### ISSUE TITLE
SSN recommendation has incorrect "qudt-1-1:numericalValue" in Tree height example

### ISSUE THREAD

**Issue by sanderzz91** [w3c/sdw#1017]
Hi,

I'd like to report that, in the SSN recommendation, the "tree height measurement" example (example 12/section B.4) uses an incorrect `qudt-1-1:numericalValue` in the statements about `<observation/1087>`. I think the property to use should be `qudt-1-1:numericValue`.

Kind regards.

**Comment by maximelefrancois86** [comment]
True, pull request #1018 fixes this.
Thank you for reporting
