### ISSUE TITLE
BP 3 needs more content

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#102]
Especially the Possible Approach to Implementation section needs more content. But perhaps also the Why section.

Notes not yet included in the text: 
- incorporates assignment of URIs based on scoped identifiers (e.g. Feature IDs from a dataset or local identifiers within tabular data); assignment of URIs to ‘blank nodes’ (plus note on subsequent reconciliation; non-unique naming is inevitable) … SIRF, schema.org etc.
- something about toponyms?
- should this move to “Exposing data through APIs” section? (Not in my opinion - lvdbrink)

**Comment by 6a6d74** [comment]
@edparsons said in his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0013.html):

<em>This is where GIS has traditionally been the tool of choice, I agree we need to accept this as best practice despite the potential pitfalls...</em>

**Comment by 6a6d74** [comment]
@Fransie said in point (12) of his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0015.html)

<em>[...] instead of “Working with data that lacks globally unique identifiers for entity-level resources” one could write “make spatial relationships explicit”</em>.

This misses the intended point of the BP; the concern is not so much making spatial relationships explicit, but what to do if your data doesn't use URIs. How do you convert from locally scoped identifier to URI?

**Comment by 6a6d74** [comment]
The scope of this Best Practice isn't quite correct. The intent is that it helps practitioners decide what to do when their data doesn't already have URIs, but at present it's more about reconciliation and linking with other resources (which overlaps with <a href="http://w3c.github.io/sdw/bp/#link-to-related-resources">Best Practice 23: Link to related resources</a>). The previous title ("<em>Working with data that lacks globally unique identifiers for entity-level resources</em>") and description ("<em>Create Spatial reconciliation across datasets</em>") have been changed to reflect this.</p>

So far we have discussed the short comings of using names as identifiers (and the subsequent need for reconciliation). We also need to discuss assigning URIs based on local identifiers; for example, row numbers from tabular data or Feature identifiers from geo-databases.</p>

This Best Practice needs more content ... or it might even be possible to merge it with <a href="http://w3c.github.io/sdw/bp/#globally-unique-ids">Best Practice 1: Use globally unique HTTP identifiers for entity-level resources</a> as it is really all about using globally unique identifiers.

**Comment by PeterParslow** [comment]
There are a lot more examples of poor results from spatial coincidence. The one given now could be solved by 3D spatial queries (OK, a bit of a dream). But accidently creating relationships between physical and social geography 'spatial things' would also be a hazard - easily avoided if/when the data has good semantics, but that's not the case in the things discussed here. Example (England): the 'on and off' coincidence between a Public Right of Way and a physical track or path. Once again, there are many times this doesn't matter, and then you get sued / fined.

**Comment by lvdbrink** [comment]
BP3 no longer exists, it has been merged with [Use globally unique HTTP identifiers for spatial things](http://w3c.github.io/sdw/bp/#globally-unique-ids) in the restructured BP document.
