### ISSUE TITLE
State of the Art assertion is incomplete

### ISSUE THREAD

**Issue by cmheazel** [w3c/sdw#1020]
The standards supporting the listed use cases exist and have been in operational use for many years.  See http://www.gwg.nga.mil/misb/.  The MISB standards are closely coordinated with the SMPTE.  These are public standards developed in cooperation with the motion imagery community.  Leveraging the MPEG metadata stream assures tight synchronization of the metadata with the essence.  In addition, the MPEG Transport Stream assures that dropped and corrupted packets (common in video feeds) are quickly recovered.

**Comment by cmheazel** [comment]
The MPEG Transport Stream standards address transfer of the video over streaming media.  For file transfers use the SMPTE Material Exchange Format (MXF) standard.  MXF was designed to exchange synchronized essence (video, audio, etc.) and supporting descriptive metadata.

**Comment by cmheazel** [comment]
Motion imagery metadata for both MPEG and MXF is stored using Key-Length-Value (SMPTE 336M-2007) encoding.  The SMPTE KLV register is at https://registry.smpte-ra.org/apps/pages/published/.  MISB has extended the SMPTE register (see MISB Std 0807.20).  These extensions include a large number of spatial-temporal metadata elements (orbital mechanics anyone?).  See the KLV Users Guild (MISB TRM 1006) for an introduction to KLV. 
XML has been generated from KLV metadata streams and JSON is certainly possible.

**Comment by cmheazel** [comment]
More state of the art: ESRI implements the MISB standards discussed above in their FMV Add-in.  See the announcement at [ESRI FMV](https://community.esri.com/message/625504) with a tutorial and documentation available from [FMV Tutorial](https://community.esri.com/external-link.jspa?url=http%3A%2F%2Fesriurl.com%2FFMVexercises).

**Comment by rjksmith** [comment]
Updated State of the Art with more details including MXF and SMPTE KLVs to address #1020
