### ISSUE TITLE
Inverse property for ssn:hasSubSystem

### ISSUE THREAD

**Issue by sanderzz91** [w3c/sdw#1022]
Hi,

I'd like to point out that adding an inverse property for `ssn:hasSubSystem` may be an improvement.

The application that I'm developing now knows the URLs of sensors from the start, but not the system hierarchy in which the sensor is deployed, so the goal is to host at the URL of the sensor what its parent system is. This is impossible with the `ssn:hasSubSystem` property, I would need the inverse property, which does not exist. 

And once the application fetches the semantic description of a sensor's parent system, it should read if it also has a parent system, and so on. Again, this isn't possible with `ssn:hasSubSystem`.

I guess I'm going to write a little extension to the ssn ontology to provide an inverse property for `ssn:hasSubSystem`.

But maybe such a change would benefit other developers. I see that you thought of this already anyway, since you have this statement in the ssn ontology file:

```
ssn:System rdfs:subClassOf [ 
    a owl:Restriction ; 
    owl:onProperty [ 
        owl:inverseOf ssn:hasSubSystem 
    ] ; 
    owl:allValuesFrom ssn:System 
]
```

Also I think it's strange that you provided a two-way relation between `ssn:System` and `sosa:Platform`, but not between `ssn:System`s. I think as well that the conceptual difference between `ssn:System` and `sosa:Platform` isn't that clear. How are they different? To me, the following comment in one of the examples was the most helpful so far:

```
<PCBBoard1> a ssn:System , sosa:Platform ;
  rdfs:comment "PCB Board 1 hosts DHT22 temperature and humidity sensor #4578 permanently, one can say it has it as one of its subsystems."@en ;
```

Kind regards.

**Comment by maximelefrancois86** [comment]
Hi, 

Thanks for this remarks.

We did not reach a consensus on whether or not such a property had to be defined, so this is left for a potential future version of the SSN ontology. This is not planned at the moment. It can only be done by a new Working Group with a charter that state a new version of the SSN ontology will be published as a recommendation --> 2 years process.

In the meantime, at the URL of the sensor, nothing prevents you from providing information about its super-system. Example: 

```
REQ: GET sensor/123

RES: 200 OK
Content-Type: text/turtle

@prefix ssn: <http://www.w3.org/ns/sosa/>.
@prefix ssn: <http://www.w3.org/ns/ssn/>.
@base <> <http://example.org/>.

<sensor/123> a sosa:Sensor .
<system1> ssn:hasSubSystem <sensor/123> .
```

You can of course create your own extension of SSN and define an inverse property for `ssn:hasSubSystem`. 

As for the distinction between `ssn:hasSubSystem` and a `sosa:hosts`, you can use one or both, depending on what you need. I explained (my understanding of) the distinction between the two concepts in a paper submitted at ESWC this year (rejected unfortunately, but openly accessible online). Maybe this can help https://2018.eswc-conferences.org/paper_196/  See p. 10 and 11, section p. 4.1, paragraph *Smart-Sensors Composition*.

**Comment by dr-shorthair** [comment]
Resolved to make no change in SDWIG f2f - Lyon TPAC 2018-10-23

RESOLUTION: Re. #1022, we will not add an inverse property for ssn:hasSubSystem, because this would introduce a normative change, and can be done in one's own applications

However, it may be considered for a future version of SNN.

**Comment by maximelefrancois86** [comment]
Update: see p10 of 

> Samya Sagar, Maxime Lefrançois, Issam Rebai, Khemaja Maha, Serge Garlatti, Jamel Feki, Lionel Médini. Modeling Smart Sensors on top of SOSA/SSN and WoT TD with the Semantic Smart Sensor Network (S3N) modular Ontology. In Emerging Topics in Semantic Technologies. ISWC 2018 Satellite Events. E. Demidova, A.J. Zaveri, E. Simperl (Eds.), ISBN: 978-3-89838-736-1, 2018, AKA Verlag Berlin., preprint http://ceur-ws.org/Vol-2213/best-paper-1-preprint.pdf
