### ISSUE TITLE
Worked examples using hasUltimateFeatureOfInterest

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw#1027]
@smrgeoinfo and @denevers can you help?

**Comment by denevers** [comment]
I'll need some catch-up reading first...

**Comment by KathiSchleidt** [comment]
In the Water domain, I see samplingFeature FoIs requiring a contextual link as UFoI (nice that we've finally managed to integrate UFOs ;) ) to:

- River
- Aquifer

In Biodiversity, the speciesObservationPoint could also go to something larger, but still semantically chewing on what that would be. First bang is the population of a specific area, i.e. a protected site or survey area; not clear how this is related to the site itself yet...

In air quality things are a bit too ethereal, but meteo could be worth exploring as they have other features they may wish to relate to (prevailing currents, also some radiation cloud examples tickling the back of my brain)

**Comment by sgrellet** [comment]
Lets give a quick try for 'Groundwater level monitoring'.
Observation -> timeSeries
Observation.FoI=Well (or Piezometer attached to it)
ObservationUFoI=The Aquifer

Does that help or do you need a more detailed example ?

**Comment by denevers** [comment]
@sgrellet , wouldn't the UFoi be the groundwater body ?

**Comment by denevers** [comment]
@grellet.  point taken

**Comment by smrgeoinfo** [comment]
Here's a diagram showing a cascade of sampling events with different ultimate features of interest
![sampling-featureofinterestrelations](https://user-images.githubusercontent.com/513380/39262645-cc45d508-4874-11e8-93a9-b1f5b6e54ef0.jpg)

I haven't tried the rdf encoding for this.

**Comment by dr-shorthair** [comment]
The rules in the draft spec say that _if a UFoI is not provided explicitly_, then the UFoI can be inferred by following the chain of `isSampleOf` links until you get to a feature that doesn't have one. But this is always overridden (I hesitate to say 'trumped') if an explicit UFoI is indicated. So I think the 'different UFoI' case illustrated by @smrgeoinfo is accommodated by the proposal.

**Comment by dr-shorthair** [comment]
I believe the worked examples now in the document and also in the RDF folder resolve this issue
