### ISSUE TITLE
List & group features

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#1030]
This is the first step needed to create the SDW Roadmap: 

Analysis of all the features, list them, group them; decide on 1 or several pages. Scope: Spatial + Web. Not only what the WG is discussing, but an overview of the relevant things that exist in SDW space.

"Features" are the things / tech components a roadmap talks about. Finding the right granularity at which features are identified is important in this first step.

**Comment by lvdbrink** [comment]
Examples: 
https://www.w3.org/2018/01/web-roadmaps/mobile/

This one groups the "Web Applications on Mobile" into 12 groups of features, each group has its own page.

**Comment by lvdbrink** [comment]
If we want several pages, a home page + icons are needed for the subtopics. Existing ones can be reused, extra icons will need to be created, preferably matching the style of the existing ones. Format: SVG. We can start with rough drawings.

**Comment by lvdbrink** [comment]
See https://github.com/w3c/sdw/blob/gh-pages/roadmap/analysis.md

**Comment by MichaelGordon** [comment]
Not helpful for the overfull grouping of group 1 but I can think of a few more things potentially, espcially if the scope includes standards in any maturity phase (my assumption on reading that means that they might be so mature that they don't use SDW BP): 

 I might split present a view into partioning data for the web and presenting a view - 

Partitioning data for the web -

- Vector Tiling
- Raster Tiling
- Data cubes

To present a view:

- WMS
- WMTS
- XYZ
- MapML

To provide access to data - 

- WFS 3.0
- WCS

To process data - 

- WPS

**Comment by lvdbrink** [comment]
Yes, that was one of the things I was wondering about and wanting feedback from the group: Do we list all those mature, but not very 'webby' in our sense, standards? If we do we potentially have a long list of OGC standards to go...

If we go with just the web service standards as you're doing here, that narrows it down at least. (now I'm adding SOS in my mind)

**Comment by tidoust** [comment]
I haven't given it much thoughts, but I wonder if we could follow a sort of data pipeline to categorize technologies, completed with a couple of other sections, as was done in the media roadmap (capture, process, distribute, playback). This could help break group 1 a bit. For instance, reusing the subcategories names that you have in the proposed structure, we could have:

- capture spatial/sensor data
  - "to get a device's location"
  - relevant parts of SensorThingsAPI
  - APIs based on the Generic Sensor API
  - relevant WoT work
- represent spatial data
  - "to represent spatial data: vocabularies / encodings"
  - "moving features XML and CSV"
  - WoT Thing Description
  - "to represent geometry"
  - "to reference a location"
  - "to geotag video"
- publish spatial data on the Web
  - "general guidelines" (without SSN related specs)
  - "to describe a spatial dataset"
  - "to present a view" (MapML, WMS, WMTS, XYZ)
  - "to provide access"
  - "to query using spatial operators"
- transform spatial data (before / after publication)
  - Partitioning data for the web proposed by Michael
  - WPS
- sensor data:
  - "general guidelines" (only SSN related specs)
  - "to represent: vocabularies / encodings"
  - "to work with"
  - relevant WoT work
- temporal data:
  - "to represent: vocabularies / encodings"
- stats:
  - statsBP
  - data cube, SDMX, DDI, SKOS, etc/.
  - existing classifications? (activities, products, etc.)

**Comment by lvdbrink** [comment]
RE scope @edpars0ns said: Mass market audience scope / broad community of users. 

We had a [discussion](https://www.w3.org/2018/06/05-sdw-minutes.html#x07) at the f2f in Fort Collins about whether or not OGC standards, which are not in our view 'web friendly', should be part of the roadmap. We did not exactly resolve this question. I think it was a good suggestion to add them, but under a 'not relevant to this roadmap' section. Standards in this section could be 
- standards which have been replaced (e.g. O&M > SSN)
- standards which are too complicated / not web friendly enough for a mass audience
- standards which are using http for transport only, not as an interface

However, these criteria were not fully agreed either. It will be a somewhat subjective exercise. We plan to let the OGC architecture board review it.

**Comment by lvdbrink** [comment]
Based on the ideas of @tidoust and the input of @MichaelGordon I created a new [grouping proposal][1].

It looks as though it could work to create a roadmap with four main groups: 
- capturing spatial data
- represeting spatial data
- publishing spatial data
- transforming spatial data

The first and last groups are smaller than the second and third. I'm not convinced the last group 'transforming spatial data' will work as well as the others. 

Comments and proposals are welcome! Once we have the main groups (or decide to have just 1 main group and 1 roadmap page, but I'm in favour of going with these 3 or 4 groups) we can start creating the roadmap and describing and categorizing all the features (well-deployed, in progress, not web-friendly enough). 

[1]: https://github.com/w3c/sdw/blob/gh-pages/roadmap/analysis.md#step-2-grouping
