### ISSUE TITLE
WebVMT: Change name of div-id / tile-url attributes

### ISSUE THREAD

**Issue by tidoust** [w3c/sdw#1033]
I cannot seem to find a pointer for now, but I believe having a `-` in attribute names where the first part is not a generic namespace-like string (e.g. `aria-*` attributes) is not good practice.

Also `div-id` seems to be a bad name because there is no reason to believe that the element will always be a `<div>`. One possibility could perhaps be to reuse the [`for` attribute of `label` tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label).

**Comment by tidoust** [comment]
Replying to myself with a link to the relevant spec:

> I cannot seem to find a pointer for now, but I believe having a - in attribute names where the first part is not a generic namespace-like string (e.g. aria-* attributes) is not good practice.

See [casing rules](https://w3ctag.github.io/design-principles/#casing-rules) in the Client-Side API Design Principles document developed by the TAG: "HTML elements and attributes", "lowercase, concatenated".

**Comment by rjksmith** [comment]
You're right. These names made sense when they were CSS-like properties of the MAP block, but that's no longer true.

I already renamed `div-id` to `map-id`, though it sounds as if we should drop the hyphenation too.

MAP Property | Proposed &lt;track&gt; Attribute | Description
------------ | ------------- | -------------
`div-id ` | `mapid` or `for` | Map display element id
`tile-url` | `tileurl` | URL for map tile layer
 n/a | `attribution` | Attribution text, e.g. copyright message

**Comment by rjksmith** [comment]
Track attributes renamed
