### ISSUE TITLE
May I have access to the MapML project so that I can add tasks and descriptions and links etc.

### ISSUE THREAD

**Issue by prushforth** [w3c/sdw#1045]
Thank you

**Comment by prushforth** [comment]
Perhaps I just fork the whole repo and submit a pull request.  Which I am preparing, so maybe access is not required. Thanks

**Comment by tidoust** [comment]
@prushforth I added you to the editing team for the repo, which should give you the appropriate rights.

**Comment by prushforth** [comment]
Thank you kindly!  Projects don't seem to be replicated when you fork the thing anyway.
