### ISSUE TITLE
CRS negotiation in MapML

### ISSUE THREAD

**Issue by prushforth** [w3c/sdw#1058]
Each MapML document has a single TCRS, which is either declared in a `<meta>` tag or by the required `<extent@units>` attribute, (if the document has the optional `<extent>` element).

When the referring `<map>` has a different declared projection (TCRS), currently the client (which in the future may be the browser) disables the layer and does not make tile/image/feature requests.

What if the MapML document was able to declare that its content was also available under a different TCRS, using one or more appropriately configured `<link rel="alternate" projection="{TCRS_NAME_HERE}" href="...">` elements?  Could (should?) the client transparently redirect to the more appropriate map resource?

```
<mapml>
  <head>
    <title>Canada Base Map - Transportation (CBMT)</title>
    <meta http-equiv="Content-Type" content="text/mapml"/>
    <meta charset="utf-8"/>
    <base href="/api/beta/mapml/en/cbmtile/cbmt/"/>
    <link rel="license" href="https://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/free-data-geogratis/licence/17285" title="Canada Base Map © Natural Resources Canada"/>
==> <link rel="alternate" projection="OSMTILE" href="http://geogratis.gc.ca/api/beta/mapml/en/osmtile/cbmt/"/>
    <link rel="zoomin" href="/api/beta/mapml/en/cbmtile/cbmt/?z=18" type="text/mapml"/>
  </head>
  <body>
    <extent units="CBMTILE" method="GET">
      <input name="z" type="zoom" value="0" min="0" max="17"/>
      <input name="projection" type="projection" value="CBMTILE"/>
      <input name="y" type="location" units="tilematrix" axis="row"/>
      <input name="x" type="location" units="tilematrix" axis="column"/>
      <template type="tile" tref="https://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer/tile/{z}/{y}/{x}?m4h=t"/>
    </extent>
  </body>
</mapml>

```

More discussion [here](https://github.com/Maps4HTML/MapML/issues/11) and [here](https://github.com/w3c/sdw/issues/757).

**Comment by prushforth** [comment]
I had a stab at client side CRS negotiation.  If you load [this Web Mercator map](http://geogratis.gc.ca/api/beta/mapml/en/osmtile/cbmt/) and then paste this URL 

[http://geogratis.gc.ca/api/beta/mapml/static/cubeserv_precipitation.mapml](http://geogratis.gc.ca/api/beta/mapml/static/cubeserv_precipitation.mapml)

into the "Add a MapML URL to this map:" text box, the client will detect that the requested projection doesn't match the projection of the document, and will follow a more appropriate link if it exists in the `<head>`.  The same document will work when pasted onto a [polar](http://geogratis.gc.ca/api/beta/mapml/en/apstile/arctic/) or [Lambert](http://geogratis.gc.ca/api/beta/mapml/en/cbmtile/cbmtsimple/) map.

Let me know if you find something doesn't work, or have comments.

**Comment by lvdbrink** [comment]
It works nicely! The `projection`  attribute of `<link>` is not standardized, right? Nevertheless, maybe a quite simple solution to the CRS negotiation problem.

**Comment by prushforth** [comment]
Thanks!

It's true, the projection attribute is specific to MapML.  I had a [discussion ](https://github.com/opengeospatial/D012-MapML_Engineering_Report/issues/31)with Keith Pomakis about the design of that yesterday.

**Comment by dvh** [comment]
Hi. @lvdbrink pointed me here because I don't know much about MapML but I'm interested in standardising CRS negotiation ;)

Using our REST APIs, a client can send geometries in a specific CRS and a server can reply geometries in a specific CRS. Using response headers, we could use the `Link` approach mentioned here to tell the client which CRS is used in the response, but then we'd still have to find a proper way to do this in a request.

We chose to introduce an `Accept-Crs` request header to let the client negotiate a preferred CRS and a `Content-Crs` header to identify the CRS used in both the payload of the request as the payload of the response.

How is this compared to the MapML usecase?

**Comment by larsgsvensson** [comment]
At this point I'd like to point to the work on content negotiation by profile going on in the [Data Exchange WG](/w3c/dxwg). The use of a specific CRS could be seen as a special case of an application profile. The current suggestion is to register the headers `Accept-Profile` and `Content-Profile` and then let conforming servers evaluate those.

**Comment by prushforth** [comment]
@larsgsvensson and @dvh Interesting.  I don't think headers will work for MapML, because the "tiled coordinate reference system" concept, and the definition of 'WGS84' are defined only within MapML as "projection" [values](https://maps4html.github.io/MapML/spec/#semantics). 

MapML aims to be a defined internet media type (text/mapml), so the definition of the media type would make it self-describing, as I understand that concept. A profile would seem to be an extension of a media type, if I understand the concept correctly.   Perhaps when the definition of TCRS is widely enough accepted these could be considered profiles and header-based negotiation could also work.  As a first pass, and without implying deeper protocol inspection than I wanted to get into at this time, having the media type provide a facility to adapt to the runtime environment seemed like a win.

Early on I did try negotiating the projection off a media type parameter but that did not work very well, so I abandoned that idea.

> We chose to introduce an Accept-Crs request header to let the client negotiate a preferred CRS and a Content-Crs header to identify the CRS used in both the payload of the request as the payload of the response.

@dvh where an API would be negotiating with a client for GeoJSON or KML for example, what value of `Accept-Crs` would be used (the axes in those formats, like MapML, are ordered [long,lat], which is defined only in the format and not by a well-known CRS identifier, IIRC)?

**Comment by lvdbrink** [comment]
@larsgsvensson we did speak with you about using profiles for crs negotiation before (must be at least a year ago) but at the time it was not clear if profiles would solve this. Is there more progress on this particular use of profiles now? (I should pay more attention to the DXWG I know...)

**Comment by larsgsvensson** [comment]
@lvdbrink No I'm afraid there hasn't been a lot progress so far... We can catch up in Lyon (assuming you'll be at the TPAC)

@prushforth scripsit:
> A profile would seem to be an extension of a media type, if I understand the concept correctly. 

No, profiles are orthogonal to media types. The idea is that you have a certain data model and serialise that in XML, Turtle, or JSON-LD while still retaining the semantics and structurd of the underlying data.

Let's see what we can make out of the use case @rob-metalinkage just created.

**Comment by lvdbrink** [comment]
Use case at DXWG: https://github.com/w3c/dxwg/issues/311

**Comment by prushforth** [comment]
I'm going to go ahead and close this issue, as the related issue for [CRS negotiation](https://github.com/w3c/dxwg/issues/311) has been closed.  We are pretty happy with how MapML deals with CRS selection, and this is now implemented in CubeServe and GeoServer (MapML Community Module).

**Comment by prushforth** [comment]
[Here is an example of content negotiation over map CRS in MapML](https://maps4html.org/experiments/change-projection/projection-negotiation/)
