### ISSUE TITLE
Irc logs from #mapml channel during breakout

### ISSUE THREAD

**Issue by prushforth** [w3c/sdw#1090]
Hi Jeremy, Thank you for taking some notes I believe, anyway, during our MapML breakout. I don't know how to recover those, but I would like to use them as the basis for minutes that I'll post. If you know how to access, could you paste them or send a link, please? Thanks!

**Comment by cportele** [comment]
@prushforth See here: https://www.w3.org/2018/10/24-mapml-minutes.html

**Comment by prushforth** [comment]
Thanks Jeremy and Clemens
