### ISSUE TITLE
Spatial Data on the Web Best Practices Example 2 has wrong coordinate axes

### ISSUE THREAD

**Issue by nmtoken** [w3c/sdw#1118]
In EXAMPLE 2: Eddystone Lighthouse geometry (encoded as GeoJSON [RFC7946]) the document has:

    ...
      {
      “geometry”: {
        “type”: “Point”,
        “coordinates”: [50.184, -4.268]
      }
    }
   ....

which is incorrect.  GeoJSON RFC7946 has [Coordinate Reference System](https://tools.ietf.org/html/rfc7946#page-12) of **urn:ogc:def:crs:OGC::CRS84** which expresses coordinates in longitude/latitude order

So the coordinates should be `[-4.268,50.184]` just off the South coast of the the UK.

**Comment by MichaelGordon** [comment]
Committed the change in https://github.com/w3c/sdw/commit/d7c499a78f0c03bcbf3abd598197b7de5fa7a2e3

@tidoust - I completely forgot, how do we publish out the change to the w3 site?

**Comment by tidoust** [comment]
> @tidoust - I completely forgot, how do we publish out the change to the w3 site?

The document is a Note, so on W3C side, all we need is a group's call for consensus and then decision to publish an update. Not sure whether more is needed from an OGC perspective.

**Comment by ogcscotts** [comment]
Because the document is a Best Practice on the OGC side, it would need an electronic vote for update.

**Comment by lvdbrink** [comment]
@ogcscotts even for a corrigendum?

**Comment by ogcscotts** [comment]
@lvdbrink We only have a corrigendum process for standards. Best Practices are versioned, but each update is a new version. I'd be willing to ask the TC if such a minor update could be accepted by corrigendum process and if we have no objection, then proceed.

**Comment by lvdbrink** [comment]
It would be great if you could try that!

**Comment by MichaelGordon** [comment]
> @lvdbrink We only have a corrigendum process for standards. Best Practices are versioned, but each update is a new version. I'd be willing to ask the TC if such a minor update could be accepted by corrigendum process and if we have no objection, then proceed.

@ogcscotts Have we been able to advance this? I saw from Opening Plenary you were looking at PnP changes for corrigendium process for Community Standards, but have we looked at Best Practices process?

**Comment by ogcscotts** [comment]
@MichaelGordon The expansion of the corrigendum process is also planned to include Best Practices and Community Practices... I just forgot to say so in the plenary!

**Comment by MichaelGordon** [comment]
> @MichaelGordon The expansion of the corrigendum process is also planned to include Best Practices and Community Practices... I just forgot to say so in the plenary!

Awesome, thanks. I'd suggest we wait for that to land and then we can take this very minor change through.
