### ISSUE TITLE
`time:Instant` equal to another `time:Instant`

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/sdw#1126]
OWL-Time has `time:intervalEquals` to define equal `time:ProperInterval`. It also has `time:inside` to position `time:Instant` inside of `time:Interval`. I don't see anything equivalent to `time:intervalEquals` which would allow to relatively position two instances of `time:Instant` at the same (some - relative positioning) point in time.

**Comment by dr-shorthair** [comment]
In [Allen's original formulation](https://www.sciencedirect.com/science/article/pii/0004370284900080?via%3Dihub) all temporal entities are considered to be **intervals**. Time instants are merely intervals for which the beginning and end cannot be separated using the available level of precision. So in principle the topological relations should also be used on instants - as the degenerate form 

However, in OWL-Time we followed the [2006 draft by Hobbs and Pan](http://www.w3.org/TR/2006/WD-owl-time-20060927/) - see https://www.w3.org/TR/2006/WD-owl-time-20060927/#summary which specifies that both domain and range of the interval relations are `ProperInterval` - which is the subclass of `Interval` in which beginning and end can be distinguished.  So under the definitions in OWL-Time you can't use the topological relations for instants :-( 

Was this a mistake? Perhaps. 

Would correcting it (make the domain and range of the interval relations `time:Interval`, or even just `time:TemporalEntity) be disruptive? Not much. It would change entailments, but wouldn't 'invalidate' existing data. Its a pretty straightforward change though it would affect all the text definitions and global constraints in [these property definitions](https://www.w3.org/TR/owl-time/#time:intervalAfter).  

Should we consider correcting it ... ? Not sure.

**Comment by elf-pavlik** [comment]
Both [`time:before`](https://www.w3.org/TR/owl-time/#time:before) and [`time:after`](https://www.w3.org/TR/owl-time/#time:after) have domain and range `time:TemporalEntity`. At the same time ontology includes [`time:intervalBefore`](https://www.w3.org/TR/owl-time/#time:intervalBefore) and [`time:intervalAfter`](https://www.w3.org/TR/owl-time/#time:intervalAfter) which have domain and range `time:ProperInterval`. Maybe in similar way alongside [`time:intervalEquals`](https://www.w3.org/TR/owl-time/#time:intervalEquals) with domain and range `time:ProperInterval`, ontology could get additional `time:equals` which would have domain and range `time:TemporalEntity`?

**Comment by dr-shorthair** [comment]
Right. That would be a simpler solution. And also perhaps assert 
```
time:intervalEquals rdfs:subPropertyOf equals.
time:intervalBefore rdfs:subPropertyOf time:before .
time:intervalAfter rdfs:subPropertyOf time:after .
```

**Comment by elf-pavlik** [comment]
> `time:intervalEquals rdfs:subPropertyOf time:equals .`

:+1:

> do we also need `time:notEquals` where

Yes, I think with this we have all possible relations for general `time:TemporalEntity`. Also all the `rdf:subPropertyOf` alignments statements sound great!

**Comment by elf-pavlik** [comment]
Thinking about use cases we work with in https://www.valueflo.ws/ I see one which with all above might still not get covered. When describing some future temporal entity, one may not know if it will get observed and recorded as and instant or proper interval. I don't see a way to have something looser than discussed `time:equals`, so it would also cover cases when already observed and recorded:
* for two proper intervals we can have anything but `time:intervalDisjoint`
* for an interval and instant we have `time:inside`
* for two instants we have discussed `time:equals`

Pretty much some property which allows to state that two temporal entities coincide, but without implying about any of them that it is an instant or proper interval.

**Comment by dr-shorthair** [comment]
`time:notDisjoint` ?

Then all of the other relations would be sub-properties _except_ `time:before`, `time:after`, `time:notEquals` and their interval-related sub-properties.

**Comment by chris-little** [comment]
@elf-pavlik @dr-shorthair I am slightly nervous about this proposal for instants being defined/instantiated/implemented (whatever the correct verb is). To quote Prof. J R Lucas [1] : 
"The distinction between instants and intervals is one that is difficult to draw clearly. It is dangerously easy to suppose that instants must be extremely short intervals."

"The analogy between time and space, although useful here, is dangerous."

I would like some assurance that the logic and deductions that would be performed on top of the ontology, however long and big, would not get us into the difficult mathematical arena he describes. 

In essence, by equating instants to the real numbers, there is potentially an uncountably infinite continuum of them, whereas specified intervals will presumably be only countably infinite, I.e. between ANY two instants, there will always be more instants (an infinite number in fact), and we choose intervals that we could potentially list. The problem is that we are now in an area of mathematical set theory, where some things have been proved that they cannot be proved true or false!

I think that if the logic is always a discrete number of logical deductions, we are safe, but if there is some kind of quantative deduction involving arithmetic and measures, the logic cannot be guaranteed by mathematics. 

I am probably worrying unnecessarily.

[1] "A Treatise on Time and Space", J R Lucas, Methuen & Co Ltd, 1973. ISBN 0416 75070 2. Chapter 3: Instants and Intervals.

**Comment by dr-shorthair** [comment]
@chris-little I don't think we are proposing any (new) properties tied specifically to `time:Instant`. 
I believe the proposal  is for three new properties relating temporal entities, with the existing properties related to these as indicated: 

```
time:equals a owl:ObjectProperty ;
  rdfs:domain time:TemporalEntity ;
  rdfs:range time:TemporalEntity .

time:intervalEquals rdfs:sunbPropertyOf time:equals .
```
```
time:notEquals a owl:ObjectProperty ;
  rdfs:domain time:TemporalEntity ;
  rdfs:range time:TemporalEntity .

time:before rdfs:subPropertyOf time:notEquals .
time:after rdfs:subPropertyOf time:notEquals .
time:intervalDisjoint rdfs:subPropertyOf time:notEquals .
```
```
time:notDisjoint a owl:ObjectProperty ;
  rdfs:domain time:TemporalEntity ;
  rdfs:range time:TemporalEntity .

time:equals rdfs:subPropertyOf  time:notDisjoint .
time:intervalMeets rdfs:subPropertyOf  time:notDisjoint .
time:intervalMetBy rdfs:subPropertyOf  time:notDisjoint .
time:intervalOverlaps rdfs:subPropertyOf  time:notDisjoint .
time:intervalOverlappedBy rdfs:subPropertyOf  time:notDisjoint .
time:intervalStarts rdfs:subPropertyOf  time:notDisjoint .
time:intervalStartedBy rdfs:subPropertyOf  time:notDisjoint .
time:intervalDuring rdfs:subPropertyOf  time:notDisjoint .
time:intervalContains rdfs:subPropertyOf  time:notDisjoint .
time:intervalFinishes rdfs:subPropertyOf  time:notDisjoint .
time:intervalFinished rdfs:subPropertyOf  time:notDisjoint .
```

`time:notDisjoint` is essentially the _union_ of all those relations, but has to be done with sub-properties as property-unions is not implemented directly in RDFS or OWL.

**Comment by elf-pavlik** [comment]
I wonder if naming property `time:disjoint` would make more sense, rather than naming it `time:notEquals`?

```ttl
time:disjoint a owl:ObjectProperty ;
  rdfs:domain time:TemporalEntity ;
  rdfs:range time:TemporalEntity .

time:before rdfs:subPropertyOf time:notEquals .
time:after rdfs:subPropertyOf time:notEquals .
time:intervalDisjoint rdfs:subPropertyOf time:notEquals .
```

**Comment by chris-little** [comment]
@elf-pavlik @dr-shorthair 
Happy with the renaming time:notEquals to time:disjoint (just tested it on a very small sample of other  people).
Thought about my concerns and happy with the proposed extensions providing nobody uses ontologies for mathematical induction. I.e. deduce true for n=0, then deduce true for n implies true for n+1.

**Comment by chris-little** [comment]
@dr-shorthair @elf-pavlik We have just discussed this in the W3C Spatial Data on the Web Interest Group face to face meeting in Leuven, Belgium. There was a consensus suggestion is that this extension to the OWL-Time be published as a non-normative Note. Then when there is appetite for revising the OWL-Time Recommendation, the content could then be merged. 

Are you happy with this approach?

**Comment by dr-shorthair** [comment]
Should the extension be in the same namespace? 
I think yes - in which case where would the RDF artefact be located ... ?  

I have a similar concern about ssn-ext - too many namespaces is distracting, particularly when the added elements don't introduce any significant entailments with respect to the exsting normative elements. Dunno - its a bit tricky.

**Comment by elf-pavlik** [comment]
thank you @chris-little and @dr-shorthair  👍 

I see no problem with having it published as non-normative Note, at the same time I think it should stay in the same namespace with commonly used prefix `time:`. This will also work nicely when eventually revised OWL-Time gets published with that note merged.

**Comment by dr-shorthair** [comment]
I'm drafting the note now (in a hotel room). 
See this branch: https://github.com/w3c/sdw/tree/time-entity-relations 
and preview here: https://rawgit.com/w3c/sdw/time-entity-relations/proposals/time-entity-relations/index.html

**Comment by dr-shorthair** [comment]
@elf-pavlik you have gone too quiet! 

Can you look at the draft mentioned in #1139 (peview at https://rawgit.com/w3c/sdw/time-entity-relations/proposals/time-entity-relations/index.html) and provide some examples for clause 5 please?  I think that is all we need for this to be published as a WD or W3C Note.
