### ISSUE TITLE
"IANA considerations" for OWL-Time interval relations

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw#1131]
I used the IANA process to get the OWL-Time interval relations added to the [IANA Link Relations registry.](https://www.iana.org/assignments/link-relations/link-relations.xhtml). 

However, it appears there is some unfinished business: there should be an explicit section on 'IANA Considerations' in the document as an anchor - see the discussion here: https://github.com/link-relations/registry/issues/4#issuecomment-499362149 . Can it be inserted as an erratum? 

Also relates to #215

**Comment by chris-little** [comment]
@dr-shorthair I commented at [https://github.com/link-relations/registry/issues/4#issuecomment-501709580 ]

**Comment by chris-little** [comment]
@dr-shorthair I commented at the [https://github.com/link-relations/registry/issues/4#issuecomment-501709580 | links thread]

**Comment by dr-shorthair** [comment]
Fixed by #1138
