### ISSUE TITLE
WebVMT: Proposal for data sync design, including sensors & GeoJSON

### ISSUE THREAD

**Issue by rjksmith** [w3c/sdw#1141]
WebVMT includes the [concept of synchronising arbitrary data with video and location](https://w3c.github.io/sdw/proposals/geotagging/webvmt/#datasync) which is critical for, though not limited to, two important use cases:
   1. Sensor data collected by mobile video devices, e.g. drones and dashcams;
   1. [GeoJSON](https://geojson.org) data synchronised with video.

The following design is proposed.

A <i><b>WebVMT data sync</b></i> command which consists of:
 * <b>A <i>data sync type.</i></b>
    The DataCue type of the associated metadata, [proposed in the WICG DataCue Explainer](https://github.com/WICG/datacue/blob/master/explainer.md#proposed-api-and-example-code), e.g. `org.geojson`.
 * <b><i>Data sync values.</i></b>
    An array of data values, i.e. the raw data bytes, also [proposed in the WICG DataCue Explainer](https://github.com/WICG/datacue/blob/master/explainer.md#proposed-api-and-example-code).
 * Optionally, <b>a <i>data sync path</i>.</b>
    The path identifier of the path segments associated with the data, which identifies a [WebVMT path](https://w3c.github.io/sdw/proposals/geotagging/webvmt/#dfn-webvmt-path), i.e. an object moving through the mapped space.

Comments and questions to help refine this proposal for inclusion in the [W3C Editor's Draft](https://w3c.github.io/sdw/proposals/geotagging/webvmt/) are welcomed.

**Comment by rjksmith** [comment]
Posted [Classifying Video Training Data For Machine Learning Using WebVMT](https://www.w3.org/community/webvmt-cg/2019/11/08/classifying-video-training-data-for-machine-learning-using-webvmt/) to the W3C Community Group, based on this proposal, to address an issue raised in [OGC GeoAI](https://www.opengeospatial.org/projects/groups/geoaidwg).

**Comment by ksookim** [comment]
I wonder whether you consider W3C Web Annotation Model and Protocol.

**Comment by rjksmith** [comment]
Issue migrated to WebVMT Community Group: https://github.com/webvmt/community-group/issues/1
