### ISSUE TITLE
Should the best practices mention ethical use of geo, and if so how?

### ISSUE THREAD

**Issue by MichaelGordon** [w3c/sdw#1146]
Raised during discussion of WebVMT at OGC Toulouse TC with @rjksmith 

WebVMT files provide map presentation and annotation synchronised to video content, including animation support, and more generally any form of geolocation data that is time-aligned with audio or video content.

This creates a potential issue of facial recognition combined with geospatial information knowing exactly who and where someone is. Therefore should the best practices talk about how geo should be integrated into the web in an ethical way?

**Comment by situx** [comment]
A section about ethics has been added to the best practice document.
