### ISSUE TITLE
DUL reference in new editor's draft of SSN-Extensions

### ISSUE THREAD

**Issue by smrgeoinfo** [w3c/sdw#1151]
In https://w3c.github.io/sdw/proposals/ssn-extensions/#motivation
Second bullet point:

“SSN - which adds a full axiomatization to the SOSA classes and properties, and adds additional elements relating particularly to sensor descriptions and to support alignment to **DUL**”

There is no explanation of what DUL is.

**Comment by dr-shorthair** [comment]
Considering what a shadow it casts, DUL is amazingly difficult to actually cite. 
This is the best I can currently find - http://ontologydesignpatterns.org/wiki/Ontology:DOLCE+DnS_Ultralite

Will add it to the text.
