### ISSUE TITLE
ssn:ext proposal comment: Note in section 3.1

### ISSUE THREAD

**Issue by smrgeoinfo** [w3c/sdw#1152]
Text in note on 'ultimate feature of interest' states:

> That approach was unnecessarily coy about satisfying the principle requirement, which is to know the ultimate feature of interest.

Seems to me that the OM-Light approach is as direct (not really that 'coy') than the proposed sosa approach, but more indirect in its ability to represent a sampling or observation chain.  
possible revised text:

> That approach was unclear because of the multiple possible interpretations of ‘featureOfInterest’, as well as its indirect representation of chains of sampling or observation events.

**Comment by dr-shorthair** [comment]
Thanks @smrgeoinfo I'll merge your thinking in.
