### ISSUE TITLE
Minor editorial typos in TTL definition of OWL-Time ontology

### ISSUE THREAD

**Issue by chris-little** [w3c/sdw#1161]
@dr-shorthair, @lvdbrink, @tguild   I was wondering why in the 2017 OWL-Time ontology in Turtle at https://raw.githubusercontent.com/w3c/sdw/gh-pages/time/rdf/time.ttl , the Skos declaration for the German language has the month in lower case, but all the others German definitions capitalized?   "skos:prefLabel "monat"@de ;" rather than "skos:prefLabel "Monat"@de ;" ?

And in Polish why is the year definition capitalized and all the other Polish definitions in lower case?   "skos:prefLabel "Rok"@pl ;" instead of "skos:prefLabel "rok"@pl ;" ?

These are typos. I have just checked with two native speakers - these are not subtleties of their languages.

I am assuming the Turtle tool has put everything in Unicode collation order.

_Originally posted by @chris-little in https://github.com/w3c/sdw/pull/1159#issuecomment-575102338_

**Comment by dr-shorthair** [comment]
See https://github.com/w3c/sdw/pull/1162
