### ISSUE TITLE
Support OGC profiling of W3C specifications

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/sdw#1167]
There are two drivers for profiling W3C specifications by OGC:
1) W3C scope is more general than OGC, so OGC profiles provide canonical ways to use W3C specifications for geospatial applications
2) to provide a pathway for W3C groups to get OGC input into specifications rather than reinventing the wheel - publishing a general specifications then asking the OGC to provide a profile of it consistent with other OGC specifications.

The SDIWG should perhaps take on reviewing and publishing OGC profiles of W3C specifications as necessary, to ensure there is some consistency of approach and visibility of activities in this space.

**Comment by rob-metalinkage** [comment]
Linda - assigned this to you to work out how to attach issue to rechartering as suggested in email.

**Comment by lvdbrink** [comment]
Supporting OGC profiling of W3C specs sounds like a good thing for the SDWIG to do. 

It is a more concrete task and potentially more work than the items we have in the draft charter now, listed in the [scope section](https://w3c.github.io/sdw/roadmap/charter-2020.html#scope) and the [deliverables section](https://w3c.github.io/sdw/roadmap/charter-2020.html#deliverables). 

What do members of the group think?

**Comment by cportele** [comment]
I have concerns / questions about such a general task:

* I do not see that OGC profiles of W3C specs have value per se. I have seen enough profiles that have created more issues than help that I am sceptical about a general profiling task in the charter. Profiling could be done in cases where we have concrete evidence that they will help many users. 
* Since the charter is only for two years, do we have an idea what the most important profiles are, why they are important and who would implement them? Can we list them and identify who is committed to working on them?
* Since they are called "OGC profiles" I assume it would be an OGC SWG that works on them and the SDWIG would mainly review the work and support with links between W3C and OGC groups?

**Comment by jvanulde** [comment]
Profiling should only be considered in highly specialized cases as @cportele suggests. In all other cases, the universe of specifications need to coalesce - that is the path to mass adoption IMO.

**Comment by rob-metalinkage** [comment]
It doesnt make sense to profile W3C specifications for the sake of it .. but there are plenty of specifications where spatio-temporal aspects are worth standardising beyond W3C concerns. 
We already have GeoDCAT and GeoSPARQL for example.

Coalescence of standards is not a scalable solution - one standard to cover all aspects of everything for all time is not a very useful idea. Profiling is a well known mechanism to provide incremental improvements in specificity to a more general standard for a particular purpose, and is much simpler to manage and govern than the alternatives: pushing changes into a base specification for a particular community, or duplicating the original standard and leaving it to the user to figure out what might have changed and no longer work.  Alternatively, one could describe profiles as a means  to coalesce governance overheads to meet goals with minimal effort and maximum interoperability. 

All I was suggesting is that its a common enough thing, and we probably ought to do a couple of things: 
1. try to make profiling activities and outputs a bit consistent with each other
2. publish profile relationships so people can find out relationships between OGC and W3C specs.

As to the latter - I will draft up some of these and push them as annotations to the OGC definitions server, but ideally the SDWIG could take ownership of statements about how OGC and other specs relate (above and beyond canonical statements in specs - but also where statements in specs use text labels or document locations, and unambiguous URI identifiers for such specs are established in accordance with Best Practices, which may take some time).

**Comment by lvdbrink** [comment]
Maybe we could add something to the charter, if we could phrase this in a more general way and then, once re-chartered, have a discussion on what & how specifically we could do. We have to publish the charter really soon. 

One place where profile relationships could be published is the [roadmap](https://w3c.github.io/web-roadmaps/sdw/).

**Comment by rob-metalinkage** [comment]
I'd put it this way - SDWIG should identify and support best practices for publishing and supporting profiles of W3C standards for geospatial applications, as the need for such profiles are established.

If there is genuinely no interest then this means nothing to do - but IMHO someone needs to own conversations like making updates to GeoJSON and GeoSPARQL and GeoDCAT and various -LD consistent flavours of OGC specifications consistent with each other. The OAB doesnt seem to perform this role, but should have oversight it has been done, and it requires the specialist knowledge of the SDWIG constituents. Either this should be scoped within the charter, or should be acknowledged its out of scope and some other body identified as being responsible for it.

**Comment by tguild** [comment]
I think simply adding OGC profiles of W3C specifications to list of deliverables with brief description of what a profile is

**Comment by lvdbrink** [comment]
I added the following item to the draft charter: 

> support the creation of OGC profiles of W3C specifications, in cases where spatio-temporal aspects are worth standardising beyond W3C concerns, as the need for such profiles are established.
