### ISSUE TITLE
Publish time-aggregates as W3C Public Working Draft

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw#1173]
The ESIP science-on-schema.og project [triggered the development](https://github.com/ESIPFed/science-on-schema.org/issues/77) of the [temporal-aggregates extension for OWL-Time](https://w3c.github.io/sdw/time-aggregates/) . 

We think this is now ready to be issued as a Public Working Draft, which would allow it to be referred to with confidence, and tested in action. 

Maybe a call-for-consensus?

**Comment by chris-little** [comment]
@dr-shorthair @tguild Looks good to me, but the link from the candidate PWD to the ontology with aggregate gives me a 404.

**Comment by dr-shorthair** [comment]
Fixed.

**Comment by chris-little** [comment]
@dr-shorthair I noticed that a capitalised Rok crept back in at 
:unitYear
  rdf:type :TemporalUnit ;
  rdfs:label "Year (unit of temporal duration)"@en ;
  skos:prefLabel "1 년"@kr ;
  skos:prefLabel "1年"@jp ;
  ...
  skos:prefLabel "Rok"@pl ; should be "rok"
...
 skos:prefLabel "一年"@zh ;
  
@tguild In the Japanese and Chinese texts, there is an inconsistent mixture of western and eastern digits used in the labels, 1 and 一 (yi). Do you have anyone on the staff who could give a view on correctness?

Also, some literals have Korean versions, but not consistently, several are missing. 

Apologies if this seems pedantically nit-picky.

**Comment by dr-shorthair** [comment]
I can't find the error - can you give specific link please. 
(There are some label errors in some deprecated classes from the 2006 version, but I shan't be changing those.)

**Comment by chris-little** [comment]
@dr-shorthair The Time-Aggregates doc at https://w3c.github.io/sdw/time-aggregates/  pointed to the Time Ontology at  https ://www.w3.org/2006/time which downloaded a file .../AppData/Local/Temp/time-3

**Comment by dr-shorthair** [comment]
That shows that the static representation at the NS URI https://www.w3.org/2006/time has not been re-synced with the file from GitHub. That requires some work from @tguild behind the scenes I think.

**Comment by lvdbrink** [comment]
Is this intended to be on REC track? 

And is everything ready for a call for consensus or are we waiting for @tguild to do something?

**Comment by tguild** [comment]
> @dr-shorthair I noticed that a capitalised Rok crept back in at
> :unitYear
> rdf:type :TemporalUnit ;
> rdfs:label "Year (unit of temporal duration)"@en ;
> skos:prefLabel "1 년"@kr ;
> skos:prefLabel "1年"@jp ;
> ...
> skos:prefLabel "Rok"@pl ; should be "rok"
> ...
> skos:prefLabel "一年"@zh ;
> 
> @tguild In the Japanese and Chinese texts, there is an inconsistent mixture of western and eastern digits used in the labels, 1 and 一 (yi - _one_). Do you have anyone on the staff who could give a view on correctness?
> 
> Also, some literals have Korean versions, but not consistently, several are missing. I am not in a position to propose anything. Though I could add all the Greek options.
> 
> Apologies if this seems pedantically nit-picky.

we should submit to a formal horizontal review 

https://github.com/w3c/i18n-request

**Comment by tguild** [comment]
> Is this intended to be on REC track?
> 
> And is everything ready for a call for consensus or are we waiting for @tguild to do something?

This appears to be a First Public Working Draft, new spec. Unsure how to handle new extensions with current Interest Group charter. We may have to start off as a Note and then move to REC track after rechartering as an IG

I'll discuss with @plehegar and follow up

**Comment by plehegar** [comment]
@tguild is correct. The IG can only publish Interest Group notes. Once it becomes a WG, it can be put on the W3C Recommendation track.

**Comment by dr-shorthair** [comment]
I'm happy to start with a 'Note' - I think that is appropriate. I suspect there are just a couple of changes in the config required?

**Comment by dr-shorthair** [comment]
@tguild can you help re-syncing the RDF file from GitHub to the NS? - https://github.com/w3c/sdw/issues/1173#issuecomment-608117375

**Comment by lvdbrink** [comment]
> I'm happy to start with a 'Note' - I think that is appropriate. I suspect there are just a couple of changes in the config required?

Not that much - the config already has `noRecTrack = true`. We only need to set the right status when publishing. Not sure if the correct one in this case is `FPWD-NOTE` or `IG-NOTE`.

**Comment by tguild** [comment]
IG-NOTE, I'm pretty sure but will work with @dr-shorthair on getting it to pass W3C pubrules etc. I can/do minor last minute tweaks as I stage the document for publication.

CfC to IG for Note next step I guess

**Comment by lvdbrink** [comment]
One more thing - if we want to publish it as an IG Note at the W3C side, normally we'd want to publish it as an OGC discussion paper as well. @dr-shorthair is that the intent here? If so, we'd need to request an OGC doc nr and stick that in the draft.

**Comment by dr-shorthair** [comment]
I added OGC doc number

**Comment by tguild** [comment]
@dr-shorthair certaintly, done

**Comment by tguild** [comment]
@dr-shorthair is there documentation of all the ns used? Also open to figuring out how to streamline and/or let you publish directly once I have a good mapping

**Comment by dr-shorthair** [comment]
Sorry @tguild I don't understand the question. Here is the RDF file https://github.com/w3c/sdw/blob/gh-pages/time-aggregates/rdf/time-agg.ttl 
that shows all the ns used in the t-box. And there are some a-box examples here https://github.com/w3c/sdw/tree/gh-pages/time-aggregates/rdf/examples which shows them in action.

**Comment by tguild** [comment]
Sorry, missed the response earlier @dr-shorthair 

I was wondering if there was a mapping (besides in the specs themselves) of the various namespaces used by the various time, sosa, ssn specs with their w3.org uris and their corresponding sources in github repos. This is the second time I've had to play catch up when people have noticed they are out of sync and would prefer to ensure we're better about it or even automate updates.

**Comment by dr-shorthair** [comment]
OK - this is what I understand

Prefix | primary graph |  Github location 
--- | --- | --- 
sosa: | http://www.w3.org/ns/sosa/ | https://github.com/w3c/sdw/blob/gh-pages/ssn/integrated/sosa.ttl 
ssn: | http://www.w3.org/ns/ssn/ | https://github.com/w3c/sdw/blob/gh-pages/ssn/integrated/ssn.ttl 
time: | http://www.w3.org/2006/time | https://github.com/w3c/sdw/blob/gh-pages/time/rdf/time.ttl 

However, there are a number of additional graphs that add resources to these namespaces, or additional axioms to resources in these namespaces. No new namespaces were coined because they are likely to be folded into the primary graph in a future revision and we don't want people to use yetanother ns in the interim only to go back to the original later (URIs are forever...): 

Prefix | supplementary graph |  Github location 
--- | --- | ---
time: | https://www.w3.org/2006/time/agg | https://github.com/w3c/sdw/blob/gh-pages/time-aggregates/rdf/time-agg.ttl
time: | https://www.w3.org/2006/time/rel | https://github.com/w3c/sdw/blob/gh-pages/time-entity-relations/rdf/time-rel.ttl 
sosa: | http://www.w3.org/ns/ssn/ext | https://github.com/w3c/sdw/blob/gh-pages/ssn-extensions/rdf/ssn-ext.ttl

**Comment by dr-shorthair** [comment]
Preview at
https://rawgit.com/w3c/sdw/gh-pages/time-aggregates/index.html or
https://w3c.github.io/sdw/time-aggregates/

**Comment by chris-little** [comment]
@dr-shorthair, @tguild  Thank you. Spotted a couple of minor inconsistencies, but again in the  [referenced time ontology](https://www.w3.org/2006/time). Rhetorical question: why does my brain see them, even without coffee? ;-)
1. In skos, the language tags (@en, @zh, etc) seem to adhere to IETF BCP47/RFC5646, which states "Interoperability is best served when the same language tag is used consistently to represent the same language." Japanese is represented by both @ja and @jp. 
@ja is the defined tag for the Japanese language, and @jp is not defined in ISO639 etc. 
jp is the code for the country Japan.
Is it too late to alter, or should we just leave it as is? 
@ja is used in for the days of the week for the 2006 version (Monday, Tuesday, etc) 
@jp occurs only in the unitSecond, unitMinute, unitHour, unitDay, unitWeek, unitMonth and unitYear definitions.

2. The text for the Asian languages for the unit definitions still have some inconsistencies, using both Chinese '一' ("yi") and Western '1' ("unit"). The Chinese is now consistent, but unitWeek and unitYear are using the western 1 for both Japanese and Korean. Native speaker needs to confirm correctness or correct.

3. An upper-case has crept back into the Polish definition for unitSecond: 
"skos:prefLabel "Sekundę"@pl ;" should read "skos:prefLabel "sekundę"@pl ;"

**Comment by dr-shorthair** [comment]
@chris-little - can you make the fixes and issue a PR?

**Comment by chris-little** [comment]
@dr-shorthair Yes, I will do that, but is there a file in a GitHub? I only ever see a file that is downloaded to my browser.
Alternatively, I can edit that file, but then need to know where to upload it.

**Comment by tguild** [comment]
After pr is merged in github to the gh-pages branch, I can stage it for publication on W3C site like I did for 

https://www.w3.org/TR/2020/NOTE-vocab-owl-time-rel-20200630/

We should be able to publish on Thursday if ready and passes pubrules (I can do initial checks today) or next week (Tuesday or Thursday)

**Comment by chris-little** [comment]
@dr-shorthair @tguild PR created with all minor language corrections, except one..i am still awaiting a suggestion from a Korean.

**Comment by tguild** [comment]
thanks @chris-little I'll  check out the document.

As we neglected to send the call for consensus for entity Note earlier, I can't publish that today. I will stage both documents for publication on Tuesday 7 July and confirm with you and @dr-shorthair before doing so

**Comment by chris-little** [comment]
@dr-shorthair Simon, I do not want to hold up publication, but Nobu and Kyoung-sook made suggestions about the Japanaese and Korean language tags which imply that the original tags may have been misconstrued. To make sensible corrections, I need to understand the use and intent of the multiple language tags - that is, the skos:prefLabels. My onoological ignorance is now showing.

DayofWeek is tied to the Gregorian Calendar and the labels like below are not problematic (though Korean is missing):
:Friday
  rdf:type :DayOfWeek ;
  rdfs:label "Friday"@en ;
  skos:prefLabel "Freitag"@de ;
  skos:prefLabel "Friday"@en ;
  ...
  skos:prefLabel "星期五"@zh ;
  skos:prefLabel "金曜日"@ja ;

The durations unitSecond, unitMinute, unitHour, unitDay, unitWeek, unitMonth and unitYear have been translated very literally into Chinese, Japanese and Korean. Hence the one or yi meaning a 'unit'. All the other skos:prefLabels in the other languages are just the name, like a Unit of Measure. Is this a good way to think of these labels? Would they be used with numeric values?

If so, then  unitYear skos:prefLabel "一年"@ja ;  used to express three years, would end up as the rather strange "三 一年" (3 unitYear) rather than "三 年" (3 year) .

:unitYear
  rdf:type :TemporalUnit ;
  rdfs:label "Year (unit of temporal duration)"@en ;
  skos:prefLabel "1 년"@kr ;
  skos:prefLabel "一年"@ja ;
  skos:prefLabel "Jahr"@de ;
  skos:prefLabel "rok"@pl 

I hope my concerns make sense.

**Comment by dr-shorthair** [comment]
The issue with the labels has been moved to #1181 as it is not related to the preparation and publication of the new notes.

**Comment by dr-shorthair** [comment]
> @chris-little - can you make the fixes and issue a PR?

I should not have responded in this issue - should have created new issue at this stage. :-(

**Comment by chris-little** [comment]
@dr-shorthair On it's way, just awaiting confirmation from Nobu and Kyoung-Sook that my proposals are not silly. I suspect some of the original multilingual Preferred Labels came via machine translation

**Comment by dr-shorthair** [comment]
Published as IG Note 2020-07-07 - see https://www.w3.org/TR/vocab-owl-time-agg/
