### ISSUE TITLE
Formalise release of SDWWG W3C notes as OGC discussion papers

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/sdw#1174]
When the WG released W3C notes:

https://www.w3.org/TR/qb4st/ ( OGC doc  OGC 16-142) 
 and 
https://www.w3.org/TR/2017/NOTE-eo-qb-20170928/  (OGC 16-125)

they were assumed to have the status of OGC discussion papers - but internal processes mean they only appear in OGC document registers when the TC votes to release them - and that step got missed. 

According to Scott a motion from the SDW - or a request perhaps to the Geosemantics WG to perform one is needed to bring it to the TC to electronically vote. Can I request the chairs to initiate one or other procedure please?

**Comment by lvdbrink** [comment]
This also goes for

https://www.w3.org/TR/covjson-overview/ OGC 16-145

@ogcscotts I believe a motion from the SDW is enough - this is an OGC group as well as a W3C group, right?

**Comment by ogcscotts** [comment]
@lvdbrink yes, a motion from SDWIG is sufficient as it is an OGC subcommittee

**Comment by lvdbrink** [comment]
This has been done a long while ago. See the motion [here](https://lists.w3.org/Archives/Public/public-sdwig/2020Apr/0030.html). 

The Notes mentioned above are available from the [OGC discussion paper page](https://www.ogc.org/docs/discussion-papers).
