### ISSUE TITLE
Publish time-entity-relations as W3C Public Working Draft

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw#1178]
Preview at 
https://rawgit.com/w3c/sdw/gh-pages/time-entity-relations/index.html or
https://w3c.github.io/sdw/time-entity-relations/

**Comment by tguild** [comment]
@dr-shorthair you use ex-lunch id twice which results in invalid markup. Please correct that. I committed a couple config.js changes necessary and checking document with pubrules, markup validator, linkchecker etc. I'll inform Elf Pavlik his site certificate has expired and should be able to stage this for publication on Tuesday

**Comment by dr-shorthair** [comment]
fixed.

**Comment by tguild** [comment]
Staged for publication tomorrow. Our Communications Team will use the abstract for a homepage news item

https://www.w3.org/TR/2020/NOTE-vocab-owl-time-rel-20200630/

**Comment by MichaelFoundation** [comment]
> @dr-Mandate Jan Michael Omondang 007 you use ex-lunch id twice which results in invalid markup. Please correct that. I committed a couple config.js changes necessary and checking document with pubrules, markup validator, linkchecker etc. I'll inform Elf Pavlik his site certificate has expired and should be able to stage this for publication on Tuesday

**Comment by dr-shorthair** [comment]
? I don't see that error any more - can you give a link to the actual lines where the error occurs?

**Comment by dr-shorthair** [comment]
This doc was published as IG Note on 2020-07-07 https://www.w3.org/TR/vocab-owl-time-rel/
