### ISSUE TITLE
time:isPartof in the abstract should be time:isPartOf

### ISSUE THREAD

**Issue by Toni100** [w3c/sdw#1183]
The note https://www.w3.org/TR/2020/NOTE-vocab-owl-time-agg-20200707/ mentions in its abstract `time:isPartof`. Later, the property is defined as `time:isPartOf`. Note the capital "O" in "Of".

**Comment by chris-little** [comment]
@tguild @dr-shorthair I've checked the definitions and formal documents. All state "isPartOf". The error is in the English in the Abstract "time:isPartof".
