### ISSUE TITLE
BP 9 - how to describe relative positions- needs more content

### ISSUE THREAD

**Issue by PBarnaghi** [w3c/sdw#121]
The question is whether we need this as a Best Practice or not; There don't seem to be many existing solutions/best practices for this. 

If the answer is yes we need it, then please help to add more content to this BP.

**Comment by lvdbrink** [comment]
See also this action: http://www.w3.org/2015/spatial/track/actions/128

**Comment by ghost** [comment]
This could be a gap ? This is some work.. http://www.teachspatial.org/concept-browser/spatial%20hierarchy for example but it's largely academic

**Comment by dr-shorthair** [comment]
Relative positioning is very important in many engineering applications, particularly where there is a local CRS, and  with linear referencing. Positioning along a route is a classic in logistics of course. 
This is also closely related to trajectories - mentioned by Jano today (relative position along a trajectory is parameterised by time).

**Comment by 6a6d74** [comment]
In this [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0040.html) Bill says:

<em>In my opinion, this is a useful BP to include.</em>

**Comment by lvdbrink** [comment]
See also https://lists.w3.org/Archives/Public/public-sdw-wg/2016Aug/0101.html

**Comment by rob-metalinkage** [comment]
I think we should point to the more general CRS and URI BP here - i.e. linear referencing may be done using a formally defined CRS, or done using a measure related to an identifiable feature. in the latter case,  then BP for feature identification should be used to make sure the feature identifiers is dereferenceable to provide a geometry property,  that the measure uses and identifiable Unit of Measure, and that the principles around  vocabulary reuse apply to the vocabulary used to relate the feature, the measure and its attributes (uom, precision) etc. 
Some domains may provide explicit data models for such constructs, however it will be preferable to offer a domain-neutral encoding conforming to OGC recommended practices. (here's where our general BP needs to be clear and useful!)

**Comment by lieberjosh** [comment]
There is a basic ISO 19148 compatible  linear referencing vocabulary included in sdwgeo (http://geosemweb.org/sdwgeo http://geosemweb.org/sdwgeo). It doesn’t have a “linear reference method” or “lrcs” element, but does have a reference curve, reference origin, measure, and UoM. The relevant CRS is whatever the referent(s) are in. The LinearReference alongCurve property a geometry not a feature that might have more than one geometry.

<owl:Class rdf:about="http://geosemweb.org/sdwgeo/LinearReference">
<rdfs:subClassOf rdf:resource="http://geosemweb.org/sdwgeo/SpatialModel"/>
/owl:Class

<owl:ObjectProperty rdf:about="http://geosemweb.org/sdwgeo/hasLR">
<rdfs:subPropertyOf rdf:resource="http://geosemweb.org/sdwgeo/hasSpatialModel"/>
<rdfs:domain rdf:resource="http://geosemweb.org/sdwgeo/SpatialThing"/>
<rdfs:range rdf:resource="http://geosemweb.org/sdwgeo/LinearReference"/>
/owl:ObjectProperty

<owl:ObjectProperty rdf:about="http://geosemweb.org/sdwgeo/alongCurve">
<rdfs:subPropertyOf rdf:resource="http://geosemweb.org/sdwgeo/hasReferent"/>
/owl:ObjectProperty

<owl:ObjectProperty rdf:about="http://geosemweb.org/sdwgeo/originPoint">
<rdfs:subPropertyOf rdf:resource="http://geosemweb.org/sdwgeo/hasReferent"/>
/owl:ObjectProperty

<owl:DatatypeProperty rdf:about="http://geosemweb.org/sdwgeo/measure">
<rdfs:domain rdf:resource="http://geosemweb.org/sdwgeo/LinearReference"/>
<rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#float"/>
/owl:DatatypeProperty

<owl:DatatypeProperty rdf:about="http://geosemweb.org/sdwgeo/uoM">
<rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#anyURI"/>
/owl:DatatypeProperty
—josh

**Comment by lvdbrink** [comment]
Content has now been added to [BP9][1]

See also PR #624

[1]: http://w3c.github.io/sdw/bp/#relative-position

**Comment by lvdbrink** [comment]
BP9 seems complete except for some code examples (it has examples, but they are descriptive in nature, not coded).
