### ISSUE TITLE
[Responsible Use] Shortname

### ISSUE THREAD

**Issue by tguild** [w3c/sdw#1232]
As mentioned in mail thread, we should come up with a new shortname in place of responsible-use since it is too generic.

https://lists.w3.org/Archives/Public/public-sdwig/2020Dec/0030.html

Couple suggestions:

spatial-data-use
responsible-spatial

**Comment by jabhay** [comment]
My recommendation is responsible-use-spatial

**Comment by tguild** [comment]
@edpars0ns care to weigh in? Also please see mail thread and let me know when you and @jabhay want to proceed with publishing a First Public Working Draft of this Note.

https://lists.w3.org/Archives/Public/public-sdwig/2020Dec/0034.html

**Comment by edpars0ns** [comment]
I concur with @jabhay responsible-use-spatial - re date ASAP I think ?

**Comment by tguild** [comment]
Manual publications (updates for various stages can be setup to be automatic) are on Tuesdays and Thursdays. Tomorrow is probably too short notice, I'll try to get it in for Tuesday.

**Comment by tguild** [comment]
Staging the document and debating whether to change the directory name in repo.

It will be published at:

https://www.w3.org/TR/responsible-use-spatial/

(plus a dated URI for this first version)

and currently has the following link for Editor's draft:

https://w3c.github.io/sdw/responsible-use/

which is fine but maybe better to be consistent. Let me know before Tuesday if you have a preference.

**Comment by tguild** [comment]
Set to publish on Tuesday, document staged

https://www.w3.org/TR/2021/NOTE-responsible-use-spatial-20210119/

**Comment by tguild** [comment]
Published

https://www.w3.org/TR/2021/NOTE-responsible-use-spatial-20210119/
