### ISSUE TITLE
BP10: needs some explanations

### ISSUE THREAD

**Issue by PBarnaghi** [w3c/sdw#125]
BP10: We need some explanations for the appraohes to describe positional (in)accuracy

**Comment by ghost** [comment]
There is a lot of literature on spatial data accuracy, are we looking for something practical like CEP ? https://en.wikipedia.org/wiki/Circular_error_probable

**Comment by 6a6d74** [comment]
In point (15) of his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0015.html) @Fransie says:

<em>BP 10: I would at least recommend to be aware of significant digits.</em>

**Comment by lvdbrink** [comment]
Resolved during F2F London see http://www.w3.org/2016/12/15-sdw-minutes.html
