### ISSUE TITLE
Re: SDW2022 need to continue existing activities too

### ISSUE THREAD

**Issue by ewulff1** [w3c/sdw#1272]
Yes, the bus can stop.
The First webinar on Infrastructure and data management EEA H2020 data flow (WEBINAR Infrastructure - Spatial Data Infrastructure), was by 6 September 2019. 
And I did not hear on any continuity. -

(Although the infoMAP Data Centre Global task list is currently updated. eg. https://idc.info-rac.org/mt)

**Comment by 6a6d74** [comment]
Hi thanks for the comment. I'll link to this from the original thread, and close this issue. Would like to drive conversation on this topic in a single GitHub Issue. Thanks.
