### ISSUE TITLE
[SDW Best Practices Update]: Section Ethics of Location Sharing

### ISSUE THREAD

**Issue by situx** [w3c/sdw#1284]
Adding a section (we thought it should go in the Gaps part) about ethics of location sharing: making clear there are privacy and other ethical dangers to location sharing, and referring to the responsible use doc (https://www.w3.org/TR/responsible-use-spatial/). One of the editors of that document might help

**Comment by jvanulde** [comment]
Of potential interest: https://www.w3.org/TR/geolocation/#privacy

**Comment by lvdbrink** [comment]
I got commitment from colleague and co-author of the [Responsible use of spatial data document](https://www.w3.org/TR/responsible-use-spatial/), Emily Daemen, to write this section before the end of 2022.

**Comment by EmilyDaemen** [comment]
Yes, thank you Linda - I'll write a short piece linking your work to ours. Always nice to see it being used somehow!
