### ISSUE TITLE
[SDW Best Practices Update]: Update chapter 8 with dynamic CRS

### ISSUE THREAD

**Issue by situx** [w3c/sdw#1289]
Update BP 8 with respect to dynamic CRS

**Comment by PeterParslow** [comment]
There is one sentence in https://github.com/w3c/sdw/pull/1340 that would introduce dynamic CRS in BP 7 (in clause 12.2.2), but without using the phrase 'dynamic CRS'.

**Comment by PeterParslow** [comment]
I suggest that it is BP 7 which needs to mention/discuss dynamic CRS, because it's BP 7 which is about choosing the appropriate CRS for the intended purpose, with only a small mention at BP 8.

**Comment by dr-shorthair** [comment]
Nicely worded. Clear, but compact.
