### ISSUE TITLE
[SDW Best Practices Update]: Adding MapML to the Best Practices document

### ISSUE THREAD

**Issue by situx** [w3c/sdw#1300]
We should consider MapML as either an emerging technology in an emerging technologies section or in the gaps section of the document

**Comment by prushforth** [comment]
Section requirements

* What it is, who is involved
* What is it trying to solve / scope
* What is the process for development
* What is the timeline for standardization / when will this be ready
* Why is it important
* 

Please feel free to add information you would like covered
