### ISSUE TITLE
Example 7 in Best Practice 2

### ISSUE THREAD

**Issue by PeterParslow** [w3c/sdw#1310]
The Property Search in the City of Nanaimo, Canada https://securedevel.nanaimo.ca/web/PIP/Pages/Search.aspx?templateName=property now returns "Forbidden: Access is denied"

https://www.nanaimo.ca/city-services/home-property/property-taxes/property-information-portal suggests you need to register & pay per transaction. This is not a problem in itself, but makes it less useful as an example for us to link to.

**Comment by situx** [comment]
We might consider creating a Github repository or some other data repository where examples related to the document are stored. This would at least guarantee their availability in the long run.
@lvdbrink is that something you have considered in the past?

**Comment by jvanulde** [comment]
We can keep the collateral material in the release assets. That way they are versioned and on a CDN. Just an idea.
