### ISSUE TITLE
Example 14 (in 12.2.1 Best Practice 4) - no longer available

### ISSUE THREAD

**Issue by PeterParslow** [w3c/sdw#1321]
The links in Example 14 return an HTTP 404 JSON object. It appears that the Dutch Nationaal georegister has moved, perhaps to https://www.pdok.nl/ and no longer has a WFS for "wijkenbuurten2016"

However, this may only be temporary, as the same WFS endpoint is still advertised (within a PDF) on https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/cartografische-toegang/geoservices-bij-het-cbs

Suggest: get advice from NL or switch to a different example WFS (if we're retaining WFS examples!)

**Comment by lvdbrink** [comment]
There's been an update in the dataset and the URL turns out not to be persistent. 2016 is the year the dataset was published. The new URL is: 

`https://geodata.nationaalgeoregister.nl/wijkenbuurten2020/wfs?request=GetCapabilities`

But do we still want WFS examples in the BP?

**Comment by situx** [comment]
I would prefer an OGC API Features endpoint if one is available.

**Comment by lvdbrink** [comment]
So would I, but I'm afraid in NL there are no production-level OGC API Feature endpoints yet (that I know of). My suggestion then is to change to a different example.

**Comment by tomkralidis** [comment]
We (Meteorological Service of Canada) have production OGC API (Features/Coverages/Processes/etc.) endpoints.  Happy to jump in if this helps.

**Comment by situx** [comment]
@tomkralidis that would be great. Could you suggest an example for us?

**Comment by KoalaGeo** [comment]
For Features, British Geological Survey have our 625k geology production service setup if you'd like to use this - https://ogcapi.bgs.ac.uk/collections/BGSGeology625kBedrock

We'll be adding further collections shortly + OGCAPI-Tiles

**Comment by tomkralidis** [comment]
> @tomkralidis that would be great. Could you suggest an example for us?

Sure.  I'll issue a PR in the next few days.

**Comment by tomkralidis** [comment]
PR in #1353.  Happy to add more examples if desired.
