### ISSUE TITLE
Gaps section: Publishing dynamic and large datasets on the Web

### ISSUE THREAD

**Issue by situx** [w3c/sdw#1356]
Does this section need to be updated?
Have there been recent developments?
Do we have use cases/showcases that published dynamic and large datasets on the Web?

**Comment by tomkralidis** [comment]
We (MSC) have examples of both, and could provide an example of our observations archive setup via OGC API - Features, for example.

**Comment by cportele** [comment]
I think the developments with "cloud native" data formats like COG, Zarr, COPC, etc. over the last years clearly show progress with publishing large datasets on the Web. 

Same for Web APIs with specific filter capabilities to fetch only a small(ish) subset of the data that is needed by an application in some context - with relatively simple queries (e.g., OGC API EDR or OGC API Features).

**Comment by PeterParslow** [comment]
Have I worded the descriptions OK? (@cportele ) The older one is still more wordy.

Should we add examples, as offered by @tomkralidis ?
