### ISSUE TITLE
Links to reference implementations of Best Practices components

### ISSUE THREAD

**Issue by situx** [w3c/sdw#1361]
This issue is to collect links to reference implementations that follow the spatial data best practices.
Please edit this comment or add other comments here before we decide where to merge them into the document.

**Comment by lvdbrink** [comment]
https://geoe3platform.eu/geoe3/ should have examples / reference implementation for us to use. I haven't looked closely yet, but they have a lot of geospatial data from different European countries published as OGC APIs, items published as HTML/JSON/GeoJSON/RDF. 

See also https://geoe3.eu/geoe3-publishes-the-first-data-integration-platform-connecting-national-regional-and-cross-border-digital-services/ for description.

**Comment by tomkralidis** [comment]
Additional examples for consideration (from https://github.com/geopython/pygeoapi/wiki/LiveDeployments):

|Name                                  | URL                                                                                                    
|--------------------------------------|--------------------------------------------------------------------------------------------------------
|Meteorological Service of Canada Geospatial Web Services|https://api.weather.gc.ca|
|GLOSIS - Global Soil Information|https://glosis.isric.org/ogc
|Internet of Water|https://geoconnex.us
|eMOTIONAL Cities|https://emotionalcities-h2020.eu
|US Geoplatform.gov|https://geoapi.geoplatform.gov
|British Geological Survey|https://ogcapi.bgs.ac.uk
|WMO WIS 2.0 in a box|https://docs.wis2box.wis.wmo.int
|River Runner|https://merit.internetofwater.app

**Comment by situx** [comment]
Closing this issue, as we decided not to link to reference implementations but rather only link to data products
