### ISSUE TITLE
Chapter 12.1.1 Possible approach to implementation - broken link

### ISSUE THREAD

**Issue by Iza82** [w3c/sdw#1369]
There is a broken link within chapter 12.1.1 Possible approach to implementation section just before the NOTE. An URI for Anne Franks's House comes up with 404 error message https://monumentenregister.cultureelerfgoed.nl/monuments?MonumentId=4296

**Comment by lvdbrink** [comment]
Use this one: https://monumentenregister.cultureelerfgoed.nl/monumenten/4296

I will make a PR.
