### ISSUE TITLE
Consider a section on Web accessibility - a11y

### ISSUE THREAD

**Issue by prushforth** [w3c/sdw#1392]
I apologize for this late issue, but it occurs to me that given that this is a paper about the Web, that we should consider information accessibility for persons with disabilities.  Happy for discussion below.  Thank you.

**Comment by PeterParslow** [comment]
@prushforth Have you had a look at the new section "Accessibility for Humans and Machines"? 

https://w3c.github.io/sdw/bp/#a-accessibility-for-humans-and-machines in the Editors' draft

**Comment by prushforth** [comment]
> Have you had a look at the new section "Accessibility for Humans and Machines"?

Yes, but it occurred to me that a document that aims for best practices should actually tackle what the best practices of Web cartography may be  rather than a simple take on a poor acronym that's used as a fig leaf by some standards organizations and national mapping agencies. 

If I recall correctly, "visualization" of spatial data was originally designated as out of scope for the first version of this paper. Maybe that is still the case. If so that's unfortunate. Web a11y experts have shown a lot of willingness to help our community bridge this gap; we should engage.

I wrote a possibly relevant [post](https://www.w3.org/community/maps4html/2022/09/28/why-spatial-is-very-special/) that touches on the subject.

**Comment by PeterParslow** [comment]
"a simple take on a poor acronym" - I'm not sure whether this is about FAIR, WCAG, or something else. And whether "simple take" is intended as a critique of what we've put in this new draft.

**Comment by prushforth** [comment]
>  I'm not sure whether this is about FAIR, WCAG, or something else.

I couldn't find "WCAG" in the document, but that is indeed what I believe the document should address.

**Comment by PeterParslow** [comment]
Could you make a specific suggestion for adding a reference to WCAG perhaps alongside the link to [WAI](https://www.w3.org/WAI/) and/or [Web Accessibility Initiative standards](https://www.w3.org/WAI/standards-guidelines/)?

**Comment by prushforth** [comment]
I was thinking that a section in [Chapter 12](https://w3c.github.io/sdw/bp/#bestPractices) would be appropriate.  It could be structured similar to the other best practices, and would contain information similar to that suggested by the [State of Minnesota](https://mn.gov/mnit/about-mnit/accessibility/maps/web.jsp), for example.  Inclusion of a top-level best practice like that might stimulate more conversation about accessibility practices for Web maps.

**Comment by PeterParslow** [comment]
Just a note, WCAG2.0 is also an ISO/IEC standard: https://www.iso.org/standard/58625.html

**Comment by situx** [comment]
@prushforth Would you like to contribute this section in chapter 12? You are very welcome to issue us a pull request.

**Comment by prushforth** [comment]
@situx That is great news! Yes we would like to contribute a section on a11y. I will come up with an outline and post it here for discussion before submitting a PR. Thanks!

**Comment by situx** [comment]
@prushforth Very good! Looking forward to it

**Comment by situx** [comment]
@prushforth How is your section going? Any progress so far?

**Comment by prushforth** [comment]
@situx I have had discussions with a Web map a11y expert on contributing this section. I think we are in agreement, and I'm looking to help facilitate this contribution in the coming weeks/months.  What timeline are we talking about? I'll provide further update as soon as possible.

**Comment by prushforth** [comment]
Unfortunately, I'm not in a position to contribute this section at this time.  My apologies for the false start.
