### ISSUE TITLE
Time Ontology - Missing "hasMember" object property definition for modeling proper intervals of hierarchical TRS

### ISSUE THREAD

**Issue by mdesalvo** [w3c/sdw#1407]
Hi,
I'm developing a C# library for giving applications the ability to model ontologies containing temporal entities, so Time Ontology is the conceptual reference I'm following. I noticed, in the geologic time scale example, the usage of a property "**:hasMember**" which is supposed to be an object property from the legacy version of Time ontology (http://www.w3.org/2006/time#) but I cannot find it in the Turtle file.

So my doubt is: how can we specify the proper intervals describing a hierarchical TRS? This property may be missing from the actual draft.

Thanks,
Marco

**Comment by dr-shorthair** [comment]
@mdesalvo `:hasMember` does not appear in https://www.w3.org/TR/owl-time/#geologictimescale 
Where did you find it? 

Note that the Geologic Timescale ontology extends OWL-Time. 
It was documented here: https://link.springer.com/article/10.1007/s12145-014-0170-6 and maintained here https://github.com/CGI-IUGS/timescale-ont 
There is a property `thors:member` which is used to build temporal hierarchical ordinal reference systems. 
Perhaps this is what you were looking for. 

@nicholascar you may have more information from your work with IUGS.

**Comment by mdesalvo** [comment]
Hi,
the Turtle file of the Geologic Timescale example is [here](https://raw.githubusercontent.com/w3c/sdw/gh-pages/time/rdf/geologicTimeScale.ttl).

These are the triples describing the TRS, having the unknown property:
```
geol:TimeScale
  rdf:type :TRS ;
  rdfs:label "Geologic timescale" ;
  :hasMember geol:Archean ;
  :hasMember geol:Hadean ;
  :hasMember geol:Phanerozoic ;
  :hasMember geol:Proterozoic ;
.
```

Regards,
Marco

**Comment by dr-shorthair** [comment]
Thanks. 

The example is wrong. I will look into fixing it.
