### ISSUE TITLE
TIME: OWL syntax correction on cardinality

### ISSUE THREAD

**Issue by ajnelson-nist** [w3c/sdw#1440]
Hello,

I ran across a syntax issue on OWL-Time, present in the 2006 state (assuming that is what is served from the namespace IRI) and today's state in this repository.  From other issues, particularly [this comment](https://github.com/w3c/sdw/issues/1435#issuecomment-1744205254) on 1435, it appears what I'm linking below is a prerelease state, which might not be under consideration for revision currently.

This line shows a cardinality of 0, datatyped as `xsd:integer`.

https://github.com/w3c/sdw/blob/c3202f919a50ec550a66b34a3a90c81eddb3dc10/time/rdf/time.ttl#L589

OWL 2 DL requires cardinality be datatyped as `xsd:nonNegativeInteger`, as done here:

https://github.com/w3c/sdw/blob/c3202f919a50ec550a66b34a3a90c81eddb3dc10/time/rdf/time.ttl#L101

This syntax requirement can be verified by reviewing the [OWL 2 mapping to RDF document](https://www.w3.org/TR/2012/REC-owl2-mapping-to-rdf-20121211/), reviewing all 48 occurrences of the string "ardinality" [sic.].

It seems this only occurred on the `owl:Restriction`s attached to the (currently deprecated) class `time:Year`.

**Comment by chris-little** [comment]
@ajnelson-nist To me, it looks like a typo caused by copy&paste, but I ask @dr-shorthair for confirmation, and guidance on how to correct it.
