### ISSUE TITLE
need to provide summary in 'approach to implementation' plus drill-down for more detailed info

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#147]
need to provide summary of the approach to implementation and enable readers to drill-down to more detailed documentation within each of the best practices- else this document will become (very) unwieldy

... in particular, this thought is inspired by [Best Practice 19 Make your entity-level links visible on the web](http://w3c.github.io/sdw/bp/#entity-level-links) which already (prior to FPWD) has a lot of content.

**Comment by 6a6d74** [comment]
See https://api.open.fec.gov/developers/ as an example.

(other examples of good documentation style can be found [here](https://www.w3.org/2015/spatial/wiki/BP_Structure_Examples))

**Comment by lvdbrink** [comment]
We have the approach clear for now, have decided to use the narrative.
