### ISSUE TITLE
How to link to a resource as it was at a particular time?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#168]
[Best Practice 21: Link to spatial Things](http://w3c.github.io/sdw/bp/#link-to-spatialthings) includes an example where we link to a resource as it was at a particular time. What is the best way to do this? Point to particular version of the target resource or provide date-time context with the assertion?

Is there any evidence that can be used to support either approach?

Also see [Best Practice 4: Provide stable identifiers for Things (resources) that change over time](http://w3c.github.io/sdw/bp/#ids-for-changing-things) and [Best Practice 11: How to describe properties that change over time](http://w3c.github.io/sdw/bp/#desc-changing-properties).

**Comment by lvdbrink** [comment]
That example is no longer present in the document.
