### ISSUE TITLE
Example required for search engine indexing of dataset / data-stream

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#179]
Relating to [Best Practice 25: Make your entity-level data indexable by search engines](http://w3c.github.io/sdw/bp/#indexable-by-search-engines), are there any examples of a search engine indexing data that is provided as a record in a dataset or data-stream? Especially where that data is not exposed as an HTML page?

How do search engine Web crawlers work with that kind of data?

**Comment by lvdbrink** [comment]
This was addressed in the update by Clemens Portele.
Update #509
