### ISSUE TITLE
Example required for search engine directly indexing structured spatial data

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#180]
Relating to [Best Practice 25: Make your entity-level data indexable by search engines](http://w3c.github.io/sdw/bp/#indexable-by-search-engines), are there any examples of a search engine indexing structured spatial data such as KML or GeoJSON? Both of these formats seem to have good support from Google; but do these formats get crawled and indexed?

Also see #179.

**Comment by lvdbrink** [comment]
BP4 now mentiones that KML is crawled at time of writing, (Geo)JSON is currently not crawled. No example given of crawled spatial data specifically. But the Nanaimo data is an example. If you search for "2100 AARON WAY, NANAIMO, BC" for example, the landing page is high in search rankings. We could add this to the BP.

**Comment by lvdbrink** [comment]
Correcting myself: Nanaimo is not example of crawled *structured* spatial data. But nevertheless nice to add this to the BP as an example of the possible approach working in practice. 

An example of crawled *structured* spatial data is not necessary as this BP focusses more on publishing HTML in a certain way for crawlability.
