### ISSUE TITLE
Should BP "Include search capability in your data access API" move to "Enabling discovery" section?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#186]
Section [6.5 Exposing datasets through APIs](http://w3c.github.io/sdw/bp/#bp-exposing-via-api) includes [Best Practice 30: Include search capability in your data access API](http://w3c.github.io/sdw/bp/#include-search-api). This might be better suited in section [6.4 Enabling discovery](http://w3c.github.io/sdw/bp/#bp-discovery).

**Comment by lvdbrink** [comment]
That section no longer exists after the restructuring. We should decide if we want to retain or remove this section. It is not especially spatial, but it is also not mentioned in DWPB so we cannot simply refer to it there.

**Comment by cportele** [comment]
WG decided to remove the BP. The content is covered by the BP on spatial data access APIs. See [minutes](https://www.w3.org/2017/03/08-sdw-minutes).
