### ISSUE TITLE
Should content from "Exposing datasets through APIs" be moved to DWBP "Data Access"?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#187]
With the exception of [Best Practice 30: Include search capability in your data access API](http://w3c.github.io/sdw/bp/#include-search-api), the information in section [6.5 Exposing datasets through APIs](http://w3c.github.io/sdw/bp/#bp-exposing-via-api) seems to be largely applicable to all kinds of data published on the web - not just spatial data. Is there merit in moving the content to DWBP section [9.11 Data Access](http://w3c.github.io/dwbp/bp.html#dataAccess)?

Somewhere we need to talk about making OGC WxS services more "web friendly" and compatible with linked data approaches ... [this](http://w3c.github.io/sdw/bp/#bp-exposing-via-api) section seems like the most appropriate place. Alternatively, we could provide this kind of information in an Appendix or even a separate Note?

**Comment by 6a6d74** [comment]
In his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0047.html) Clemens says:

<em>What is the spatial aspect of [BPs 28, 29 & 30]? These are more general Data on the Web recommendations. I see that we may want to discuss examples in the spatial context, but maybe we should shorten the general discussion and simply reference the related Data on the Web best practices and focus in our document on the spatial aspects?</em>

**Comment by lvdbrink** [comment]
Section on [Spatial Data Access][1] has been substantially rewritten to address this.

[1]: http://w3c.github.io/sdw/bp/#bp-exposing-via-api
