### ISSUE TITLE
Are "content publishers" sufficiently different from the other defined audience categories?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#190]
Kerry Taylor noted in her [email](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0004.html) that she "can't distinguish this group from [geospatial experts] nor [web developers]".

Do we need a [content publishers category](http://w3c.github.io/sdw/bp/#audience-content-publishers) in section [2. Audience](http://w3c.github.io/sdw/bp/#audience)?

**Comment by ghost** [comment]
I prefer the term Spatial Data Custodian, someone who has spatial data to share / publish and who may or may not have expertise. They are different from developers or consumers of content.

**Comment by 6a6d74** [comment]
See also my [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0027.html) which says:

<em>I get your point, but our emphasis is on those people who commonly use SDIs in their routine work. I don't think we even thought of non-experts providing VGI.

Am looking for others in the WG to endorse this before making a change. Please respond with +1 (or 0 or -1) to vote; comments are optional.</em>

**Comment by 6a6d74** [comment]
Rachael Heaven wrote in point (RH25) of her [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0022.html)

<em>perhaps we rename to Spatial Data Custodian and text is "These are people who are responsible for acquiring, managing and publishing spatial data. They want to know how to publish their spatial data so that it can be used to its full potential, by using the skills of the geospatial experts and web developers.</em>

**Comment by lvdbrink** [comment]
I think the scope section is much clearer since this issue was first raised.
