### ISSUE TITLE
The term "entity-level resources" is confusing

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#191]
By "entity-level resources" the BP editors are talking about the descriptions (information objects) of the SpatialThings (the entities) in a dataset ... the discrete components that comprise the dataset.

In her [email](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0004.html), Kerry Taylor wonders if the term "entities" is sufficient. I'm not sure that this covers the intended scope. Should we be saying "SpatialThing"?

**Comment by 6a6d74** [comment]
@edparsons indicated in his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0013.html):

<em>I think a narrative around the ability to link to a entity/spatialthing is useful here, as a municipal engineer can I send a ink to a individual street light in an email to a contractor ?  Identification of resources is the "means to the end not the end itself" - sorry about the use of this idiom</em>

**Comment by edparsons** [comment]
Hi Jeremy, I think you may have the wrong Ed Parsons. I'm a British engineer in San Francisco, I think you are looking for the other Ed Parsons who works for Google in London. Say hi from me.

**Comment by 6a6d74** [comment]
You're absolutely correct. My mistake ... Apologies. Imagine there being
two of you! I've found the GitHub name for the other Ed so I should be able
to avoid the mistake again.

I'll pass on your regards :-)

Best regards. Jeremy

**Comment by lvdbrink** [comment]
Solved; now using the term spatial thing here.
