### ISSUE TITLE
Is the term "subset" correct?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#195]
Regarding [Best Practice 5: Provide identifiers for parts of larger information resources](http://w3c.github.io/sdw/bp/#ids-for-chunks) Kerry notes in her [email](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0007.html):

<em>I don't like "subset" being used for this purpose -- despite its popularity in spatial arenas,  for its lack of clarity being a misused mathematical term. Database language of "select" and "project" are preferable, but  still too narrow. What  do you think of "view"?</em>

**Comment by ghost** [comment]
I think the email thread here https://lists.w3.org/Archives/Public/public-sdw-comments/2015Dec/0000.html is interesting, I think there should be a distinction between a spatial thing that is component part of a larger thing (Essex as part of England"), and the results of some form of operation on a dataset query/view whatever... (Counties with higher than average consumption of fake tan)

**Comment by cportele** [comment]
Since the Data on the Web Best Practices uses the term "subset", I think we should use the term, too, with the same meaning that is used there.

https://www.w3.org/TR/dwbp/#ProvideSubsets

**Comment by lvdbrink** [comment]
time expired
