### ISSUE TITLE
Need to clarify when and why people use different CRS's

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#204]
@edparsons said in his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0013.html):

<em>I think we have to be very careful with this section, we are rather loose with language. [This](https://www.mapthematics.com/forums/viewtopic.php?f=8&t=251) is quite a good starting point as to why people use different CRS.</em>

**Comment by 6a6d74** [comment]
@edparsons ... can you provide some copy for inclusion in [Best Practice 8: Specify Coordinate Reference System for high-precision applications](http://w3c.github.io/sdw/bp/#ref-crs)?

**Comment by 6a6d74** [comment]
@philarcher1 ... I can't seem to assign @edparsons this ISSUE; is he set up as a member of the w3c/sdw repo?

**Comment by 6a6d74** [comment]
@philarcher1 ... Ed is @edpars0ns; I still can't assign the issue to him tho.

**Comment by 6a6d74** [comment]
In his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0070.html) Chris suggested some text:

<em>Even if a CRS, tied to a tectonic plate, is used, local coordinates in some areas may still change over time, if the plate is rotating with respect to the rest of the earth. Many existing useful maps pre-date GPS and WGS84 based mapping, so that location errors of tens of metres, or more, may exist when compared to the same location derived from a different technology, and these errors may vary in size across the extent of a single map.</em>

**Comment by lvdbrink** [comment]
CRS BP has been revised bearing in mind the comments above. After review new issue may be opened if it is still not carefully worded enough. We need to strike a balance between being carefully worded and being concise and understandable.
