### ISSUE TITLE
Definition of "spatial data" is required

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#206]
In point (6) of his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0015.html) @Fransie says:

<em>I think an explanation of the term 'spatial data' should be somewhere very high up in the document (abstract and/or introduction), especially that spatial != geographic (geographical data is a subset of spatial data)</em>

**Comment by 6a6d74** [comment]
In point (1) of his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0018.html) @andrea-perego says:

<em>we should clarify what we mean with "spatial data", and that "geospatial" / "geographic(al)" data are just a subclass of them.</em>

In point (2) he also says:

<em>In relation to point (1), the term "geospatial" is frequently used just after having talked about "spatial data" (e.g., when talking about "geospatial experts"). If not clarified, a reader is very likely to (wrongly) infer that "spatial" = "geospatial".</em>

**Comment by PeterParslow** [comment]
The set of words & their use are a mess (in my opinion), so good luck finding any agreed meanings that distinguish between them - even just for the context of this group.

For example, ISO 19107 defines 'spatial objects', which it would be reasonable to assume must be present in data for it to be 'spatial data'. But an ISO 19107 spatial object is "an object used for representing a spatial characteristic of a feature" (e.g. a point, a polygon, a solid), whereas the same phrase is used in the European INSPIRE Directive as a synonym for ISO 19107's feature instance i.e. the whole digital representation of the feature.

Similarly, ISO 19101 defines 'geographic information' as 'information concerning phenomena implicitly or explicitly associated with a location relative to the Earth' and avoids using 'geospatial'. Perhaps 10 years ago, that appeared to be more a UK/US difference than a difference in meaning, but I accept that 'geospatial' does now have a broader meaning (covering both medical scanning & astronomy). 

When this group chose to be called 'spatial data on the web', what was the intended scope? The charter seems to equate it with geospatial information, but elsewhere uses the term 'location'.

May I suggest you leave it ambiguous, except where absolutely necessary. Or even introduce a couple of sentences explaining the overlapping uses?

**Comment by 6a6d74** [comment]
In re-writing the introductory material, I have now written the following:

> Location, or geospatial data, is often a common thread running through such data; describing how things are positioned relative to the Earth in terms of coordinates and/or topology.
> Within this document our focus is the somewhat broader concern of spatial data; data that describes anything with spatial extent (i.e. size, shape or position) whether or not it is positioned relative to the Earth.

I have also added the following terms to the Glossary:
- Geographic information (also geospatial data):: Information concerning phenomena implicitly or explicitly associated with a location relative to the Earth [ISO19101].
- Spatial data:: Data describing anything with spatial extent; i.e. size, shape or position. In addition to describing things that are positioned relative to the Earth (also see geospatial data), spatial data may also describe things using other coordinate systems that are not related to position on the Earth, such as the size, shape and positions of cellular and sub-cellular features described using the 2D or 3D cartesian coordinate system of a specific tissue sample.

Hopefully this clarifies the difference between spatial and geospatial.

@PeterParslow, @andrea-perego and @Fransie ... what do you think? Can we close this issue?

**Comment by andrea-perego** [comment]
+1 from me.

**Comment by 6a6d74** [comment]
@andrea-perego ... thank you.

**Comment by dr-shorthair** [comment]
Jeremy –

Could we add this Issue before the Glossary

```
  <div class="issue" data-number="223">
    <p>Consider adopting definitions from <a href="http://www.isotc211.org/Terminology.htm">ISO/TC 211 Glossary</a>
      - see <a href="http://registry.it.csiro.au/sandbox/iso-tc211/terms">linked data prototype&nbsp;</a> .</p>
  </div>
```

(I’ve tried to make this a pull request but getting tangled up in GitHub.)

Simon

**Comment by 6a6d74** [comment]
@dr-shorthair ... is ISSUE #223 the correct one; this talks about the role of SDIs. Did you just choose 223 as the next sequential number :-)

**Comment by 6a6d74** [comment]
@dr-shorthair ... I've added it as a placeholder pending the identification of the appropriate issue number.

**Comment by dr-shorthair** [comment]
No - #223 is not correct – I was hacking the HTML without fully understanding.
I now see it is #212https://github.com/w3c/sdw/issues/212

We have too many issue lists! – I’ve been looking at http://w3c.github.io/sdw/UseCases/SDWUseCasesAndRequirements.html and https://www.w3.org/2015/spatial/track/issues/open but overlooked https://github.com/w3c/sdw/issues
Not sure that all of https://www.w3.org/2015/spatial/track/issues/open are reflected in github ☹

Simon

**Comment by 6a6d74** [comment]
@dr-shorthair 

> We have too many issue lists!

You might be right. For BP deliverable, we're using GitHub because (I think) it's easier to tie in COMMITs and PRs to the ISSUEs. It does make things a little confusing.

> Not sure that all of https://www.w3.org/2015/spatial/track/issues/open are reflected in github ☹

They're not. Perhaps we (I?) have made a mess ... 

Anyhow, I see that your point about the ISO/TC 211 Glossary and the CSIRO Sandbox Registry is already made at: https://github.com/w3c/sdw/issues/212#issuecomment-208697482

**Comment by lvdbrink** [comment]
Needs review to decide if we define spatial data in a satisfying way now. Responses to this issue suggest a Yes. 

Probably we still need to check the use of spatial vs geospatial throughout the document.
