### ISSUE TITLE
Details of "Audience" section overlaps with "Introduction"; redraft to avoid duplication

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#207]
In point (7) of this [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0015.html) @Fransie says:

<em>Section 2: There seems to be overlap with description of user groups in the introduction (1.1). This leads (or could lead) to duplicate information. Why not just mention in the introduction that there are multiple audiences and that they are described in section 2?</em>

**Comment by 6a6d74** [comment]
@Fransie also says:

<em>Section 2: I wonder if the three groups that are described cover all audience types. Some more I can think of are

<ul>
<li>People working with spatial data that is not geographical (e.g. SVG, CAD, BIM).</li>
<li>People involved in development of standards that have something to do with spatial data on the web .</li>
<li>People involved in development of software that can work with spatial data.</li>
</ul>

</em>

This is useful input to a future redraft of section 2.

**Comment by lvdbrink** [comment]
The user groups in 1.1 are there to introduce the problem space and don't seem to fully overlap with the intended audience. However, we might rethink this and merge the text around these user groups from 1.1 into section 2. More discussion needed.

**Comment by 6a6d74** [comment]
Rachael Heaven stated in point (RH23) of her [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0022.html):

<em>[Geospatial experts] are described according to their role as a publisher of data, whereas in the introduction their role is “find and use data”. Can these two sections be made consistent, or perhaps have a matrix of expertise group (geospatial OR web) crossed with their role (publisher OR consumer OR ?custodian). Relates to ISSUE #190.</em>

**Comment by lvdbrink** [comment]
Was redrafted.
