### ISSUE TITLE
Add content to general introduction

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#21]
[General introduction](http://w3c.github.io/sdw/bp/#general-introduction) needs content.

Content sources:
- [Charter](http://www.w3.org/2015/spatial/charter) 
- [Geonovum tender doc](http://www.geonovum.nl/sites/default/files/Invitationtotender-SDWtestbed_0.pdf)

**Comment by lvdbrink** [comment]
Provided content. Now needs review!

**Comment by lvdbrink** [comment]
Was reviewed, text updated based on [review remarks from mailing list](https://lists.w3.org/Archives/Public/public-sdw-wg/2015Nov/0029.html.).
