### ISSUE TITLE
Glossary section needs improving; see existing sources of definitions

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#212]
Thanks to @dr-shorthair for pointing our these existing sources of definitions:

https://www.w3.org/2015/spatial/wiki/Glossary_of_terms

http://www.isotc211.org/Terminology.htm (>900 terms)

He says:

<em>Just a reminder that we have a Wiki page focussed on a glossary of terms (thanks Kerry). I’ve just updated the link to the ISO/TC 211 glossary spreadsheet, which is very well maintained resource (thanks Andrew Jones), even if it is bit heavy going in places. Note that the ISO glossary is assembled from definitions found in the various ISO 191*\* standards, so it is not necessarily fully self-consistent conceptually, but does at least have an auditable link back to someone’s hard thinking in each case.</em>

**Comment by 6a6d74** [comment]
Also- in his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0049.html) LarsG says:

<em> To me as a non-geospatial expert, the definition of [coverage](http://w3c.github.io/sdw/bp/#dfn-coverage) is not very helpful </em>

Based on his recent efforts during revision of ISO 19109, @dr-shorthair (aka Simon Cox) includes this description (albeit much longer than the other glossary definitions:

<em>7.2.2 Coverages

Many aspects of the real-world may be represented as features whose properties are single-valued and static. These conventional features provide a model of the world in terms of discrete objects located in it. However, in some applications it is more useful to use a model focussing on the variation of property
values in space and time, formalized as coverages. Users of geographic information may utilize both viewpoints. While coverages are themselves strictly features as well, it is common to contrast coverages and non-coverage features when discussing the functionality provided by each viewpoint. In the following discussion the name ‘feature’ refers to non-coverage features.

﻿The feature and coverage representations may be related in several ways:
— signal processing to find and characterize features: signals in coverages may provide evidence for the existence, location and type of features, detected through modelling and interpretation;

EXAMPLE 1 Patterns of colour or other radiance bands within a remotely-sensed image may be used to infer the existence of specific objects or features on the ground.
EXAMPLE 2 Signals in a geophysical borehole log may be used to infer the presence of particular rock-units at underground locations.

— coverage-typed feature properties: feature properties whose value vary within the scope of a feature may be described as coverages whose domain extent is the geometry of the feature;

EXAMPLE 3 The variation of concentration of a particular ore-mineral within a mine may be described as a spatial function or coverage within the spatial limits of the mine.

— features sample a coverage: the values of a common property of a set of features provide a discrete sampling of a coverage, whose range type is the property, and whose domain is the aggregate geometry of the set of features.

EXAMPLE 4 The temperature at a set of weather stations may be compiled to show the spatial variation of temperature across the region where the stations are located.

A constraint in the latter two cases is that a property-type from a feature catalogue is the range-type of a coverage description in the same universe of discourse.

The case of features having property values that vary within the scope of the feature can be described using the general feature model (7.5.8).

While the coverage model is described in detail in ISO 19123, an application schema may include both feature- and coverage-types.

NOTE The feature and coverage viewpoints are related to (though not identical with) the so-called ‘vector’ and ‘raster’ approaches from traditional GIS implementations.</em>

**Comment by 6a6d74** [comment]
In point (RH30) of her [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0023.html) Rachel says:

<em> Scope. (and several other places)
“thematic” – add to glossary </em>

Need to add a definition for "thematic" (e.g. see [Scope](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0023.html) and 11 other places).

**Comment by 6a6d74** [comment]
Do we need a definition for "Mutually Exclusive Collectively Exhaustive" (MECE) ... see [wikipedia](https://en.wikipedia.org/wiki/MECE_principle) for starters. See point (RH44) of Rachel's [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0023.html).

**Comment by 6a6d74** [comment]
In point (RH78) of her [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0025.html) Rachel says:

<em>Few items to be added as already mentioned in previous comments. Perhaps GIS and SDI definitions could be updated to indicate the relation between them (e.g. GIS is usually a component part of an SDI)</em>

**Comment by dret** [comment]
it would be good to have "vocabulary" defined. it may mean "RDF vocabulary", or "some structured data model, not limited to a specific metamodel". that makes a big difference because the term is used a lot.

**Comment by dr-shorthair** [comment]
1. The ISO/TC 211 terminology list is available as linked data here: http://registry.it.csiro.au/sandbox/iso-tc211/terms 
   These URI's are temporary, while I work with the maintainer on ironing out bugs. 
2. @dret the discussion here concerns a 'glossary' or 'terminology list'. However, looks like you could be being 'meta' here, and asking for a definition of the term 'vocabulary' to be included in the glossary - is that correct?

**Comment by dret** [comment]
> ```
> @dret <https://github.com/dret> the discussion here concerns a
> 'glossary' or 'terminology list'. However, looks like you could be
> being 'meta' here, and asking for a definition of the term
> 'vocabulary' to be included in the glossary - is that correct?
> ```

that's correct. my apologies if that was a bit confusing, i was assuming 
this was a issue concerned with how to improve the glossary. i think 
that adding "vocabulary" as a glossary term would be one such improvement.

**Comment by lvdbrink** [comment]
The glossary still needs work. In the comments in this issue several terms were suggested but not yet added, including: 
- 'thematic'
- 'Mutually Exclusive Collectively Exhaustive (MECE)'
- 'vocabulary'

Also, GIS and SDI definitions could be updated to indicate the relation between them (e.g. GIS is usually a component part of an SDI). 

The term 'dimension' was added recently. See [comments][1]

Several parts in the glossary are marked in yellow and need review. 

See also [this older discussion][2] on the glossary (and reusing the ISO Terminology). 

[1]: https://lists.w3.org/Archives/Public/public-sdw-wg/2017Jan/0127.html
[2]: https://lists.w3.org/Archives/Public/public-sdw-wg/2016Mar/0061.html

**Comment by 6a6d74** [comment]
@PeterParslow - this relates to the Glossary section review / update
