### ISSUE TITLE
Methodology for selecting a spatial vocabulary is not yet defined.

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#214]
In point (RH58) of her [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0025.html), Rachel says:

<em>"[ [Best Practice 12: Use spatial semantics for Spatial Things](http://w3c.github.io/sdw/bp/#semantic-thing) ] helps you decide which vocabulary to use" - I don't think it helps you to decide as it stands, it just tells you to decide.
The list of mappings as suggested in ISSUE #38 would be very useful.</em>

**Comment by dret** [comment]
does "vocabulary" imply RDF here? if so, i'd be opposed to phrase it like this. the vast majority of valuable semantic models of spatial things out there are non-RDF models. implying that _only_ RDF vocabularies can be a valid choice would by definition make all those choices violate this BP.

**Comment by lvdbrink** [comment]
(After the reordering of BPs this is currently BP10.)
Content that helps users decide on a vocabulary has not yet been added. In the introduction of the [12.5 Spatial Data Vocabularies](http://w3c.github.io/sdw/bp/#h-bp-expressing-spatial) section, there is now a bit of text suggesting that semantics may already be described in some form for standardized formats such as GeoJSON, schema.org. We want to make clear that RDF is not the only way to provide clear semantics but the text may need further improvement.

**Comment by dret** [comment]
On 2016-09-27 15:23, Linda van den Brink wrote:

> (After the reordering of BPs this is currently BP10.)
> Content that helps users decide on a vocabulary has not yet been added.
> In the introduction of the 12.5 Spatial Data Vocabularies
> http://w3c.github.io/sdw/bp/#h-bp-expressing-spatial section, there is
> now a bit of text suggesting that semantics may already be described in
> some form for standardized formats such as GeoJSON, schema.org. We want
> to make clear that RDF is not the only way to provide clear semantics
> but the text may need further improvement.

that sounds like an excellent goal. any text that would communicate some 
form of metamodel supremacism would not be very helpful or webby.

**Comment by lvdbrink** [comment]
Work was done on [BP10][1]  this sprint, to be reviewed. 

However, the bit quoted above may have inadvertently been dropped. To be checked. 
 
[1]: http://w3c.github.io/sdw/bp/#semantic-thing

**Comment by lvdbrink** [comment]
The text about semantics already being present in some formats is still there, 3rd paragraph of [Spatial data vocabularies][1]. 

Content that helps users decide on a specific vocabulary has not yet been added. 

[1]: http://w3c.github.io/sdw/bp/#bp-expressing-spatial

**Comment by lvdbrink** [comment]
Try to refer back to DWBP instead of repeating.

**Comment by andrea-perego** [comment]
>
> Try to refer back to DWBP instead of repeating.
>

Just to note that the table in Appendix A about spatial data vocabularies
<http://w3c.github.io/sdw/bp/#table-vocabs-matrix>, could be used as a
guidance - at least to know what you can and what you can't do with them:
