### ISSUE TITLE
Is the description of sensor data processing workflows in scope?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#216]
In point (RH64) of her [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0025.html), Rachel says:

<em>Is [ [Best Practice 15: Describe sensor data processing workflows](http://w3c.github.io/sdw/bp/#describe-process) ] only about processing of the spatial aspects of sensor data ? Perhaps that needs to be made clearer in the title and the content, and to state that processing information about any of the non-spatial aspects is out of scope.</em>

**Comment by lvdbrink** [comment]
It was decided that this is out of scope for the best practice.  It is considered too specific for the Best Practice work - the details of working with sensor data processing workflows should be covered in the ssn work. See [Minutes](https://www.w3.org/2016/08/24-sdwbp-minutes#item02).
