### ISSUE TITLE
BP17 "How to work with crowd-sourced observations" needs more content 

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#220]
Currently it's not clear how 'crowd-sourced' data is different from other data.

In this [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0040.html) Bill says:

<em>How does crowd-sourced data differ from other data? (I'm not saying it doesn't! - just a genuine question on what considerations are specific to data generated in this way, which might inform how it can best be dealt with)</em>

The intent of this BP is recognising that we get a lot of spatial data from _social media_ channels, where one can't typically use structured data. How can these 'reports' (posts, tweets, whatever...) be integrated with other spatial data?

In addition, we need to define what we mean by "contextual information that describes the quality, completeness and trust levels of crowd-sourced observations".

**Comment by 6a6d74** [comment]
In point (RH21) of her [email to the WG](http://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0022.html) Rachel says:

<em>it seems important to engage developers of social media tools with these best practices, to enable citizen authored information to be properly “spatialised” at source</em>

She [later](http://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0076.html) clarifies:

<em>[BP17](http://w3c.github.io/sdw/bp/#crowd-obs) states that the best practice will not be able to be met by some social media channels because they don’t allow structured data. This could read a bit like a dead-end to widespread implementation. Are the “some” a significant portion of the social media channels? Are we hoping that they will change their rules? If so should we give the developers of those channels a special mention in the Audience section?  

Perhaps just re-wording to  “...currently do not allow...” in [BP17](http://w3c.github.io/sdw/bp/#crowd-obs) will be sufficient to sound more open to change. 

And regardless of whether we are hoping for that change, we need to include or refer to a way of handling the unstructured information (ref ISSUE #217)</em>

**Comment by lvdbrink** [comment]
Further discussion in [this telecon](https://www.w3.org/2016/08/24-sdwbp-minutes).

**Comment by lvdbrink** [comment]
We decided to remove this BP.
