### ISSUE TITLE
Need to illustrate role of SDIs in publishing spatial data on the Web

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#223]
In his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0047.html) Clemens says:

<em>Another comment related to the references to "typical SDIs" is that to me the wording in the document sometimes gives the impression, that by design SDIs do not fit what is the Web today. While that is true (to me [BP25](http://w3c.github.io/sdw/bp/#indexable-by-search-engines) is a key point here among other aspects), I think this is only part of the story. SDIs offer the capability for linking data and for expressing models and semantics, but quite often these capabilities are not used and data is often published like GIS data more or less before we had the Web. One could in principle implement many of the BPs in current SDIs, too. Or publish spatial data using RDF technologies in ways that wouldn’t be very Webby either. To me, the potential value of the BP document is in helping to establish am understanding what aspects are key with respect to putting and using spatial data _on_ the Web. Specific technologies also play a role here and we need to cover them as well, in particular in the examples, but it should be the principles that matter most. There will always be a mix in technologies that will be used, often for good reasons.</em>

**Comment by lvdbrink** [comment]
The role of SDIs is addressed in 
- [10. Why are traditional Spatial Data Infrastructures not enough?][1]
- [BP4][2]
- [BP11][3]

[1]: http://w3c.github.io/sdw/bp/#why-are-traditional-sdi-not-enough
[2]: http://w3c.github.io/sdw/bp/#indexable-by-search-engines
[3]: http://w3c.github.io/sdw/bp/#convenience-apis
