### ISSUE TITLE
Maintaining links to *all* related resources doesn't scale. Redraft required.

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#224]
In his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0047.html) Clemens says of [Best Practice 23: Link to related resources](http://w3c.github.io/sdw/bp/#link-to-related-resources):

<em>This could be read to recommend to create and maintain explicit links to all other (related) datasets in the Web? That clearly does not scale, so I think we should be more clear on what we are considering good practice.</em>

**Comment by lvdbrink** [comment]
In the current draft this is [BP14](http://w3c.github.io/sdw/bp/#entity-level-links), it was consolidated with other BPs about linking data. The issue is still relevant.

**Comment by 6a6d74** [comment]
Concern is resolved in edits of this [commit](https://github.com/w3c/sdw/commit/09986967d6ba31377f0652c923ca94f1f54a4a14).
