### ISSUE TITLE
We must avoid being overly focused on RDF

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#225]
In his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0047.html) Clemens says:

<em>The LD-BP reference makes this very RDF dependent. Is there a need / justification for this? Are we saying that RDF is the only recommended way to publish data and models on the Web? I know some will say "yes", but if we target web developers I would guess that many do not care about RDF vocabularies and maybe they prefer a Swagger document (just to pick an example)?</em>

**Comment by PeterParslow** [comment]
I'm inclined to agree. Reading the draft best practices, two sentences jar:

"The intended users of the SDI are experts in the geospatial domain." - definitely not the case with the WMS/View Service part (which is why the paper can make the comment about a 'spatial picture infrastructure' - that's the most user friendly bit..

"the Linked Data approach is most appropriate for publishing and using spatial data on the Web" - although at least here there is immediately a note implying that this is only the case for web developers. And even then, I know plenty who have no interest in Linked Data.

Like you, I am keen to move beyond pictures to meaningful information. Concentrating solely on linked data is already putting web developer colleagues off from being involved in this group.

**Comment by dret** [comment]
if there is a justification for making this very RDF dependent, then this must be made explicit. my view is that the WG is doing themselves as well as the spatial data community a disservice by (so far) turning this into a "Best Practices for Spatial RDF Data on the Web" document. #229 also raised this point a little while ago, and i am curious to see responses over there or here.

**Comment by lvdbrink** [comment]
Did a small rewrite. Maybe this is enough to reduce the RDF focus?

Added this text: 
"Depending on the format you use, the semantics may already be described in some form. For example, in GeoJSON this description is present in the [[GeoJSON]] specification. When using JSON it is possible to add semantics using a JSON-LD @context. For providing semantics to search engines, using schema.org is the way to go, as explained in BP 3: Make your data indexable by search engines.
    In a linked data setting, the attributes of a spatial thing can be described using existing vocabularies [..]."

**Comment by dret** [comment]
On 2016-08-18 01:57, Linda van den Brink wrote:

> "Depending on the format you use, the semantics may already be described
> in some form. For example, in GeoJSON this description is present in the
> [[GeoJSON]] specification. When using JSON it is possible to add
> semantics using a JSON-LD @context https://github.com/context. For
> providing semantics to search engines, using schema.org is the way to
> go, as explained in BP 3: Make your data indexable by search engines.
> In a linked data setting, the attributes of a spatial thing can be
> described using existing vocabularies [..]."

i take issue with this general assumption that "semantics" are awarded 
when using RDF. that only is the case when the RDF vocabulary used is 
either shared, or is grounded in shared vocabularies. and for either of 
these cases, the very same is true for non-RDF vocabularies. to me, 
trying to cast this document as something that favors one specific 
technology makes it unnecessarily biased, and hurts its usefulness for 
the larger web.

any document claiming to be about "data on the web" should be fiercely 
nonpartisan when it comes to technology choices beyond web architecture. 
i haven't looked at the overall document recently, but when i did a 
while ago, there were many places where the document would require 
cleanup from clear bias.

http://dret.github.io/webdata/

**Comment by dr-shorthair** [comment]
I agree with Erik here. It is true that a certain kind of semantics are made possible by use of RDF-based technology.  But whether that is actually realised depends on a few more steps than merely using an RDF-friendly serialization. We need to be careful that the claim around semantics is not premature. Maybe this tweak to Linda's formulation is a little more accurate: 

"Depending on the format you use, support for some semantics may already be available. For example, for data in GeoJSON the description of the spatial semantics is in the [GeoJSON] specification. When using JSON it is also possible to link to semantics defined in some RDF vocabulary using a JSON-LD @context. To provide semantics to search engines, using schema.org is the way to go, as explained in BP 3: Make your data indexable by search engines."

**Comment by 6a6d74** [comment]
In the newly drafted [section on Linked Data](http://w3c.github.io/sdw/bp/#linked-data), we've tried to indicate that our focus is _linked_ data not (only) RDF and that there are many technology solutions that can be applied. 

In a nut shell, I think that our recommended formats need to support Web Linking (see RFC5988), where each link contains:
1. context URI (the source or origin)
2. link relation type 
3. target URI 
4. (optionally) target attributes

Item (2) covers semantics of links; a user or software agent should be able to find the definition of a given link type. Similarly, we need to be able to define the type of the resources themselves and the semantics of properties with literal values.

That said, the majority of examples in the BP doc have a RDF flavour which is tending to distort our aspiration to avoid technology bias.

**Comment by PeterParslow** [comment]
Would an example implemented in XML/GML help? I can offer OS OpenNames. It's not necessarily the best example, because the GML isn't directly available on the web (except as a giant Zip file!), but it may be useful to illustrate how the concept of linked data needn't be RDF.

Also, I'm quite happy (on behalf of OS) if people have suggestions for improving the encoding (although it may take us some time to implement them). What we've done so far is inspired by INSPIRE.

Details at https://data.gov.uk/dataset/os-open-names. Sample snippet:

```
<names:NamedPlace gml:id="osgb4000000023473828">
      <gml:identifier codeSpace="http://inspire.jrc.ec.europa.eu/ids">http://data.ordnancesurvey.co.uk/id/4000000023473828</gml:identifier>
...
      <names:inPostcodeDistrict xlink:title="SN8" xlink:href="http://data.ordnancesurvey.co.uk/id/postcodedistrict/SN8"/>
      <names:inPopulatedPlace xlink:title="Buttermere" xlink:role="http://www.ordnancesurvey.co.uk/xml/codelists/localtype.xml#hamlet" xlink:href="http://data.ordnancesurvey.co.uk/id/4000000074567820"/>
      <names:inCounty xlink:title="Wiltshire" xlink:role="http://data.ordnancesurvey.co.uk/ontology/admingeo/UnitaryAuthority" xlink:href="http://data.ordnancesurvey.co.uk/id/7000000000043925"/>
      <names:inEuropeanRegion xlink:title="South West" xlink:href="http://data.ordnancesurvey.co.uk/id/7000000000041427"/>
      <names:inCountry xlink:title="England" xlink:href="http://data.ordnancesurvey.co.uk/id/country/england"/>
</names:NamedPlace>

```

or is that not what you meant at all, Jeremy?

**Comment by 6a6d74** [comment]
Hi @PeterParslow  ... I updated your comment to show the snippet as a code block (and stop GH interpreting it as markdown).

Yes- we need examples such as these ... 

It would be good to have examples that can be fitted into the [flooding scenario](http://w3c.github.io/sdw/bp/#narrative) that we're using in the BP document to bring some consistency.

**Comment by lvdbrink** [comment]
One other place where the focus on RDF is present is the Abstract. Rewrite needed.

**Comment by lvdbrink** [comment]
So, places to review and possibly amend are: 
- The abstract
- [9. Linked Data][2] section
- [BP7][3] because LD-BP is referenced there as well - perhaps not needed.
- [12.5 Spatial data vocabularies][4]
- [12.7 Linking spatial data][5]

[2]: http://w3c.github.io/sdw/bp/#linked-data
[3]: http://w3c.github.io/sdw/bp/#globally-unique-ids
[4]: http://w3c.github.io/sdw/bp/#bp-expressing-spatial
[5]: http://w3c.github.io/sdw/bp/#bp-linking

**Comment by dret** [comment]
On 2017-04-05 20:40, Linda van den Brink wrote:
> So, places to review and possibly amend are:
>
>   * The abstract
>   * 9. Linked Data <http://w3c.github.io/sdw/bp/#linked-data> section
>   * BP7 <http://w3c.github.io/sdw/bp/#globally-unique-ids> because LD-BP
>     is referenced there as well - perhaps not needed.
>   * 12.5 Spatial data vocabularies
>     <http://w3c.github.io/sdw/bp/#bp-expressing-spatial>
>   * 12.7 Linking spatial data <http://w3c.github.io/sdw/bp/#bp-linking>

i probably have mentioned this already: http://webdata.systems/ is an 
attempt to talk about webby data without requiring the RDF foundation. 
it might be useful as a starting point to think about what really 
matters about data on the web, and what's an RDF-specific add-on.

**Comment by lvdbrink** [comment]
Resolved to amend the abstract. We think the other sections are balanced enough and not advocating RDF as the only linked data solution.

**Comment by lvdbrink** [comment]
Abstract was rewritten. I removed: 

> “These best practices suggest a significant change of emphasis from traditional Spatial Data Infrastructures by adopting a Linked Data approach. As location is often the common factor across multiple datasets, spatial data is an especially useful addition to the Linked Data cloud; the 5 Stars of Linked Data paradigm is promoted where relevant.”

And replaced this by: 

> “These best practices suggest a significant change of emphasis from traditional Spatial Data Infrastructures by adopting an approach based on general web standards. As location is often the common factor across multiple datasets, spatial data is an especially useful addition to the Web of data.”

@dret We reference http://webdata.systems/ in http://w3c.github.io/sdw/bp/#bp-linking-2.

**Comment by lvdbrink** [comment]
The reference to LD-BP was removed from section [12.2.1 Spatial data encoding][1]

[1]: http://w3c.github.io/sdw/bp/#bp-spatialdata

**Comment by 6a6d74** [comment]
[section 9 Linked Data](http://w3c.github.io/sdw/bp/#linked-data) now amended to specifically call out the Web-Data principles. Personally, I think they provide an excellent description of _our_ intended approach to Linked Data.

> In fact, our approach to linked data is well described by an alternative 5-star scheme from [WEB-DATA]:
> ★ Linkable: use stable and discoverable global identifiers
> ★★ Parseable: use standardized data metamodels such as CSV, XML, RDF, or JSON
> ★★★ Understandable: use well-known or at least well-documented vocabularies/schemas
> ★★★★ Linked: link to other resources whenever possible
> ★★★★★ Usable: label your document with a license

See [commit](https://github.com/w3c/sdw/pull/793/commits/87ebb4660b097dec77e52c5545a8b0fe6f303dc7) and PR #793.

**Comment by dret** [comment]
On 2017-05-04 17:16, Jeremy Tandy wrote:
> section 9 Linked Data <http://w3c.github.io/sdw/bp/#linked-data> now
> amended to specifically call out the Web-Data principles. Personally, I
> think they provide an excellent description of /our/ intended approach
> to Linked Data.

thanks, it's very good to see them mentioned in the document!
