### ISSUE TITLE
Mention ongoing GeoJSON work in IETF

### ISSUE THREAD

**Issue by dret** [w3c/sdw#227]
while the referenced GeoJSON specification is the current stable specification, it has no official status with any SDO. it would be great if the ongoing work in the IETF GeoJSON WG would be mentioned.

**Comment by dret** [comment]
interestingly, GeoJSON currently has the concept of an id, but just talks about this as a "number or a string". this could for example be augmented with guidance to make those strings URIs. 
https://tools.ietf.org/html/draft-ietf-geojson-00#section-2.2

**Comment by dret** [comment]
i have raised https://github.com/geojson/draft-geojson/issues/150 in an attempt to clarify if "id" really only is something that's specified for GeoJSON "Feature" objects, or whether the other object types should also be allowed to have an "id" member.

**Comment by lvdbrink** [comment]
We now reference https://tools.ietf.org/html/rfc7946.

**Comment by dret** [comment]
On 2017-03-17 14:59, Linda van den Brink wrote:
> We now reference https://tools.ietf.org/html/rfc7946.

excellent, i think this closes this issue. thanks!
