### ISSUE TITLE
Remove RDF bias when talking about semantics

### ISSUE THREAD

**Issue by dret** [w3c/sdw#229]
it would be very helpful if this document would be clear where it is about spatial data, and where it is about spatial linked data.
as one example, it talks about "using spatial semantics", and then jumps to the conclusion that for semantics to be present, RDF has to be used. this ignores decades of standardization of rich semantics for spatial data that simply happened before RDF was around, or for whatever reason even nowadays choose to use a different metamodel. GeoJSON is one such example, deliberately choosing JSON as a popular metamodel, and then defining spatial semantics.
implying that semantics can only be used and encoded confuses people looking for solutions. please make sure to use the term "semantics" correctly, and if you want to talk about RDF about one possible metamodel to represent semantics, then also make this explicit.

**Comment by dret** [comment]
as a point of reference, it is possible to practice web architecture without mandating a specific metamodel. http://dret.github.io/webdata/ is an attempt at doing this, trying to do what "linked data" is doing, without making one specific metamodel a mandate.

**Comment by lvdbrink** [comment]
@dret We reference http://dret.github.io/webdata/ in the BP document now and have, we think, removed RDF bias where it was present in the document. We think this issue can be closed; do you agree?

**Comment by dret** [comment]
On 2017-05-03 12:08, Linda van den Brink wrote:
> @dret <https://github.com/dret> We reference
> http://dret.github.io/webdata/ in the BP document now and have, we
> think, removed RDF bias where it was present in the document. We think
> this issue can be closed; do you agree?

to be honest, i am not going to re-read the whole document to check at 
this time. if you think you have addressed this issue as you see fit, 
then i am satisfied, and would like to thank you for the effort!
