### ISSUE TITLE
Does the BP doc need 'Conformance'? - it's a Note not a Rec

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#23]
The BP document currently contains a [conformance section](http://w3c.github.io/sdw/bp/#conformance). Given that this document is a Note, do we need this section?

**Comment by philarcher** [comment]
No - for the reason you cite.

I think ReSpec has a setting for non-Rec Track documents that should get 
rid of that but I can't be sure.

On 28/10/2015 04:10, Jeremy Tandy wrote:

> The BP document currently contains a [conformance section][http://w3c.github.io/sdw/bp/#conformance]. Given that this document is a Note, do we need this section?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/sdw/issues/23

## 

Phil Archer
W3C Data Activity Lead
http://www.w3.org/2013/data/

http://philarcher.org
+44 (0)7887 767755
@philarcher1

**Comment by lvdbrink** [comment]
Removed the section from the doc.
