### ISSUE TITLE
Make Best Practices more open

### ISSUE THREAD

**Issue by dret** [w3c/sdw#230]
currently one measure of quality control in terms of "do i follow the best practices" refers to the linked data principles. these make sense if people are using linked data for their spatial data. however, in order to be more open and inclusive, there should be a way for readers/practitioners to use different metamodels, and still "do the right thing".
the http://dret.github.io/webdata/ principles have been developed with the specific goal to just talk about "the web" and its architectural principles, and not one specific set of technologies.
these principles could help to make the document more inclusive and open, and to make sure that the many developers that for whatever reason are not using RDF technologies can still benefit from guidance and get the feeling and the feedback "to do the right thing".

**Comment by dret** [comment]
this is related to #229 and #225.

**Comment by 6a6d74** [comment]
Web-Data principles are referenced from BP14: https://www.w3.org/TR/sdw-bp/#entity-level-links

**Comment by lvdbrink** [comment]
@dret Could you check if you're satisfied this issue can be closed?

**Comment by dret** [comment]
On 2017-05-03 12:06, Linda van den Brink wrote:
> @dret <https://github.com/dret> Could you check if you're satisfied this
> issue can be closed?

to be honest, i am not going to re-read the whole document to check at 
this time. if you think you have addressed this issue as you see fit, 
then i am satisfied, and would like to thank you for the effort!

**Comment by lvdbrink** [comment]
I understand, and thank you for your efforts to review the document!
