### ISSUE TITLE
B. Authoritative sources

### ISSUE THREAD

**Issue by PeterParslow** [w3c/sdw#231]
Particularly the OS examples (as OS's Principal Geo Information Architect).
1. Please note that the '50kGazetteer' identifiers will not persist; they were part of our initial experimental foray into linked data. Personally, I'm disappointed that we haven't replaced that yet - we have the better identifiers minted & available (in CSV & GML formats), with two benefits: better lat/long, and persistent-by-design management. But not yet in linked data format (lack of web developers with those skills!).
1. the relationship between http://data.ordnancesurvey.co.uk/id/50kGazetteer/81482 and http://data.ordnancesurvey.co.uk/id/7000000000030505 is "more or less the same as". The former represents the fact that the text Edinburgh appears on a 50k map; the second represents the geometry of the administrative city of Edinburgh. I'm sure DCLG had an identifier for the social geography object 'City of Edinburgh' that runs the area with that geometry - but that doesn't seem to have persisted either. Looked at another way, the /81482 one is colloquial geography; the 30505 one is legal/administrative geography, with a crisp polygon edge. I guess the question is 'is Queensferry in Edinburgh'.

The statistics Edinburgh may well have the same boundary, but not all statistical geographies match administrative ones. Geonames doesn't seem to be explicit, but looks as if it is also the administrative one.

But most of the time, these distinctions don't matter for the use case in hand!

**Comment by lvdbrink** [comment]
We will substitute the 50k gazetteer URI with a GeoNames one.

**Comment by ghost** [comment]
We can use http://www.geonames.org/2650225 ?

**Comment by PeterParslow** [comment]
In my opinion, GeoNames is a good source for the colloquial geography. UK seems 'between stools' when it comes to official persistent identifiers for formal administrative geography: DCLG linked data seems to have gone, and the GDS register of Scottish admin units is only in Alpha. The English ones are persistent at https://local-authority-eng.register.gov.uk/records.

**Comment by 6a6d74** [comment]
Thanks @PeterParslow !

**Comment by ghost** [comment]
So I will just remove the link to OS which is a shame as we already reference geonames.. I need to find another reference then to the "place" Edinburgh..

**Comment by PeterParslow** [comment]
Can't think why I didn't spot this; in the year since I first made this comment, we have published OS OpenNames as linked data. This content comes from a system with proper managed identifiers, so http://data.os.uk/id/4000000074558316 is a persistent URI for 'colloquial' Edinburgh. I'd be happy for that to be used.

**Comment by 6a6d74** [comment]
@edpars0ns & @PeterParslow ... doc is updated now. Am closing this issue.
