### ISSUE TITLE
Naming of BP7 is inconsistent with other BPs

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/sdw#232]
BP7 is currently named "How to describe geometry". This is not consistent with other BP names that start with a verb in imperative, e. g. "Provide identifiers for parts of larger information resources". A better name for BP7 would be "Use an appropriate format to describe geometries".

**Comment by lvdbrink** [comment]
In the current draft this is BP8. It was renamed to Provide geometries on the Web in a usable way.
