### ISSUE TITLE
Add 'principles' from wiki into BP doc

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#25]
The [principles section](http://w3c.github.io/sdw/bp/#intro-principles) currently includes only a link to the [principles list in the wiki](https://www.w3.org/2015/spatial/wiki/BP_Principles).

Not all of these are applicable; need to review.

Seems to make sense to add relevant principles to Context or Scope sections of the BP document.

**Comment by lvdbrink** [comment]
Done; added some of the principles to Principles section and some to the Scope section.
