### ISSUE TITLE
Good practice for publishing geometry of a thing as different geometry types

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#251]
See this thread https://lists.w3.org/Archives/Public/public-sdw-wg/2016May/0021.html

Parts of this to be used as BP content.

**Comment by lvdbrink** [comment]
To be assessed if this issue can be closed after major rework on [BP8][1].

[1]: http://w3c.github.io/sdw/bp/#describe-geometry

**Comment by lvdbrink** [comment]
@andrea-perego could you assess if this issue can be closed, in your opinion, and put this in a comment?

**Comment by andrea-perego** [comment]
The publication of alternative versions of a geometry (in different dimension and at different levels of accuracy and precision) is now addressed in [BP6](http://w3c.github.io/sdw/bp/#multiplegeometries), whereas the publication of geometries in different formats is addressed in [BP5](http://w3c.github.io/sdw/bp/#describe-geometry) (formerly, BP8).

I think this issue can be closed.
