### ISSUE TITLE
Extension for mean date range

### ISSUE THREAD

**Issue by PeterBourgonje** [w3c/sdw#273]
The current list of properties that are available in the http://www.w3.org/2006/time# ontology supports , a.o. specific points in time, temporal intervals, directionality, inclusion/overlap, but no property exists to reason over multiple temporal annotations that are present within defined boundaries (e.g. either all temporal annotations within a sentence, paragraph, document or document set). 

In the platform we are developing (http://digitale-kuratierung.de/) we are using the Time ontology properties where possible to represent recognized and normalized temporal expressions. One of the use cases of our platform is time lining, e.g. taking a document collection and visualizing this in an intuitive way on a chronological axis. The position of a document on this axis depends on all temporal expressions found in the document. In addition to defining the position on a time line, we also want to display the “temporal spread” in an intuitive way. The average of a document mentioning several dates in the year 1983 may be the same as another document mentioning several dates in the year 2016 and the year 1950, but we want to distinguish between the two in a visual way. 

To achieve this, we are using two additional properties currently called meanDateStarts and meanDateFinishes, that allow us to display both the positioning and the spread on a line. To obtain them we calculate the average value and the standard deviation over multiple temporal values. All calculations are done based on number of milliseconds before or after Unix-epoch. The value for the meanDateStarts property then is the average value minus the value for standard deviation. The value for the meanDateFinishes property is the average value plus the value for standard deviation.

If you consider this functionality a useful addition to the Time ontology, perhaps the following can be considered as addition:

```
:meanDateFinishes
  rdf:type owl:ObjectProperty ;
  rdfs:comment "The average over a set of temporal expressions minus the standard deviation of the set."^^xsd:string ;
  rdfs:domain :ProperInterval ;
  rdfs:label "mean date finishes"^^xsd:string ;
  rdfs:range :ProperInterval ;
.
```

```
:meanDateStarts
  rdf:type owl:ObjectProperty ;
  rdfs:comment "The average over a set of temporal expressions plus the standard deviation of the set."^^xsd:string ;
  rdfs:domain :ProperInterval ;
  rdfs:label "mean date starts"^^xsd:string ;
  rdfs:range :ProperInterval ;
.
```

If you have any questions or require more specific information regarding our implementation our rationale, please just let me know!

**Comment by dr-shorthair** [comment]
This is an interesting extension, clearly well motivated for a time-line ontology. This application is, however, slightly outside the scope of OWL-Time. If we were to consider adding this, then there are likely multiple other properties of similar value. We are pleased to see OWL-Time being extended in this way, but suggest that such extensions are best handled in external ontoloies rather than as a core part of OWL-TIme itself.

**Comment by fsasaki** [comment]
@dr-shorthair , not asking for re-opening the issue, but what would you suggest for keeping track of such extensions? Or to put it differently, is there an extension mechanism foreseen for OWL-Time?

**Comment by dr-shorthair** [comment]
1. there is no definitive way to maintain a record of extensions to rdf vocabularies or ontologies. Its a consequence of the underlying open world assumption. Registries like LOV can help. For example, this SPARQL query finds  usage of time: classes that are registered in LOV

http://lov.okfn.org/dataset/lov/sparql

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX voaf:<http://purl.org/vocommons/voaf#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?vocab
WHERE{
GRAPH <http://lov.okfn.org/dataset/lov> {
    VALUES ?e { voaf:specializes voaf:generalizes voaf:extends voaf:metadataVoc voaf:hasEquivalencesWith
voaf:hasDisjunctionsWith owl:imports }
             ?v2 ?e <http://www.w3.org/2006/time>.
                        ?vocab dcat:distribution ?v2.  
    
  }
}

2. The extension mechanism is merely the generic one that OWL offers, i.e. owl:imports, rdfs:subClassof, rdfs:subPropertyOf, owl:equivalentClass, owl:equivalentProperty, owl:Restriction, etc.
