### ISSUE TITLE
Determine audience for BP

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#29]
In the [audience section](http://w3c.github.io/sdw/bp/#h-audience) we mention two different groups: Geospatial experts without web knowledge and Web developers without geospatial knowledge. 

With regards to the first group, Geospatial experts without web knowledge, we need to determine if we are indeed targetting them. 

Secondary issue: developer audiences are sometimes described as the [Large set of unknown developers and the Small set of known developers](http://thenextweb.com/dd/2013/12/17/future-api-design-orchestration-layer/). Is this a useful distinction for us to make?

**Comment by ghost** [comment]
Indeed I would say the "Geospatial experts without web knowledge" group are vital in liberating existing spatial data, already published but not visible or linkable. 

Not sure the known/unknown distinction is useful, perhaps we should assume they may never be a relationship with developers e.g. access via widely used API's ?

**Comment by lvdbrink** [comment]
Added the bit about them being vital to the doc; and removed the known/unknown developers wording.
