### ISSUE TITLE
Question on spatial operators

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#298]
Questions:
1) Will we specify that we understand operators to work on numerical data?
2) Is the difference between operators and relationships clear (compare GeoSPARQL fucntions and relationships)? For spatial relationships there is a separate requirement 

See also the original issue in the W3C issue tracker https://www.w3.org/2015/spatial/track/issues/23

**Comment by lieberjosh** [comment]
Yes. My understanding is that a relation is a statement about two entities. An operator is a function that creates a new entity (perhaps temporarily) given one or more existing entities. Once a new entity is created, one may be able to make a logical statement about the old and new entities that echoes the operator, but they are not the same thing.

—Josh

**Comment by cportele** [comment]
This issue will be addressed in an update to BP 11.

**Comment by lvdbrink** [comment]
@cportele did you address this issue?

**Comment by cportele** [comment]
@lvdbrink Hm, looking at the issue text again: no, not really.  I included guidance about the typical (minimal) operators that should be considered in queries in a spatial data access API, but that is a small aspect. The new BP 10 (Publish links between spatial things and related resources) provides guidance for spatial relationships. Currently we do not have a discussion about relation vs operator, but I wonder whether that is really needed? If it needs to be clarified maybe this is best done in the glossary by adding the terms "spatial relation(ship)" and "spatial operator"?

**Comment by lvdbrink** [comment]
Yes, agreed... could you perhaps add those terms?

**Comment by cportele** [comment]
Done. 

See https://github.com/w3c/sdw/pull/789

**Comment by cportele** [comment]
Closing the issue, the change has been merged into the Editor's draft.
