### ISSUE TITLE
Inverse Properties in SOSA-Core

### ISSUE THREAD

**Issue by kjano** [w3c/sdw#334]
Wrt 5764c89 , we should agree on how to handle properties and their inverse properties in SOSA-Core. Should they be explicitly stated or not?

From the commit message:
Next important issue for our discussion (even though it is a very old one :-)): 
See http://richard.cyganiak.de/blog/2006/06/an-rdf-design-pattern-inverse-property-labels/ and also Aidan's reaction. We do so for hosts and hostedBy but not for all properties. I would propose to be consistent and **do** it for all. Even more, I am in favour of using owl:inverseOf (https://www.w3.org/TR/owl-ref/#inverseOf-def). @dr-shorthair , @axh599, all, what do you think?

Also, if we have decided on how to proceed, would you all agree that we have a first version of SOSA-core that can and should be discussed during our SSN telcons?

Jano

**Comment by dr-shorthair** [comment]
My hunch is that we should 
(a) provide properties to relate every useful combo of the classes that we have introduced
(b) yes, also give names to the inverses and declare them as such. 

I know that we are avoiding loading too much owl/rdfs semantics in the core, but it would be perverse not to use owl:inversOf to state this (just as it would be perverse not to use meta:rangeIncludes and meta:domainIncludes for annotating the usage expectations, despite, or perhaps because of the lack of ontological commitment!).

**Comment by kjano** [comment]
> (a) provide properties to relate every useful combo of the classes that we have introduced

Same here.

> (b) yes, also give names to the inverses and declare them as such. 

Great.

> I know that we are avoiding loading too much owl/rdfs semantics in the core, but it would be perverse not to use owl:inversOf to state this (just as it would be perverse not to use meta:rangeIncludes and meta:domainIncludes for annotating the usage expectations, despite, or perhaps because of the lack of ontological commitment!). 

As I stated during many telcons, I feel a bit misquoted/misunderstood about the use of RDFS in SOSA-core :-). My point was to create a surface axiomatization that is usable and understandable for folks that have not used DLs for years. Something in the _spirit_ of schema.org. Whether SOSA-core should be entirely RDF(S) based is not the point. I am absolutely fine with adding OWL elements and thus propose using owl:inverseOf. We also already have owl:AnnotationProperty in there. We want to keep SOSA-core readily usable and clearly having defined names for inverse relations is very useful. Same goes for subclassing. I am not against subclassing in SOSA-core in general, but suggested to keep it at a bare minimum and only make use of it if it really adds to semantics. To make a long story short, we seem to agree.

**Comment by kjano** [comment]
Done: 054803f  (for most properties where the idea of an inverse makes sense intuitively)
