### ISSUE TITLE
SSN/SOSA-Core - Observation vs Observing or Sensing - Nouns, verbs, activities

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw#335]
We have been circling around the naming of 'Observation' or 'Sensing'. Probably worth a clean issue. 

Last week Armin wrote: 

> > I kept Observation as is. I don’t have a strong opinion on Observation. I think it would be better named Observing, but that’s up to you Simon.

I responded: 

> I agree that it would be helpful to be consistent. I considered making that change already myself, particularly looking at the diagrams on the Wiki page https://www.w3.org/2015/spatial/wiki/File:Activity.png 
> A concern is that in English *ing words are progressive/continuous verbs. I think we want to denote activities, for which a critical characteristic is that they are time-bounded, often instantaneous, so wasn’t quite sure that the continuous form made sense, unless it is always to be understood as “activity of *ing” . 

The diagram linked above was my attempt to clarify the nature of the issue. The questions following are 
(i) is "Observation" the same as "_Activity of observing_" or "Application of observation procedure" i.e. an event-ish kind of thing, , or 
(ii) is it rather a "_Record of Observation_". 
(iii) can "Sensing" or "Observing" be used for the general case, including computation, interpretation, forecasting, as well as traditional sensing using a sensor, or do we need a more general word, like "**Estimating**". 
(iv) If we  have "Sample" and "Actuator", then don't we also need "Sampling" and "Actuating"? 
(v) in which case, wouldn't it be helpful to have a common superclass for all these activities? (equivalent to prov:Activity ...)

**Comment by maximelefrancois86** [comment]
For the record, 

(i), (ii) Observation has now been defined as the Act of carrying out an (Observation) Procedure to estimate or calculate a value of a property of a FeatureOfInterest. Links to a Sensor to describe what made the Observation and how; links to an ObservableProperty to describe what the result is an estimate of, and to a FeatureOfInterest to detail what that property was associated with.

(iii) has not been answered

(iv) Sampling and Actuating have been added in SOSA

(v) no such class has been proposed. SEAS proposes https://w3id.org/pep/ProcedureExecution
