### ISSUE TITLE
Find out which vocabularies have social spatial relationships

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#34]
Which vocabularies out there have social spatial relationships? FOAF, GeoNames, ... 

By social spatial relationships we mean relationships that are not geometric or topological, but for example hierarchy relationships like one region being part of another. 

NB it is not clear to me what is meant by social spatial relationships. Is partOf a good example? Are there others?

**Comment by lvdbrink** [comment]
Relates to [Publishing data with clear semantics](http://w3c.github.io/sdw/bp/#bp-clear-semantics) section

**Comment by 6a6d74** [comment]
Given redrafts of the best practice document, this issue is now time expired.
