### ISSUE TITLE
Determine where to place reference to GeoDCAT-AP

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#35]
The Data on the Web Best Practice is addressing discovery at the dataset level including spatial and temporal coverage. Either the DWBP or the SDWBP should refer to GeoDCAT-AP. It must be determined where this reference should go. If the DWBP will not reference it, the SDWBP should.

**Comment by FransKnibbe** [comment]
I think it should be in the SDWBP anyway. GeoDCAT-AP is not only related to the discoverability requirement (http://w3c.github.io/sdw/UseCases/SDWUseCasesAndRequirements.html#Discoverability), but also to http://w3c.github.io/sdw/UseCases/SDWUseCasesAndRequirements.html#Compatibility,  http://w3c.github.io/sdw/UseCases/SDWUseCasesAndRequirements.html#BoundingBoxCentroid, http://w3c.github.io/sdw/UseCases/SDWUseCasesAndRequirements.html#Crawlability, http://w3c.github.io/sdw/UseCases/SDWUseCasesAndRequirements.html#SpatialMetadata and http://w3c.github.io/sdw/UseCases/SDWUseCasesAndRequirements.html#Provenance.
So it is a very important practice, for many reasons.

**Comment by 6a6d74** [comment]
@Fransie - We have a specific Best Practice regarding the use of GeoDCAT-AP and other 'spatial' metadata for datasets: [Best Practice 26 Include spatial information in dataset metadata](http://w3c.github.io/sdw/bp/#spatial-info-dataset-metadata). 

I think that we have adequately determined the relationship between DWBP and SDW metadata, so I am closing this issue.

Thanks for compiling the list of requirements. I will include these in the BP doc for [BP 26](http://w3c.github.io/sdw/bp/#spatial-info-dataset-metadata) ...

**Comment by andrea-perego** [comment]
@6a6d74 , @lvdbrink , sorry to re-open this issue, but going through the current BP document, I think there are at least a couple of other places where a reference to GeoDCAT-AP could be added:
1. BP7 - [How to describe geometry](http://w3c.github.io/sdw/bp/#describe-geometry): The approach agreed upon by the GeoDCAT-AP WG, and included in the specification, is to recommend the use of WKT and/or GML, to ensure interoperability, but without preventing people from using additional representations. This has been also implemented in the [GeoDCAT-AP XSLT](https://webgate.ec.europa.eu/CITnet/stash/projects/ODCKAN/repos/iso-19139-to-dcat-ap/), that generates WKT, GML and GeoJSON encodings for the spatial coverage in the original ISO 19139 records.
2. BP25 - [Make your entity-level data indexable by search engines](http://w3c.github.io/sdw/bp/#indexable-by-search-engines): The implementation activities on GeoDCAT-AP included the development of an [API](https://webgate.ec.europa.eu/CITnet/stash/projects/ODCKAN/repos/iso-19139-to-dcat-ap/browse/api) (demo [here](http://geodcat-ap.semic.eu:8890/api/)), that can be used on top of a CSW to expose ISO 191139 records as GeoDCAT-AP (in different RDF serialisations) and via HTTP conneg. One of the supported serialisations is HTML+RDFa (example [here](http://geodcat-ap.semic.eu:8890/api/?outputSchema=extended&src=http%3A%2F%2Fsdi.eea.europa.eu%2Fcatalogue%2Fsrv%2Feng%2Fcsw%3Frequest%3DGetRecords%26service%3DCSW%26version%3D2.0.2%26namespace%3Dxmlns%2528csw%3Dhttp%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2529%26resultType%3Dresults%26outputSchema%3Dhttp%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd%26outputFormat%3Dapplication%2Fxml%26typeNames%3Dcsw%3ARecord%26elementSetName%3Dfull%26constraintLanguage%3DCQL_TEXT%26constraint_language_version%3D1.1.0%26maxRecords%3D20&outputFormat=text%2Fhtml)). So, the GeoDCAT-API can be mentioned as an example of exposing a spatial data service on the Web, and to serve its data in a way that enables their discovery via search engines.

If this makes sense to you, I can draft the relevant text.

**Comment by lvdbrink** [comment]
GeoDCAT is now also referenced in [BP8][1] and [BP17][2]. Not in [BP4][3] (Make your spatial data indexable by search engines). 

[1]: http://w3c.github.io/sdw/bp/#describe-geometry
[2]: http://w3c.github.io/sdw/bp/#bp-crs
[3]: http://w3c.github.io/sdw/bp/#indexable-by-search-engines

**Comment by lieberjosh** [comment]
Also GeoDCAT-AP is referenced in BP1

**Comment by andrea-perego** [comment]
@lvdbrink 

> GeoDCAT is now also referenced in BP8 and BP17. Not in BP4 (Make your spatial data indexable by search engines).

As I mentioned during one of our last calls, I was actually planning to include a reference to the GeoDCAT-AP API (originally in the "Narrative"), that is also providing HTML+RDFa as an output format. 

Draft text is visible on my sdw fork (yellow text in Example 8):

https://andrea-perego.github.io/sdw/bp/#indexable-by-search-engines

**Comment by lvdbrink** [comment]
@andrea-perego can you please check if this issue can be closed in your opinion?

**Comment by lvdbrink** [comment]
We reference in several places, and may reference it in BP8 too if Andrea thinks it is pertinent to do so
