### ISSUE TITLE
Should BP "describing properties that change over time" include time series?

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#356]
[BP5](http://w3c.github.io/sdw/bp/#desc-changing-properties) addresses the situation where the properties of a spatial thing are updated due to some new measurement or assertion. This could be a spatial thing whose properties are captured
as a series of discrete snapshots through time, but the property could also be a time dependent variable that is being measured or estimated according to some sampling regime. In that case you have a time series. Should this be described as a second "possible approach to implementation" ?

See [this thread](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Aug/0138.html) for discussion.

**Comment by lvdbrink** [comment]
Related issue: #170

**Comment by 6a6d74** [comment]
The WG agree that this is a valid approach; especially for sensor data (streams).

Elaboration of this time-series approach is still required; perhaps linking to CoverageJSON (examples) for how to do this? Also note that the OGC Moving Features specification ([OGC #14-083](http://docs.opengeospatial.org/is/14-083r2/14-083r2.html)) follows this pattern, albeit with specific terminology such as “foliation”, uses a “trajectory” element to describe the position plus the ability to add varying attributes (such as orientation or rotation) alongside the tuples in the trajectory. OGC also offer a CSV-format “compact encoding” ([OGC #14-084](http://docs.opengeospatial.org/is/14-084r2/14-084r2.html)). Moving Features appears to convey the same information as would be achieved by embedding a time-series coverage as a property of a feature, it just makes some different encoding choices.

**Comment by 6a6d74** [comment]
[Best Practice 6](https://w3c.github.io/sdw/bp/index.html#desc-changing-properties) has been amended to include references to the "time-series" approach. Detailed examples are not provided, but references to the relevant encoding standards are.

OGC &#174; Moving Features is referenced in a note, but with the caveat that it has not seen widespread adoption outside of Japan.

Closing this ISSUE.
