### ISSUE TITLE
Should we include recommendations on uri strategy / hierarchic uris

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#358]
Should we describe a practice of identifiers being structured minimally at least for purposes of authority and uniqueness? And when to consider taxonomic meaning for primary or secondary identifiers. 

Josh has offered to write about this.

**Comment by 6a6d74** [comment]
I would suggest that we simply refer to the URI structure guidance in DWBP.

**Comment by 6a6d74** [comment]
During the London F2F meeting of SDW WG, we agreed:

> we covered enough of the concern about structuring URIs for authority and uniqueness in the preceding paragraph and we recognise that although it would be nice to include a spatial hierarchy in the URL structure, this may result in URLs not being durable - the URI would have to change if the “containment” changed.

Examples of such change occur when electoral division boundaries are changed; moving an area from one electoral division to another. (see [Local Government Boundary Commission for England](https://www.lgbce.org.uk))
