### ISSUE TITLE
Write a shared note with the DWBP

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#36]
Linksets does not seem to be an evidence-based best practice. It might be an emerging practice (e.g. the CSIRO example). This might go in a shared note with the DWBP. An example of expressing a collection of links from the library community is [here](https://gbv.github.io/beaconspec/beacon.html). An example vocabulary for expressing link sets is [in VoID](http://www.w3.org/TR/void/#describing-linksets).

When this note is published, add a reference to the SDW BP doc.

**Comment by lvdbrink** [comment]
Relates to [Enabling discovery](http://w3c.github.io/sdw/bp/#bp-discovery) section

**Comment by lvdbrink** [comment]
Discuss if we still want to do this.

**Comment by 6a6d74** [comment]
I have an action to move one third of the BP14 into the conclusions section for open interoperability issues ... I'll close this issue once I have done this.

**Comment by 6a6d74** [comment]
We are not going to write a shared Note because DWBP has now closed
