### ISSUE TITLE
Expressing the fuzziness of a spatial thing

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#37]
It is often in social discourse useful to identify spatial things even though they're fuzzy. Do we need a subclass of SpatialThing or a property that expresses the fuzziness of a spatial thin? Is there something like this in current or emerging practice?

**Comment by lvdbrink** [comment]
Relates to [Expressing spatial data](http://w3c.github.io/sdw/bp/#bp-expressing-spatial) section

**Comment by ghost** [comment]
Conceptually I would love to reverse the logic e.g. some spatial things have geometry ?

**Comment by 6a6d74** [comment]
In his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0040.html) Bill states:

<em>perhaps it is more natural to allow a SpatialThing to have either a precise spatial extent, or a fuzzy spatial extent, or an undefined spatial extent, and create a subclass of it for the subset of things that do have a clearly defined spatial extent</em>

**Comment by lvdbrink** [comment]
This is addressed in [BP14][1] now. Review necessary to assess if this is sufficient.

[1]: http://w3c.github.io/sdw/bp/#entity-level-links
