### ISSUE TITLE
How do we ensure alignment between terminology used in BP and new spatial ontology?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#382]
How do we ensure alignment with the terminology being used in the <a href="https://www.w3.org/2015/spatial/wiki/Further_development_of_GeoSPARQL">further development of GeoSPARQL</a>? We expect a new spatial ontology to be published which will contain clear and unambiguous definitions for the terms used therein.

**Comment by lieberjosh** [comment]
Setting a high bar there, Jeremy ("clear and unambiguous” ). I’ve documented the entities in the draft ontology to a certain extent so far, but more can be done. The terminology is generally consistent with ISO and OGC usage as well as conceptual models, which I believe we’ve kept an eye on for the BP, so it shouldn’t be a huge alignment issue. More direct imports, e.g. for QB4S, will require more work, but carry benefits of consistency and reuse.

Josh

**Comment by lvdbrink** [comment]
We can't do the alignment at this moment because the spatial ontology will not be finished before the BP. 

Will put a green note about this new spatial ontology into the [new appendix][1] and ask Josh to write that note.

[1]: https://www.w3.org/2015/spatial/wiki/Detailed_planning_BP_document#File_formats_and_vocabularies

**Comment by 6a6d74** [comment]
Suggest that this 'note' about the new spatial ontology is added to the new Appendix being developed by @andrea-perego and @BillSwirrl - see [their action in the detailed plan](https://www.w3.org/2015/spatial/wiki/Detailed_planning_BP_document#File_formats_and_vocabularies) for further details.

**Comment by 6a6d74** [comment]
@lieberjosh - can you help with this?

**Comment by lieberjosh** [comment]
I’ll post the note this weekend.

**Comment by lvdbrink** [comment]
@lieberjosh I think this is still an open action for you?

**Comment by lvdbrink** [comment]
Note was added in #851
