### ISSUE TITLE
Do we also need to introduce spatial relationships?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#383]
Do we also need to talk about spatial relationships? And how they are related to spatial things and geometries?

**Comment by lieberjosh** [comment]
sdwgeo also includes the 8 basic so-called topological relations (the reduce spatial relationships to topological ones). These mathematical relationships connect geometries (i.e. point sets) but the predicates can be inferred or asserted for features (SpatialThings) as a consequence (e.g. of chain axioms).

Josh

**Comment by lvdbrink** [comment]
Now covered in [BP14][1]. To be reviewed.

Also, the [discussion on samePlaceAs][2] is related. 

[1]: http://w3c.github.io/sdw/bp/#bp-linking
[2]: https://lists.w3.org/Archives/Public/public-sdw-wg/2017Mar/0171.html

**Comment by 6a6d74** [comment]
Agreed.
