### ISSUE TITLE
Best Practice "Provide context required to interpret data values" needs clarification

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#384]
[Best Practice "Provide context required to interpret data values"](http://w3c.github.io/sdw/bp/#provide-context) is under review by the WG to see if it is sufficiently covered in DWBP. (see <a href="http://www.w3.org/2016/08/24-sdwbp-minutes.html#action01">action</a>)

**Comment by lvdbrink** [comment]
It was decided to remove this. See [minutes][1]

[1]: https://www.w3.org/2017/03/08-sdw-minutes
