### ISSUE TITLE
Introduction to CRS does not cover non-geographic cases

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#392]
Best Practice scope is "spatial data" - which includes non-geographic location (e.g. where things aren't positioned relative to the Earth). For example, we have a microscopy use case where the locations of cells are described.

**Comment by KerryLea** [comment]
Also, ssn  uses the notion of relative location (inherited from sensorml) for enabling Sensors to  be located in space relative to their Platforms  (which in turn might be located according to a geographic CRS).  However, ssn does not say *how* to encode this relationship so it would be nice to refer to BP for relative locations. Having said that, it is not fundamentally necessary and I don't have a firm proposal, either. 

This  use case might also apply to sosa (ssn core) , but that is unclear to me.

**Comment by dr-shorthair** [comment]
Strictly all locations are relative. Its just that for some the reference frame is geodetic, and for others the reference frame is local. The ISO coordinate reference system standard refers to non-geodetic frames as 'engineering coordinate reference systems' since they are commonly used in engineering contexts.

**Comment by lvdbrink** [comment]
http://w3c.github.io/sdw/bp/#relative-position now talks about this. However, this issue is related to [Section 8. Coordinate Reference Systems][1] but whether relative positioning should be added to the intro is debatable imho. 

[1]: http://w3c.github.io/sdw/bp/#CRS-background

**Comment by lvdbrink** [comment]
[Discussion on the mailing list][1] suggests we should be clear about when we're talking about spatial vs geospatial data. Also, [Martian spatial data][2] was mentioned. 

[1]: https://lists.w3.org/Archives/Public/public-sdw-wg/2017Apr/0009.html
[2]: https://lists.w3.org/Archives/Public/public-sdw-wg/2017Mar/0250.html

**Comment by 6a6d74** [comment]
Section  [§3.1 Spatial Data](http://w3c.github.io/sdw/bp/#spatial-data) in the BP Scope is updated to assert that we are focused on geospatial data.

ISSUE text removed from BP doc via PR #788.
