### ISSUE TITLE
Detailed examples needed that use schema.org to describe spatial data

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#447]
Detailed examples are required for HTML pages and the structured markup. It’s early days for using schema.org to describe spatial attributes - can we write some useful statements and badge them as “emerging practice” to drive the right behaviours?

**Comment by lvdbrink** [comment]
Here is one: https://data.pdok.nl/datasets/nationaal-wegenbestand-wegen

**Comment by 6a6d74** [comment]
Also see [comment](https://github.com/w3c/sdw/issues/446#issuecomment-276993665l) made for ISSUE #446 providing some schema.org snippets.

BP4 now includes real examples.

Closing this ISSUE.
