### ISSUE TITLE
Example target doesn't resolve: geo.resc.info

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#482]
The example in [Best Practice 11: Expose spatial data through 'convenience APIs'](http://w3c.github.io/sdw/bp/index.html#convenience-apis) on [BP doc line 1818](https://github.com/w3c/sdw/blob/gh-pages/bp/index.html#L1818) doesn't resolve - at least not today ...

```
http://geo.resc.info:8080/geoserver/netage/wms?service=WMS&amp;version=1.1.0&amp;request=GetMap&amp;layers=netage:provincie&amp;styles=&amp;bbox=10426.282,306846.198,278026.09,621876.3&amp;width=652&amp;height=768&amp;srs=EPSG:28992&amp;format=application/openlayers
```

@semanticfire - I think this is one of yours - could you verify? Thank you!

(in the WD about to be released I've left this as URI in a `<code>` element rather than a hyperlink)

**Comment by cportele** [comment]
Not related to resolving, but a question related to the URL: 

A WMS counts as a "convenience API"? I thought "convenience API" was not about generic APIs like SPARQL, the Linked Data API, OGC Web Service interfaces, Open Search, etc, but would be APIs that were specific to a dataset. However, several of the examples in BP11 seem to refer to standardized APIs, so I must be wrong. 

To me "convenience API" was the same as "Bespoke API designed to support a particular application" from the bullet list above BP11. If "Generalized query APIs" also count as "convenience APIs", we could probably just drop "convenience" and just say "API"?

**Comment by semanticfire** [comment]
the correct URI: 
http://geo.resc.info/geoserver/netage/wms?service=WMS&version=1.1.0&request=GetMap&layers=netage:provincie&styles=&bbox=10426.282,306846.198,278026.09,621876.3&width=652&height=768&srs=EPSG:28992&format=application/openlayers

If its in the BP it needs to be stable for a while I guess

**Comment by lvdbrink** [comment]
Not in the current BP draft anymore. This issue can be closed I think.
