### ISSUE TITLE
Geluidskaarten API in SwaggerHub not found

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#499]
Hi, when looking through some final changes made by @philarcher1 I decided to take a look at the link to Geluidskaarten API in SwaggerHub: https://app.swaggerhub.com/api/pdok/geluidskaarten/1.0

This API is not found on swagger hub. Does it still exist? Did it move?

Assigning to @lvdbrink in she knows ...

See https://github.com/w3c/sdw/blob/gh-pages/bp/index.html#L1810

**Comment by lvdbrink** [comment]
Needs to be fixed still.

**Comment by lvdbrink** [comment]
@dvh in the Spatial data on the web best practice (Example 50 in http://w3c.github.io/sdw/bp/#convenience-apis) we are referring to your Geluidskaarten API on Swaggerhub as an example of a  ‘RESTful API as a wrapper, proxy or a shim layer around SDI services” 

However the link we use is not working anymore for a while now (404)

Could you give us a working link to this or a similar API that could serve as an example? It needs to be a working, non-experimental and stable API

**Comment by dvh** [comment]
These APIs have been killed unfortunately...

**Comment by lvdbrink** [comment]
Do you know another similar one we could link to?

**Comment by dvh** [comment]
Isn't LDProxy doing the same thing?

**Comment by lvdbrink** [comment]
Yes but what we would like is a link we can incorporate in the BP to an actual API on top of an SDI (aka an OGC service)  and we want it to be stable so the link won't break.

**Comment by dvh** [comment]
I'm afraid the answer is no then...

**Comment by lvdbrink** [comment]
removed broken ref to this API
