### ISSUE TITLE
Requirements need a short-name to make them easy to refer to

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#50]
The Requirements listed in the [Use Case and Requirement document](http://www.w3.org/TR/sdw-ucr/) are listed by number only ... which is a fragile referencing system should the doc section numbers change. Typically within W3C documents the Requirements are given short-names to make them easier to refer to. For example, refer to the [DWBP UCR document](http://w3c.github.io/dwbp/usecasesv1.html#req1).

So for example, our first requirement [5.1 Bounding box and centroid](http://www.w3.org/TR/sdw-ucr/#BoundingBoxCentroid) might be named _R-BoundingBoxCentroid_. I think that most of the work has already been done here, as the section element for each requirement already has a short-name in the `id` attribute; e.g. `BoundingBoxCentroid`.

**Comment by FransKnibbe** [comment]
Use cases as wel as requirements have IDs that can be used as fragment identifiers (e.g. #BoundingBoxCentroid). You can see the fragment identifiers when you hover over the table of contents. The main URI of the UCR document can be expected to change (unless you refer to the first or second public working draft), but the fragment identifiers can be expected to remain stable (unless a use case or requirement undergoes significant changes). Can you manage with using the IDs and ignoring the numbers?

**Comment by FransKnibbe** [comment]
OK, I found out yesterday that the URI http://www.w3.org/TR/sdw-ucr is stable and always points to the latest published version. So this URI plus the fragment identifier should give stable references. For example: http://www.w3.org/TR/sdw-ucr#BoundingBoxCentroid
