### ISSUE TITLE
Axis order probably inverted in Example 11

### ISSUE THREAD

**Issue by andrea-perego** [w3c/sdw#533]
Ref: http://w3c.github.io/sdw/bp/#ex-schemaorg-dataset

The issue concerns the first JSON-LD snippet.

In  the following lines:

````json
    "geo" : {
      "@type" : "GeoShape",
      "box" : "3.053,47.975 7.24,53.504"
    }
````

the axis order is supposed to be lat/long. But, in this case, the upper / lower corners are near Somalia:
- http://geohash.org?q=3.053,47.975
- http://geohash.org?q=7.24,53.504

If inverted, the two points denote a bbox including the Netherlands and other neighbouring countries. 
- http://geohash.org?q=47.97,53.053
- http://geohash.org?q=53.504,7.24

So, it should be probably re-written as:

````json
    "geo" : {
      "@type" : "GeoShape",
      "box" : "47.975,3.053 53.504,7.24"
    }
````

**Comment by cportele** [comment]
@andrea-perego 

You are right. I created a PR: https://github.com/w3c/sdw/pull/535

I remember that we had indications that some were using long/lat and some lat/long and we opted to use long/lat following GeoJSON etc, but based on the wording of the schema.org spec it should rather be lat/long for GeoShape (based on the rNews/GeoRSS origin).

**Comment by 6a6d74** [comment]
@andrea-perego: thanks for spotting this
@cportele: thanks for fixing it

**Comment by 6a6d74** [comment]
Hi @andrea-perego and @cportele ... I just wanted to check something.

Looking at RFC 7946 (GeoJSON), it has examples about the antimeridian (see [§5.2](https://tools.ietf.org/html/rfc7946#section-5.2))

```  "bbox": [177.0, -20.0, -178.0, -16.0] ```

This is clearly showing (lon / lat) coordinates.

I'm confused!

**Comment by cportele** [comment]
@6a6d74 

Your example is GeoJSON (which is explicitly long/lat), but the BP example is schema.org (which is not very specific on axis order, but says: "A GeoShape can be described using several properties whose values are based on latitude/longitude pairs. Either whitespace or commas can be used to separate latitude and longitude"; https://schema.org/GeoShape). 

The geo part in schema.org has been inspired by rNews, which also uses lat/long. For some history (just one example): https://lists.w3.org/Archives/Public/public-vocabs/2012Jun/0116.html. The examples there also clearly use lat/long.

**Comment by 6a6d74** [comment]
Doh! Where did I get GeoJSON from. Thanks for clarification...
