### ISSUE TITLE
Add reference to DWBP BP 11

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#56]
Add reference to DWBP BP 11 (if this is still the correct number - I don't remember what the BP was about), once Phil Archer gets this addition approved by the DW WG.

This reference goes into the section [Assigning identifiers to real world things and information resources](http://w3c.github.io/sdw/bp/#bp-identifiers)

**Comment by philarcher** [comment]
The relevant BP has been accepted into the DWBP doc, see http://w3c.github.io/dwbp/bp.html#DataIdentifiers. The DWBP WG is expecting to publish the next iteration of the document with that BP included before Christmas (probably on Thursday 17 which might be the FPWD date for SDW BP too of course). If so, we can link to the BP in /TR space, which is better than the draft in GH. Note that the fragment identifier for the BP is not dependent on numbering which is subject to change.

**Comment by lvdbrink** [comment]
Added reference; change the URL once new DWBP version is published.

**Comment by lvdbrink** [comment]
URL of published version added
