### ISSUE TITLE
Geonames URIs

### ISSUE THREAD

**Issue by barthanssens** [w3c/sdw#654]
I was under the impression that geoname URIs end with "/", e.g. the example at the end of "5. Spatial Things, Features and Geometry" should read "http://sws.geonames.org/2650253/" instead of " "http://sws.geonames.org/2650253" (see http://www.geonames.org/ontology/documentation.html)

**Comment by lvdbrink** [comment]
To be fixed

**Comment by larsgsvensson** [comment]
I think I found all of them and issued a pull request #e743ea3

**Comment by lvdbrink** [comment]
Solved
