### ISSUE TITLE
Should we reference GeoJSON text sequences

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#656]
There's a new standard coming from the IETF GeoJSON WG soon that could be added to the list of formats:  GeoJSON text sequences. See the [RFC][1], for motivation see also [GeoJSON on GitHub][2].

[1]: https://www.rfc-editor.org/authors/rfc8142.txt 
[2]: https://github.com/geojson/geojson-text-sequences

**Comment by lvdbrink** [comment]
Review more closely to find out if it's answering a problem we've identified. 

If so, mention as an emerging approach to resolving this (probably in a green note).

**Comment by ghost** [comment]
The issue of very large GeoJSON files is an issue and will not doubt increase as GeoJSON is more widely used. For many to the type of use cases we talk about this is not likely to be an issue, but if there are large complex geometries to be encoded users need to be aware, and possibly look for a different approach.

There are a number of different approaches to this some server sides and some like GeoJSON text sequences client side. Other client side techniques include [GeoJSON-VT](https://www.mapbox.com/blog/introducing-geojson-vt/) which implements vector tiling of GeoJSON in the browser.

Increases in browser performance and developments such as [web-workers ](https://www.w3.org/TR/workers/) may also mitigate the issue.

I suggest we note that although there may be some performance issues with GeoSJON processing in the browser there are solutions emerging to mitigate these..

**Comment by 6a6d74** [comment]
@lvdbrink, @andrea-perego 

Hi- what's the status on this issue? We discussed it during the [SDWBP subgroup call on 12-April](https://www.w3.org/2017/04/12-sdwbp-minutes) "Consider inclusion of "GeoJSON Text Sequences" in BP doc" 

The minutes say:

> Andrea with help from Ed | Refer to GeoJSON Text Sequences as just one of the methods to work with large geometry objects; see GitHub Issue 656

I guess this is tied up with the larger set of edits on BP's 5 or 6 (was BP8)?

Thanks.

**Comment by andrea-perego** [comment]
On Tue, May 2, 2017 at 1:48 PM, Jeremy Tandy <notifications@github.com> wrote:
>
> @lvdbrink, @andrea-perego
>
> Hi- what's the status on this issue? We discussed it during the SDWBP subgroup call on 12-April "Consider inclusion of "GeoJSON Text Sequences" in BP doc"
>
> The minutes say:
>
>> Andrea with help from Ed | Refer to GeoJSON Text Sequences as just one of the methods to work with large geometry objects; see GitHub Issue 656
>
> I guess this is tied up with the larger set of edits on BP's 5 or 6 (was BP8)?

Indeed. I plan to include this in BP6.

> Thanks.

**Comment by andrea-perego** [comment]
Reference to GeoJSON Text Sequences, GeoJSON-VT is now included in [BP6](http://w3c.github.io/sdw/bp/#multiplegeometries), point (2): "Use formats optimizing access to and processing of geometry data"

@edpars0ns , could you please check if you're happy with what said there?

**Comment by ghost** [comment]
Looks good to me.

**Comment by andrea-perego** [comment]
Thanks, @edpars0ns .

@lvdbrink , I think this issue can be closed.
