### ISSUE TITLE
BP: Aligning OGC bib entries

### ISSUE THREAD

**Issue by andrea-perego** [w3c/sdw#768]
- The URLs used in OGC bib entries sometimes point to the specification's landing page, sometimes to the document itself. It may be worth deciding which to use, and use it consistently
- There are two different entries in bpconfig.js about the same spec, which are both referred to from the BP document: [[SENSORTHINGS](http://w3c.github.io/sdw/bp/#bib-SENSORTHINGS)] and [[SensorThings](http://w3c.github.io/sdw/bp/#bib-SensorThings)]

**Comment by 6a6d74** [comment]
Where it makes sense to do so, let's point to the Landing Page.

And by default, we should use UPPER CASE for the bib reference.

**Comment by lvdbrink** [comment]
OGC-TOPIC-2 does not have its own landing page.

Changed the rest of the OGC entries.

Removed the duplicate SensorThings biblio entry.
