### ISSUE TITLE
Need to describe how the proposed best practices differ from typical SDI approaches

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#79]
A starter for 10 on the main differences ...
Best Practice 1: Use globally unique identifiers for entity-level resources
Best Practice 19: Make your entity-level links visible on the web
Best Practice 28: Expose entity-level data through ‘convenience APIs’

**Comment by ghost** [comment]
The context for these (which I agree with completely) is that in the LD world in contrast to the SDI world there is no a widespread separation of content and metadata. SDI's mirror the digital equivalent of the card catalogue and map chest.

**Comment by lvdbrink** [comment]
I think we sufficiently address this now in [section 7](http://w3c.github.io/sdw/bp/#why-are-traditional-sdi-not-enough).
