### ISSUE TITLE
Change intro wording to include coverage data

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#82]
'data related to a specific location' seems to exclude coverage data. This is not the intention, the scope includes coverage data. New wording is necessary to make this clear in the introduction. 

Frans, can you suggest new wording?

**Comment by FransKnibbe** [comment]
The easiest solution would be to just drop the word 'specific': 'data related to location' can include coverage data in my opinion.

**Comment by lvdbrink** [comment]
Solved as Frans suggested.
