### ISSUE TITLE
Editorial issues in BP glossary entry "dimension"

### ISSUE THREAD

**Issue by andrea-perego** [w3c/sdw#830]
[Entry "Dimension (geometry)"](http://w3c.github.io/sdw/bp/#dfn-dimension-geometry) currently reads as follows:

> Dimension (geometry): In physics and mathematics, the dimension of a mathematical space (or object) is informally defined (see Wikipedia entry as the minimum number of coordinates needed to specify any point within it. Thus, a point has no dimension (0D) as there is no inside, whereas a line has a dimension of one (1D) because only one coordinate is needed to specify a point along it – for example, the point at 5 on a number line. A surface such as a plane or the surface of a cylinder, torus or sphere has a dimension of two (2D) because two coordinates are needed to specify a point on it – for example, both a latitude and longitude are required to locate a point on the surface of a sphere. The inside of a cube, cylinder, torus or sphere is three-dimensional (3D) because three coordinates are needed to locate a point within these spaces. For a formal rigorous mathematical definition see the ISO definition. [ISO-19107]

There may be a typo in "(see Wikipedia entry", since the parenthesis is not closed.

Also, when referring to [the relevant Wikipedia entry](https://en.wikipedia.org/w/index.php?title=Dimension&oldid=775064678), it must be taken into account that the text in the BP entry does not completely match, since it was modified to add a sentence on 0D geometries (the relevant sentence: "a point has no dimension (0D) as there is no inside, whereas").

The text of the entry in Wikipedia:

> In physics and mathematics, the dimension of a mathematical space (or object) is informally defined as the minimum number of coordinates needed to specify any point within it.[1][2] Thus a line has a dimension of one because only one coordinate is needed to specify a point on it – for example, the point at 5 on a number line. A surface such as a plane or the surface of a cylinder or sphere has a dimension of two because two coordinates are needed to specify a point on it – for example, both a latitude and longitude are required to locate a point on the surface of a sphere. The inside of a cube, a cylinder or a sphere is three-dimensional because three coordinates are needed to locate a point within these spaces.

**Comment by 6a6d74** [comment]
@lvdbrink - let's discuss this one tomorrow during our catch up.

**Comment by 6a6d74** [comment]
Having discussed the inconsistency (re. the '0D' addition) @lvdbrink and I are happy to keep the definition as it is.

parenthesis is now closed.
