### ISSUE TITLE
BP1: Proposed revision to note with Geonames example

### ISSUE THREAD

**Issue by andrea-perego** [w3c/sdw#832]
The relevant text:

> While there is a cost to this conflation, problems can be mitigated by avoiding making statements that confuse spatial thing and the page/document, such as “Uluru is available in KML format”; e.g. <http://sws.geonames.org/7645281/> dc:hasFormat ex:kml .

I suggest the following revisions:
- `dc:hasFormat` should be replaced with `dct:hasFormat`: `dc:hasFormat` is supposed to have a literal as value, and not a URI reference
- `ex:kml` could be replaced with the URL of the actual KML representation available from geonames: http://www.geonames.org/kml/-25.34434_131.03282_15.kml . This would provide a working example

Proposed revision below:

````html
<p>While there is a cost to this conflation, problems can be mitigated by avoiding
 making statements that confuse <a>spatial thing</a> and the page/document, 
such as “Uluru is available in KML format”; e.g. <code>&lt;</code><a 
href="http://sws.geonames.org/7645281/"><code>http://sws.geonames.org/7645281/</code></a><code>&gt; dct:hasFormat &lt;</code><a 
href="http://www.geonames.org/kml/-25.34434_131.03282_15.kml"><code>http://www.geonames.org/kml/-25.34434_131.03282_15.kml</code></a><code>&gt; .</code>
</p>
````

**Comment by 6a6d74** [comment]
Good spot @andrea-perego - change applied!
