### ISSUE TITLE
BP: Namespaces missing from namespace table

### ISSUE THREAD

**Issue by andrea-perego** [w3c/sdw#848]
- `georss`(http://www.georss.org/georss/) which is used in [Example 21](ex-anne-frank-building-centroid-and-bbox) (BP13) and in [the table of spatial vocabularies](http://w3c.github.io/sdw/bp/#table-vocabs-matrix) in Appendix A (column about GeoRSS).
- `sf` (http://www.opengis.net/ont/sf#) which is used in [the table of spatial vocabularies](http://w3c.github.io/sdw/bp/#table-vocabs-matrix) in Appendix A (column about GeoSPARQL).

**Comment by lvdbrink** [comment]
Added in #851
