### ISSUE TITLE
BP: Possible revision to Ack section

### ISSUE THREAD

**Issue by andrea-perego** [w3c/sdw#858]
Just a suggestion, but I wonder whether we should consider following the structure of the [DWBP's Acknowledgements section](https://www.w3.org/TR/dwbp/#acknowledgements). The structure is roughly as follows:
- ack to SDW WG members (and possibly specific members)
- ack to DWBP WG, and to specific DWBP WG members who provided output
- ack to all others (who are neither SDW nor DWBP WG members)
- ack to chairs and team contacts

A possible revision to the [current SDWBP ack section](http://w3c.github.io/sdw/bp/#acknowledgments) could be the following:

> The editors gratefully acknowledge the contributions made to this document by all members of the working group. [Especially,  the contributions received from A, B, C...]
> 
> This document would not have been possible without the tremendous efforts of the Data on the Web Working Group; their [DWBP] provides the essential underpinnings for our own work. Special thanks are due to Newton Calegari, Riccardo Albertoni, Annette Grainer, Antoine Isaac, and Eric Stephan.
> 
> The editors would also like to thank comments received from Ig Ibert Bittencourt, Marco Brattinga, Martin Desruisseaux, Neil McNaughton, Simeon Nedkov, James Passmore, Stefan Proell, Maik Riechert and Erik Wilde.

NB: Some of the people above may be DWBP members - need to ask @philarcher1 to check

> The editors also gratefully acknowledge the chairs of this Working Group: Ed Parsons and Kerry Taylor — and staff contacts Phil Archer and François Daoust.

**Comment by 6a6d74** [comment]
Hi @andrea-perego - let's bottom this out at the BP sub-group call ... 

Any changes will only be editorial - so I'm not worried about making them before the freeze.

BTW: I already tried to follow the pattern from DWBP!

**Comment by andrea-perego** [comment]
Agreed.

**Comment by andrea-perego** [comment]
Only a note. The current text of the ack section includes an unfinished sentence:

> The editors would also like to thank comments received from .

**Comment by 6a6d74** [comment]
Oh yes- my mistake. That's covered in the first paragraph :-)

**Comment by 6a6d74** [comment]
Closing. This is fixed now.
