### ISSUE TITLE
Complete BP 1 Use globally unique identifiers for entity-level resources

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#86]
Including: 
- discussion on ‘punning’ to allow conflation of concerns? ref @timbl’s statement about vCard; ref URIs in data primer for direct and shorthand properties?
- discussion on identification of coverages as a property of a Thing
- how to mint the identifier yourself based on the features in your dataset and how the identifier is for the real  world thing the feature describes.

**Comment by lvdbrink** [comment]
Also, the section explaining Spatial Things and information resources could use a picture explaining the concept using the lighthouse example.

**Comment by lvdbrink** [comment]
The Possible Approach to Implementation section needs to be completed based on the list (punning, ids for coverages, minting idenfiers yourself) and other approaches; the How to Test section can be completed after the approaches are clear.

**Comment by lvdbrink** [comment]
This is no longer BP1 but [BP7](http://w3c.github.io/sdw/bp/#globally-unique-ids).

**Comment by 6a6d74** [comment]
These sections are now completed. See [this](https://github.com/w3c/sdw/commit/19d68c7895d90ab83fe5b387cf3d977987a7c760) commit.
