### ISSUE TITLE
BP: namespace section limited to RDF namespaces?

### ISSUE THREAD

**Issue by cportele** [w3c/sdw#869]
The namespace section introduced with PR #828 is misleading. It lists for the prefix "gml" the namespace IRI "http://www.opengis.net/ont/gml#" and claims that this namespace would be defined in the GML standard. This is incorrect.  

Almost everyone dealing with GML data or schemas would expect "http://www.opengis.net/gml/3.2" (or "http://www.opengis.net/gml") as the namespace IRI as it is defined in the GML standard. The prefix "gml" is used in the document as the abbreviation for "http://www.opengis.net/gml/3.2" at least in examples 15/16/29. The current section 5 seems to use the term "namespace" with an RDFS bias.

It is GeoSPARQL that specifies "http://www.opengis.net/ont/gml#" and uses "gml" as the abbreviation.

Possible solutions:
* split "5 namespaces" into two sections "5.1 RDF namespaces" and "5.2 XML namespaces" (the prefix "gml" would occur in both);
* list both the RDF and XML namespaces in the table in section 5, but clearly identify them.

My preference would be the first option to separate the different types of usages of the term "namespace".

Note that other XML namespace prefixes are used in the document, too. At least: "georss", "bag", "wml2", "xlink", "sam", "sams".

**Comment by 6a6d74** [comment]
Good point. This should be easy to do.

I may be able to queue up a PR with this change- but would be happy for
someone else to do it :-)

**Comment by cportele** [comment]
@6a6d74 thanks. I will prepare the PR and we decide on it in the call on Wednesday.

**Comment by 6a6d74** [comment]
Thanks @cportele - very helpful :-)

**Comment by andrea-perego** [comment]
@cportele , note that also `bag` and `georss` are used in the BP doc for RDF terms, so they should appear in both tables.

**Comment by cportele** [comment]
thanks @andrea-perego - I was just searching the document, whether also "Geo OWL" was used in the document :)

**Comment by lieberjosh** [comment]
The GeoSPARQL 1.0 schema is located at both http://www.opengis.net/ont/gml <http://www.opengis.net/ont/gml> and http://www.opengis.net/ont/geosparql <http://www.opengis.net/ont/geosparql> (redirects to http://schemas.opengis.net/geosparql/1.0/geosparql_vocab_all.rdf <http://schemas.opengis.net/geosparql/1.0/geosparql_vocab_all.rdf>), the internal prefix for both is “geo”. The GML namespace http://www.opengis.net/gml <http://www.opengis.net/gml> redirects to http://schemas.opengis.net/gml/3.1.1/base/gml.xsd

The georss namespace is the same for both xml and owl versions, though the internal prefix for the xml schema is georss and for the owl ontology is geo. Dereferencing the namespace URI (will) lead to a selection page.

I agree that we could use two tables, but it will be hard to be authoritatively unique about namespace prefixes. They’ve just been reused too much and were never intended to be characteristic (hence — namespaces).

—Josh

**Comment by andrea-perego** [comment]
@lieberjosh , @cportele , @6a6d74 ,

Probably we can just fix this problem by minting different prefixes when the namespace URI is different (as we did with `w3cgeo` and `geosparql` to address that prefix collision).

If I'm not mistaken, `gml` is used just once for `http://www.opengis.net/ont/gml#` ([Example 17](http://w3c.github.io/sdw/bp/#ex-anne-frank-building-rdf)). So, let's replace it with a new one.

We can do the same with `bag` - need to check whether the XML and RDF namespace URIs are different.

About `georss`, we shouldn't have this problem, but I see that, in the namespace table, the namespace URI is missing a trailing slash.

**Comment by andrea-perego** [comment]
Just realised we are using two different prefixes for the same namespace URI:
- `dc` &rarr; http://purl.org/dc/terms/
- `dct` &rarr; http://purl.org/dc/terms/

`dc:` is used only in Example 26. So, unless there's a reason to keep it, we can replace `dc:` with `dct:`, and remove the `dc` row from the namespace table.

**Comment by cportele** [comment]
That would be another option. Although I do see a benefit for separating it as an RDF namespace works differently from an XML namespace (at least, if another RDF encoding than RDF-XML is used and we use TTL in our examples).

The GeoRSS XML namespace is different from the RDF one, at least the GeoRSS spec in the bibliography references http://www.georss.org/xml/1.1/georss.xsd which uses http://www.georss.org/georss/10.

The "bag" namespaces are completely different.  

I have just created a PR with two tables (https://github.com/w3c/sdw/pull/870), but a single table is fine for me, too, if we create unique entries for each of the currently used "gml", "georss" and "bag" prefixes and add the "sam", "sams", "wml2" prefixes.

**Comment by lieberjosh** [comment]
The GeoRSS namespace will be uniformly http://www.georss.org/georss <http://www.georss.org/georss/10> when Raj gets around to merging my changes.

**Comment by cportele** [comment]
@lieberjosh But the SDW BP document uses https://www.w3.org/2005/Incubator/geo/XGR-geo/ for GeoRSS and that references http://www.georss.org/georss/10. Or will that be changed silently, too? Or should another GeoRSS spec document be referenced?

If the "/10" would be dropped, there would still be the difference of the trailing slash (in RDF) or without it (in other XML)?

**Comment by 6a6d74** [comment]
@andrea-perego... I also spotted the dc: & dct: duplication ... and there's
dcterms: too

It's not a big problem; the RDFa Initial Context uses _both_ dc: and
dcterms:

Feel free to track down the offending prefixes in the examples if you would
like to slim down the prefix list!

Jeremy

**Comment by andrea-perego** [comment]
>
> That would be another option. Although I do see a benefit for separating
> it as an RDF namespace works differently from an XML namespace (at least,
> if another RDF encoding than RDF-XML is used and we use TTL in our
> examples).
>

+1 from me to having two tables. But, to avoid ambiguity, I think we'd
better use unique prefixes irrespective of whether they are XML or RDF.

**Comment by andrea-perego** [comment]
>
> @andrea-perego... I also spotted the dc: & dct: duplication ... and there's
> dcterms: too
>
> It's not a big problem; the RDFa Initial Context uses _both_ dc: and
> dcterms:
>
> Feel free to track down the offending prefixes in the examples if you would
> like to slim down the prefix list!
>

Agreed. I'll do.

**Comment by lieberjosh** [comment]
I don’t think it’s possible at this point to chance the Geo Incubator report, which was just a report. The description of the OWL realization is also at georss.org <http://georss.org/> and copied I believe in the Community Standard, which I am able to influence, but is not yet approved.

The trailing slash distinction is a curious one. Hadn’t really thought about it before. Of course, XML uses namespaces for scoping, not as a shorthand for making URI's, so I don’t think there is any problem with using a trailing slash for XML. It just isn’t a practice. If you look in the GeoRSS OWL file, Chris Goad actually created ENTITIES without the slash, then added a slash or hash in the ontology to make namespaces.

—Josh

**Comment by andrea-perego** [comment]
>> @andrea-perego... I also spotted the dc: & dct: duplication ... and
>> there's
>> dcterms: too
>>
>> It's not a big problem; the RDFa Initial Context uses _both_ dc: and
>> dcterms:
>>
>> Feel free to track down the offending prefixes in the examples if you
>> would
>> like to slim down the prefix list!
>
> Agreed. I'll do.

Done - see #871

I replaced dc: and dct: with dcterms:

I haven't touched the namespace table, so the entries for dc and dct
are still there.
