### ISSUE TITLE
BP: Add @id to all examples

### ISSUE THREAD

**Issue by andrea-perego** [w3c/sdw#873]
This would be useful to allow BP examples be referred to (via fragment identifiers), also from external documents.

**Comment by 6a6d74** [comment]
@andrea-perego - this seems like a sensible suggestion. Purely editorial; so we can make the change at any time. It won't materially change the "vote" (either WG or TC vote).

**Comment by 6a6d74** [comment]
Closing - IDs are now included in all examples
