### ISSUE TITLE
Add clarification about metadata API 

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#880]
@andrea-perego 

> I wonder whether it would be useful to add a note in BP12, at the end of the "Why" section, explaining that BP12 is about APIs for "data" only, whereas, as far as metadata are concerned, the relevant BP is BP13.

@cportele 

> no problem with that. I think I would add this early in the section 12.3 "spatial data access" as the note applies to the whole section. As it is an informative edit I think we could always do this in the next iteration, too.

We agree in SDW BP call 10-May to apply this editorial change

**Comment by cportele** [comment]
Added the following note:

"This section is about APIs for access to spatial data. This includes access to metadata that is shared with the dataset. Access to metadata that is published separately in catalogs is covered in Best Practice 13: Include spatial metadata in dataset metadata."

**Comment by andrea-perego** [comment]
On Thu, Jun 1, 2017 at 4:13 PM, Clemens Portele <notifications@github.com>
wrote:

> Added the following note:
>
> "This section is about APIs for access to spatial data. This includes
> access to metadata that is shared with the dataset. Access to metadata that
> is published separately in catalogs is covered in Best Practice 13: Include
> spatial metadata in dataset metadata."
>

+1 from me. Thanks, @cportele .
