### ISSUE TITLE
BP: Rendering issues in Appendix B

### ISSUE THREAD

**Issue by andrea-perego** [w3c/sdw#882]
In the first table of [Appendix B](https://www.w3.org/TR/2017/NOTE-sdw-bp-20170511/#BP_Benefits), some cells in the 2nd column include a number of empty &lt;li&gt;&lt;/li&gt; elements which are rendered as bullet points.

The problem seems to concern just the document in TR space, and not the one on github.io.

**Comment by lvdbrink** [comment]
I don't see any empty list item elements in the document (not in the [May 11 Note][1] nor the Editor's draft). 

Maybe it was a temporary problem. The Benefits table is generated with javascript, there was something wrong with it for a while. 

[1]: https://www.w3.org/TR/2017/NOTE-sdw-bp-20170511/

**Comment by tidoust** [comment]
I'll take the liberty to close the issue. I confirm that this was triggered by a script that should not have been published along with the document. This got fixed mid-June.
