### ISSUE TITLE
description of time zone

### ISSUE THREAD

**Issue by aphillips** [w3c/sdw#885]
Reference: http://w3c.github.io/sdw/time/#time:TimeZone

>    A Time Zone is a geographic region that uses a clock with a specified offset from UTC. The region and offset are specified by the locally recognised governing authority.

This is not quite complete. A time zone for a specified region includes rules for changes to the offset, both historical and for future changes (pending updates). This should reference each of these.

**Comment by dr-shorthair** [comment]
Hmm. I had intended to allow the same geographic region to correspond to different time-zones, at different times of the year, or different years (I lived in Western Australia for 19 years, of which only four had daylight savings - an experiment subsequently abandoned!). 

As mentioned in the text we do *not* provide a model for time-zones, just a slot where a link to a time-zone description can be included. 

Will try to rephrase.

**Comment by dr-shorthair** [comment]
Have refined the description of the TimeZone class as follows: 

> A Time Zone specifies the amount by which the local time is offset from UTC. A time zone is usually denoted geographically (e.g. Australian Eastern Daylight Time), with a constant value in a given region. The region where it applies and the offset from UTC are specified by a locally recognised governing authority.
> 
> NOTE
> Designated timezones are associated with a geographic region. However, for a particular region the offset from UTC often varies seasonally, and the date of the change varies from year to year. In these cases the timezone designation changes for the different seasons. Furthermore, the offset may change over longer timescales, though the designation might not.

**Comment by dr-shorthair** [comment]
Will add a reference to http://www.w3.org/TR/timezone/ - thanks

**Comment by dr-shorthair** [comment]
@aphillips Please see second note here http://w3c.github.io/sdw/time/#time:TimeZone 
OK now?

**Comment by aphillips** [comment]
Works for me. Thanks!
