### ISSUE TITLE
should generalYear (etc) be gregorianYear (etc)?

### ISSUE THREAD

**Issue by aphillips** [w3c/sdw#888]
https://github.com/w3c/i18n-activity/issues/404

http://w3c.github.io/sdw/time/#time:generalYear

The name for `generalDay`/`generalMonth`/`generalYear` appear to think that the 'g' in `gDay`/`gMonth`/`gYear` in XML Schema stands for "general", but it is my impression that the 'g' actually intended to stand for Gregorian. There are actually health warnings in XML Schema to the effect that, due to the linkage to the Gregorian calendar, these values may not be convertible to other calendar systems.

**Comment by dr-shorthair** [comment]
No - it was understood that gYear / gMonth / gDay indicate 'gregorian'. The intention of the new classes is precisely to generalize Year / Month / Day by removing the implication that they are in the Gregorian Calendar. That is the major point of this revision of OWL-Time. 

The descriptions of generalYear / generalMonth / generalDay http://w3c.github.io/sdw/time/#Datatypes were intended to indicate this. I've re-written slightly to help - is this better now?

**Comment by dr-shorthair** [comment]
So the answer to the headline question in the subject of this issue is 'no'. generalYear is _not_ Gregorian, gYear is Gregorian and generalYear is more general.

**Comment by aphillips** [comment]
I see what you're trying to do. You might want to make this even more explicit?

I don't see a way to associate "general" month/day/year values with a specific calendar? Having a `gMonth` == `14` doesn't really tell me anything without knowledge of the calendar.

As an aside (and perhaps it should be a separate, new issue) but I note that your `gYear` is limited for 4 digits, while some calendars need 5 digits (and all calendars will someday--but not soon--need it) cf. https://en.wikipedia.org/wiki/Calendar_era

I also notice that you don't have a concept of era, by which I do *not* mean "archaeological era" e.g. Paleozoic etc. but rather the calendric era. The ISO/Gregorian calendar uses two eras, for example: CE (aka "AD") and BCE (aka "BC"). The Japanese Imperial calendar has a number of eras related to the various reigns of emperors, etc. The ability to use *general* year values would probably depend on the ability to represent what calendar is in use and which era within that calendar.

Please consider reopening this (I18N does not re-open issues on our own)

**Comment by chris-little** [comment]
@aphillips The intent of the revised Time Ontology was to enable temporal reasoning about instants, intervals and durations. It was also intended to _support_ the definition of other calendars, without losing backward compability with the previous, Gregorian calendar only, version of the ontology. It was not intended to define those other calendars, or any calendric specific framework that they may fit into.

Eras that you mention could be built using the general constructs.

If you wish to have an ontology with specific support for other calendars, that seems to me a different issue. I do not think it appropriate to re-open this closed issue.
