### ISSUE TITLE
non-standard time zone reference

### ISSUE THREAD

**Issue by aphillips** [w3c/sdw#890]
http://w3c.github.io/sdw/time/#dtd-vs-dt

The time zone in the example does not use the IANA identifiers, ostensibly because the only online linked data representation that the authors found was the dateandtime.com site. I'm concerned that this is not a reliable standard (or any kind of standard, fwiw). It would be better to actually use the authoritative IANA registry instead. If that is not available in a Linked Data format, the development of such a standard would not be impossible. Making dateandtime.com the reference (and particularly using the zone abbreviations, which are known to be problematic) is something that should be carefully considered before making it a "best practice"

**Comment by andrea-perego** [comment]
Just wondering whether [the corresponding IANA entries in dbpedia.org](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) could be an option.

E.g.: http://dbpedia.org/resource/Australia/Sydney

**Comment by dr-shorthair** [comment]
The phrase 'best practice' is too strong. The intention was to note that timeanddate offers a linked-data resource (one URI per timezone). @andrea-perego has drawn our attention to another - though still clealry non-normative. I would propose to also add a reference to to the dbpedia resource in the green note, and make the note descriptive rather than prescriptive.

**Comment by dr-shorthair** [comment]
Have added the following note to time:timeZone

> IETF and IANA each provide a database of timezones. These are well maintained an authoritative, but individual items are not available at individual URIs, i.e. not as "Linked Data", so cannot be used directly in data expressed using OWL-Time.
> 
> DBPedia provides a set of resources corresponding to the IANA timezones, with a URI for each. The World Clock service also provides a list of time zones with the description of each available as an individual webpage with a convenient individual URI (e.g. https://www.timeanddate.com/time/zones/acwst). Any of these can be used as the value of the time:timeZone property.

**Comment by r12a** [comment]
maintained an -> maintained and

Any of these -> Either of these / These or similar resources (?)

**Comment by chris-little** [comment]
I am happy with the re-written note. We did discuss this issue, and the lack of authoritative Linked Data from IANA, IETF and ISO, last year. The closed issues on the W3C Spatial Data on the Web WG Tracker were #63 and #127.

**Comment by dr-shorthair** [comment]
However, I think the IANA 'tz' database gives just one name (e.g. Australia/Melbourne) for both standard _and_ daylight time. So if the timezone designator is http://dbpedia.org/page/Australia/Melbourne then we still don't know what the offset is without also knowing what the rule for that year is.

**Comment by aphillips** [comment]
@dr-shorthair The IANA 'tz' database correctly models how time zones work---which is complicated. You are correct that it gives an unambiguous name to each zone. The offset *necessarily* depends on the epoch time being converted to wall time. If you only use offsets, you will get into trouble with past (or future) time values. The short names (e.g. "AEST") are language dependent and have conflicts. The longer names (Pacific Time) depend on language (they are generally localized). And the specific offset rules for a given zone change based on jurisdictional preference.

Just using local time offset (LTO) to represent time zone can cause problems. See for examples and use cases our document https://www.org/TR/timezone

**Comment by dr-shorthair** [comment]
See revised note here: http://w3c.github.io/sdw/time/#time:timeZone 
OK @aphillips ?

**Comment by aphillips** [comment]
I would suggest two changes:

> IETF and IANA each provide a database of timezones. 

The IETF publishes RFCs (the rules, the constistution if you will). IANA hosts the registry. So it would be more correct to say:

> IANA maintains a databate of timezones.

This one:

> These or similar resources can be used as the value of the time:timeZone property.

... still seems overly prescriptive to me. Perhaps:

> These or other, similar, resources might be used as a value of the `time:timeZone` property.

Otherwise looks good to me. (Someone ought to write an RFC so that the tzinfo database _is_ represented by URLs......)

**Comment by dr-shorthair** [comment]
Thanks. Done (database rather than databate :-) ).

**Comment by tidoust** [comment]
I'm closing this issue: change was applied, and spec was published as Candidate Recommendation.
