### ISSUE TITLE
Metadata on the object in SSN

### ISSUE THREAD

**Issue by dhvenema** [w3c/sdw#892]
I have been following the SSN developments for the last couple of months and I have not found much on metadata of physical objects in SSN. Has any work been done on metadata (e.g. the owner, operator or sensor-type) on physical objects, such as the sensor, actuator, sampler or platform? What would be the best approach to incorporate said metadata in SSN?

Any insight is greatly appreciated.

**Comment by maximelefrancois86** [comment]
Hello,

Thank you for your comment, could you please elaborate a bit more and send your comment directly at the following email address:

public-sdw-comments@w3.org 

That way we will be able to address it officially.

Kind regards,
Maxime
