### ISSUE TITLE
SSN Doc: We will need a new fig 1.

### ISSUE THREAD

**Issue by kjano** [w3c/sdw#897]
Before we forget about this. We will need a new fig 1 for the new horizontal module.

**Comment by maximelefrancois86** [comment]
It this still topical ?

**Comment by tidoust** [comment]
I'd like to make sure that all issues have been addressed before requesting transition to Proposed Recommendation. Can this be closed without further ado, @kjano ?

**Comment by kjano** [comment]
Yes
