### ISSUE TITLE
SSN Doc: 'appartment' should be 'apartment'

### ISSUE THREAD

**Issue by BillSwirrl** [w3c/sdw#908]
http://w3c.github.io/sdw/ssn/#appartment-134 

Very minor: normal English spelling is 'apartment'

**Comment by maximelefrancois86** [comment]
Thank you. I'll correct these mistakes soon...
As examples are not part of normative sections, we've been told we can make some corrections  and add more examples after the document has become a Candidate REC.

**Comment by maximelefrancois86** [comment]
Armin fixed this in pull request #911 .
Thanks again
