### ISSUE TITLE
Parse error in  sdw/ssn/integrated/examples/dht22.ttl

### ISSUE THREAD

**Issue by lmedini** [w3c/sdw#942]
Hi,

There seems to be a missing / unneeded prefix in dht22.ttl.

My parser returns: "Error: Undefined prefix "ex:" at line 108." and the ex prefix is actually not defined. Is it needed?

Thanks,

Lionel.

**Comment by maximelefrancois86** [comment]
Thank you !
See https://github.com/w3c/sdw/commit/e99eac53aa100623fb7fa3881f362b468b6dec6e
