### ISSUE TITLE
Parse error for  sdw/ssn/integrated/examples/seismograph.ttl

### ISSUE THREAD

**Issue by lmedini** [w3c/sdw#944]
Hello,

When parsing this file, my parser returns "Error: Expected predicate to follow "http://example.org/data/VCAB-DP1-BP-40#location" at line 47."

Works well when replacing the final semicolon with a dot.

Thanks,

Lionel.

**Comment by arminhaller** [comment]
Fixed in: https://github.com/w3c/sdw/pull/963
