### ISSUE TITLE
Minor inconsistency in use of "non normative" flags

### ISSUE THREAD

**Issue by tidoust** [w3c/sdw#958]
[Section 6](https://w3c.github.io/sdw/ssn/#VerticalSegmentation) is flagged as "non normative". All subsections also have that flag, except [6.3 O&M Alignment Module](https://w3c.github.io/sdw/ssn/#OM_Alignment).

We should either remove "non normative" flags from sub-sections (by definition, if a section is non normative, then all its sub-sections are, as well), or also flag 6.3 as non-normative.

**Comment by arminhaller** [comment]
Fixed in https://github.com/w3c/sdw/pull/959. Section 6 is now normative since 6.3 is a normative section and should remain so.
