### ISSUE TITLE
Gregorian Time example served with incorrect character encoding

### ISSUE THREAD

**Issue by edent** [w3c/sdw#961]
The example (https://www.w3.org/ns/time/gregorian) linked from https://www.w3.org/TR/2017/CR-owl-time-20170606/ appears to be served with an incorrect encoding:

![screen shot 2017-08-29 at 10 45 24](https://user-images.githubusercontent.com/837136/29815039-34d14038-8ca7-11e7-9d02-f99ab8a6bb09.png)

They should be displayed as

```
  skos:prefLabel "4月"@ja ;
  skos:prefLabel "4月"@zh ;
  skos:prefLabel "Abril"@es ;
  skos:prefLabel "Abril"@pt ;
  skos:prefLabel "April"@de ;
  skos:prefLabel "April"@en ;
  skos:prefLabel "April"@nl ;
  skos:prefLabel "Aprile"@it ;
  skos:prefLabel "Avril"@fr ;
  skos:prefLabel "Kwiecień"@pl ;
  skos:prefLabel "Апрель"@ru ;
  skos:prefLabel "أبريل"@ar ;
  time:month "--04"^^xsd:gMonth ;
  time:unitType time:unitMonth ;
```

Character encoding appears to be correct on https://www.w3.org/2006/time

**Comment by ylafon** [comment]
Now served using a proper charset.
