### ISSUE TITLE
SSN: The 2nd Observation1 should be Observation2 in Example 4 & 5, correct?

### ISSUE THREAD

**Issue by kjano** [w3c/sdw#974]
@arminhaller , @dr-shorthair  The 2nd Observation/1 should be Observation/2 in Example 4 & 5, correct?

**Comment by maximelefrancois86** [comment]
Yes, my bad. 
Can you please change this?

**Comment by kjano** [comment]
Sure, thanks for the prompt confirmation.

**Comment by tidoust** [comment]
Fixed by #975
