### ISSUE TITLE
Typo in Example 10: sosa:hasSimplResult true ;

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c/sdw#977]
Found typo in Example 10 Apartment 134

> sosa:hasSimplResult true ;

Sholud be

> sosa:hasSimpleResult "true" ;

**Comment by kjano** [comment]
@GeorgFerdinandSchneider Thanks for spotting

**Comment by tidoust** [comment]
I'm reopening this issue because the typo exists in the published Recommendation and so we should add an entry to the errata document accordingly (a bit tedious for such a typo, I know).

**Comment by tidoust** [comment]
[Entry 9](https://www.w3.org/2017/10/vocab-ssn-errata.html#entry-9) added to errata doc
