### ISSUE TITLE
Typos in B.5 Seismograph

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c/sdw#979]
Hi!

This relates to issue  #944

The displayed example in example B.5 is invalid turtle syntax.

> <VCAB-DP1-BP-40#location> rdf:type sosa:FeatureOfInterest ;
>   rdfs:label "location of VCAB-DP1-BP-40"@en ;
>   geo:lat 35.8648067 ;
 >  geo:long -120.6195831 ;
 >  geo:alt 12.75 ;
 >  sosa:isSampleOf <earth> .

There are "" missing for the literals.

Also this should end with a dot.

> <VCAB-DP1-BP-40#location> ssn:hasProperty <VCAB-DP1-BP-40#groundDisplacementSpeed> ;

Checked with [http://ttl.summerofcode.be/](http://ttl.summerofcode.be/)

Best

**Comment by tidoust** [comment]
@GeorgFerdinandSchneider Thanks for the report.

> There are "" missing for the literals.

I'm not sure I understand the problem there. Also, that error does not get reported when I check the example with the validator you mention...

> Also this should end with a dot.

Duly noted. We'll have to publish this as a separate erratum to the spec, I'm afraid, as there is no easy way to update the contents of a Recommendation once it has been published. I'm about to send a pull request to fix it in the Editor's Draft.

**Comment by GeorgFerdinandSchneider** [comment]
@tidoust thanks for your answer. Correct there is no typos in the literals.

However, the typo remains in :

> <VCAB-DP1-BP-40#location> ssn:hasProperty <VCAB-DP1-BP-40#groundDisplacementSpeed> ;

**Comment by tidoust** [comment]
Closing this issue:
- The typo was fixed in the Editor's Draft, see [B.5 Seismographs](https://w3c.github.io/sdw/ssn/#seismograph)
- An entry was added to the Errata document for the published Recommendation, see [Syntax error in Seismographs example](https://www.w3.org/2017/10/vocab-ssn-errata.html#entry-1)
