### ISSUE TITLE
Delete branches that are no longer needed

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw#983]
The repository currently has about 100 branches. This makes for a rather unpleasant experience when trying to work with the repo. It look like folk were not particularly diligent about deleting ones that had already been merged, or maybe didn't understand that this was good practice. 

Many of the branches have the contributor's name embedded in the branch name so it looks like @lvdbrink @arminhaller @BillSwirrl @PBarnaghi @6a6d74 @cportele @danhlephuoc @KerryLea @kjano @maximelefrancois86 are responsible for a lot of them. Deleting a branch does not mean it it is unrecoverable, but it does help tidy up the UI a bit. So maybe the branch initators could spend 10 minutes deleting the ones that are no longer required.

**Comment by lvdbrink** [comment]
Right you are. Mine now deleted!

**Comment by BillSwirrl** [comment]
good point Simon - done mine

**Comment by dr-shorthair** [comment]
Thanks @lvdbrink . @BillSwirrl yours are still there?

**Comment by cportele** [comment]
My branches have already been deleted.

**Comment by maximelefrancois86** [comment]
Deleted all stale, merged, and closed branches.
