### ISSUE TITLE
Representation of a generic time of day in the W3C Time Ontology

### ISSUE THREAD

**Issue by ElisaKendall** [w3c/sdw#988]
Given that xsd:time is not an allowable XML Schema Datatype in OWL 2, how would you represent the equivalent time using the ontology.  

For example, for provenance related to market valuation of financial instruments, certain sources for reference data (e.g., https://www.federalreserve.gov/releases/h15/) are revised daily at a specific time of day that is well known in the industry.  It is the same time of day, in this case, 4:15 pm Eastern time (Washington, D.C.), every week day that is not a U.S. national holiday.  Other benchmarks, including the closing time of various markets internationally, are similar in nature - a specific time of day on every business day that is not a holiday in that market, or not the day before or after a holiday that occurs on a weekend, depending on the rules for the jurisdiction.

**Comment by dr-shorthair** [comment]
As you note, while it is handled fine by the XSD datatype, but there is no class in the OWL-Time ontology which represents a recurring instant. SO I would say that a recurring instant is not in scope for OWL-Time.

**Comment by chris-little** [comment]
This example could be a useful Use Case for the SDW Interest Group Best Practice on publishing Statistical Data on the Web activity.

**Comment by ElisaKendall** [comment]
Hi Simon,
See my comment on #987 - it's underspecified, and the list of _**allowable**_ XML Schema Datatypes in OWL 2 does not include it.  There are certainly RDF tools that support it, and many of them do not care about OWL 2 reasoning.  Most RDF users don't care, either, which is why the original ontology had significant uptake and likely will continue to do so.  Having said this, because it's not in the list of supported types, the behavior of OWL 2 tools with respect to these types is not predictable.  Some of us who would like to use OWL Time, but are not reasoner developers, can't use it as a result.

**Comment by dr-shorthair** [comment]
Closed by resolution of SDWIG f2f - Lyon TPAB - 2018-10-23

RESOLUTION: Re. #988, it introduces a useful requirement to introduce recurring instants, but addition to the OWL Time ontology would require re-chartering the group. The Interest Group is not planning on working on this feature for now, but would welcome an extension proposal.

https://www.w3.org/2018/10/23-sdw-minutes.html#x09
