### ISSUE TITLE
Updates to SDW Interest Group home page

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#990]
Currently the Spatial Data on the Web Interest Group (SDW IG) home page is hosted on the W3 site here: https://www.w3.org/2017/sdwig/ 

Only W3C staff contacts can edit this page (thank you @tidoust for your efforts so far!) which is a pain when we want to advertise new meetings, publish the agenda, minutes etc.

So we agreed at the Plenary teleconference that we would move the SDW IG home page to the github repository, published using GH pages.

ACTION on Jeremy Tandy (me!) to do this, with the proposal to use Markdown (and the Jekyll static site generator integrated into GitHub) to make it easy to publish updates.

**Comment by 6a6d74** [comment]
Having looked again to use of Markdown and Jekyll to publish the home page, I think that we wouldn't get a great deal of benefit from the effort of migrating the content on the existing home page. 

Markdown and Jekyll works well if you have a bunch of pages to manage, but we only have one page at the moment.

So I propose to move the existing home page to gh-pages, merging it with the existing information already there. This will be a HTML page, which is still pretty easy to update when we want to publish new meeting agendas and minutes.

For now, I suggest that we continue to send the meeting agendas to the IG mailing list (we don't need to publish twice!) and reference those emails via their URL. Minutes are also automatically published via a URL (which we could use) or link to the email post that advertises the availability of those minutes. 

There's nothing precluding that we renovate the gh-pages site later to use Markdown and Jekyll. I just think that we wouldn't get a great benefit at the moment. And seeing as "agile" is fashionable (!) I'll do the minimum for now to meet the requirements we actually have - which is to release @tidoust from the only person able to update the home page.

For each of the projects, we can use the GitHub wiki and/or markdown pages within the individual project repositories / folders to publish working documents.

**Comment by ghost** [comment]
I know it’s all very last century but we did make use of the wiki for this type of content previously ?

**Comment by 6a6d74** [comment]
See proposed version at: http://w3c.github.io/sdw/sdwig-homepage.html

**Comment by tidoust** [comment]
The page looks good but I would overwrite the [`index.html`](http://w3c.github.io/sdw/sdwig-homepage.html) page of the repository, instead of creating a separate page. Any reason not to?

**Comment by tidoust** [comment]
See PR #992 for minor adjustments and move to `index.html`.

**Comment by 6a6d74** [comment]
@tidoust ... I agree: `index.html` is better. I didn’t want to overwrite the existing page until the group were happy.

@edpars0ns, yes we did use the W3C wiki for this previously - kind of a default assumption to use it for the Working Group. We’ve seen a continual shift of W3C work into GitHub since the WG was spun up. Linda & I are trying to keep all of our information in one place. It’s no biggie at the moment; we’lol continue to monitor what we want to use the home page for and will evolve to suit.

**Comment by 6a6d74** [comment]
@tidoust ... PR #992 merged in. Thank you.

**Comment by akuckartz** [comment]
@6a6d74 Why is this issue still open?

**Comment by chris-little** [comment]
because we have too much stuff to do!
