### ISSUE TITLE
Get feedback on spatial data BP from OGC members at next TC

### ISSUE THREAD

**Issue by MichaelGordon** [w3c/sdw#991]
At the next TC (Orleans, France) we should actively look to obtain feedback on the Spatial Data Best Practices - obvious candidates would be those involved in the relevant areas of T14 and WFS 3.0 (and potentially WCS)

**Comment by MichaelGordon** [comment]
@lvdbrink Following your various updates to TC's did we get any other feedback? Otherwise I'm minded to close this.

**Comment by lvdbrink** [comment]
No, nothing new, feel free to close.

**Comment by MichaelGordon** [comment]
Closed as no further feedback.
