### ISSUE TITLE
Range of actsOnProperty and isActedOnBy still incorrect in SOSA figure

### ISSUE THREAD

**Issue by tidoust** [w3c/sdw#995]
Reported on the WG mailing-list in:
https://lists.w3.org/Archives/Public/public-sdw-wg/2018Jan/0000.html

The actuation figures have been fixed by @rgcmme [some time ago](https://github.com/w3c/sdw/commit/09cfe103d21bfd6dd97374f5f7fecb9fd755c38e#diff-53f3b0b0bb3862b056041e3cfe7184f6) (*) but the [SOSA-only actuation figure](https://w3c.github.io/sdw/ssn/images/SOSA-Actuation.png) still incorrectly links `sosa:actsOnProperty` and `sosa:isActedOnBy` to `Actuator`, instead of `Actuation`.

(*) For some reason, the update on the SSN Actuation figure was not included in the published Recommendation, which is my bad :( I'll update the list of errata to mention both diagrams.

**Comment by rgcmme** [comment]
It is very strange, because in the source PPT the figure was already correct.

From the images, the SSN-Actuation.png figure in the repository is already the good one. I have only generated the SOSA-Actuation.png figure.
