### ISSUE TITLE
online version of ssn-dul at does not correspond to the latest one described in the spec

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw#997]
The online version of ssn-dul at http://www.w3.org/ns/ssn/dul does not correspond to the latest one described in the spec. It should correspond to the one at https://github.com/w3c/sdw/tree/gh-pages/ssn/integrated/

**Comment by tidoust** [comment]
@maximelefrancois86 Right, I was waiting for someone to provide the updated `.rdf` files to maintain consistency between the Turtle and RDF/XML versions (see private email from last week).

I think you're the one who provided the current RDF/XML versions of the ontology files. Could you provide the updated ones, and actually push them to the repository as well?

**Comment by tidoust** [comment]
Alternatively, since RDF/XML versions are probably the result of a conversion of the Turtle files, it might be useful and enough to explain somewhere which tool(s) to use and what conversion steps to follow to re-generate the files each time.

**Comment by maximelefrancois86** [comment]
PR #1000 adds the RDF/XML versions, which are converted from the Turtle files using the following procedure:

- open a Turtle file in the Protégé ontology editor
- (optional step: Reasoner -> Start, and check no class is highlighted in red) 
- File->Export, choose RDF/XML, and .rdf extension

**Comment by tidoust** [comment]
Pull request now merged. I updated the online version of ssn-dul at http://www.w3.org/ns/ssn/dul accordingly.
