### ISSUE TITLE
SSN errata in ssnx: problem with disjunction between ssn:Property and  sosa:FeatureOfInterest

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw#999]
I just found an errata with the SSN System Capability module and the alignment to DUL.

ex. with Survival: 

class ssn-system:SurvivalProperty is a sub-class of ssn:Property, and has for inverseof( ssn-system:hasSurvivalProperty ) only (and at least one) ssn-system:SurvivalRange, that is a sub-class of *ssn:Property*
inverseof( ssn-system:hasSurvivalProperty ) is a sub-property of ssn:isPropertyOf
ssn:Property has for ssn:isPropertyOf only *sosa:FeatureOfInterest*

so some instance of ssn-system:SurvivalRange would be both a ssn:Property and a sosa:FeatureOfInterest, which is forbidden. 

For this one, I therefore suggest we accept a feature of interest can also be a quality, and relax axiom (1) and (2) into (1') and  (2') :

sosa:FeatureOfInterest rdfs:subClassOf [ owl:unionOf ( dul:Event dul:Object dul:InformationEntity ) ]  (1)
oldssn:FeatureOfInterest owl:equivalentClass sosa:FeatureOfInterest (2) 

sosa:FeatureOfInterest rdfs:subClassOf dul:Entity  (1')
oldssn:FeatureOfInterest rdfs:subClassOf sosa:FeatureOfInterest (2')

**Comment by maximelefrancois86** [comment]
implemented in PR #1000

**Comment by tidoust** [comment]
Pull request now merged. This issue has been fixed in the Editor's Draft. The published Recommendation cannot be directly updated but a [new entry was added to the errata document](https://www.w3.org/2017/10/vocab-ssn-errata.html#entry-7)
